### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by SymonF** [Stickymaddness/Procurement#1007]
I can't login.

I receive this error:

Authenticating                                                                 [OK]
Fetching account name...                                                                  

[Error] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by SymonF** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3000342/DebugInfo.log)

**Comment by woshikie** [comment]
Was receiving this error, fixed by replacing the POESSID with a new one after logging in on pathofexile.com

**Comment by wakebake357** [comment]
What is POESSID and how can i fix it? have been looking for hours to fix it, no video no nothing just these 3 worded advices that went nowhere... can I get any details? neither Procurement nor Acquisition are working.. HELP PLEASE

**Comment by thailyn** [comment]
Please see the [wiki page](https://github.com/Stickymaddness/Procurement/wiki/SessionID) for information on what the session ID is and how to obtain it.
