### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by chinojuan** [Stickymaddness/Procurement#102]
my acc cant login to procurement

**Comment by chinojuan** [comment]
[Error] Error reading character data for juantalcual, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by medvedttn** [comment]
Make sure that account name (typed in Account Name field) is correct - it's case sensitive.

**Comment by Stickymaddness** [comment]
As mdevedttn said, make sure that you have the account name field filled in - case sensitive!
