### ISSUE TITLE
[PS4]  [Error] Downloading stash for Synthesis

### ISSUE THREAD

**Issue by Waciol** [Stickymaddness/Procurement#1021]
Any ideas whats going on? Is Procurement support PS4 or not? 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3151716/DebugInfo.log)

**Comment by Waciol** [comment]
It seems that sessionID and Alias are ok. I dont know what I'm doing wrong :/
![image](https://user-images.githubusercontent.com/50360248/57288320-868a9300-70b9-11e9-9412-12cf0196ad5b.png)

**Comment by Waciol** [comment]
Ok im dumb... got it - https://github.com/Flenst/Procurement-PS4/releases

**Comment by aydjay** [comment]
@Waciol after #1019 has been released you should be good to go using the normal version.
