### ISSUE TITLE
Refreshing tabs is broken

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#1029]
As I reported previously: https://github.com/Stickymaddness/Procurement/pull/994#issuecomment-490991339

Refreshing just doesn't work, and after the new release, Procurement now crashes after the failed refresh

1.26.1 still refreshes without an issue

[debug.txt](https://github.com/Stickymaddness/Procurement/files/3282442/debug.txt)

**Comment by thailyn** [comment]
Hi, @nqrcqn , the PR I just created fixes not being able to refresh tabs.  I haven't been able to recreate the crash, however; I would suggest completely refreshing your data in Procurement.  If the problem continues, can you provide your `.bin` files?

**Comment by nqrcqn** [comment]
With your fix it now refreshes, but I get the same crash at the end of refresh.
