### ISSUE TITLE
cannot login, getting mutiple errors after GET 500, 503

### ISSUE THREAD

**Issue by bittybong** [Stickymaddness/Procurement#1046]
i tried logging in with my sessionID. also didnt work

idk what do do anymore
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3362029/DebugInfo.log)

**Comment by Stickymaddness** [comment]
500 and 503 errors are GGG's servers not responding, are you still having this issue?

**Comment by bittybong** [comment]
yeah still the same...alrdy redownloaded the software and checked firewall for exceptions but nothing works...

**Comment by Stickymaddness** [comment]
Please retest with [the latest version](https://github.com/Stickymaddness/Procurement/releases/tag/1.28.0) of Procurement
