### ISSUE TITLE
Characters keep loading

### ISSUE THREAD

**Issue by MrMeatflick** [Stickymaddness/Procurement#105]
I couldent find this issue anywhere else so if its a double post im sry in advance

Issue:
All Characters in selected Leagues load into the tabs with unloaded inventory when they shouldent be there at all

Log:
Authenticating "my email"@hotmail.com                                                     [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading Standard Stash Tab 15...                                                          [OK]
Loading Standard Stash Tab 16...                                                          [OK]
Loading Standard Stash Tab 17...                                                          [OK]
Loading Standard Stash Tab 18...                                                          [OK]
Loading Standard Stash Tab 19...                                                          [OK]
Loading Standard Stash Tab 20...                                                          [OK]
Loading Standard Stash Tab 21...                                                          [OK]
Loading Standard Stash Tab 22...                                                          [OK]
Loading Standard Stash Tab 23...                                                          [OK]
Loading Standard Stash Tab 24...                                                          [OK]
Loading Standard Stash Tab 25...                                                          [OK]
Loading Standard Stash Tab 26...                                                          [OK]
Loading Standard Stash Tab 27...                                                          [OK]
Loading Standard Stash Tab 28...                                                          [OK]
Loading Standard Stash Tab 29...                                                          [OK]
Loading Standard Stash Tab 30...                                                          [OK]
Loading Standard Stash Tab 31...                                                          [OK]
Loading Standard Stash Tab 32...                                                          [OK]
Loading Standard Stash Tab 33...                                                          [OK]
Loading Standard Stash Tab 34...                                                          [OK]
Loading Standard Stash Tab 35...                                                          [OK]
Loading Standard Stash Tab 36...                                                          [OK]
Loading Standard Stash Tab 37...                                                          [OK]
Loading Standard Stash Tab 38...                                                          [OK]
Loading Standard Stash Tab 39...                                                          [OK]
Loading Standard Stash Tab 40...                                                          [OK]
Loading Standard Stash Tab 41...                                                          [OK]
Loading Standard Stash Tab 42...                                                          
GGG Server request limit hit, throttling activated. Please wait 32 seconds                [OK]
Loading Mr_Munchies's inventory...                                                        [OK]
Loading MrPunchies's inventory...                                                         [OK]
Loading Nermus_Mooch's inventory...                                                       [OK]
Loading Meatnessfivedaysolosc's inventory...                                              [OK]
Loading Ardaline's inventory...                                                           [OK]
Loading Skrivva's inventory...                                                            [OK]
Loading StaticExile's inventory...                                                        [OK]
Loading HappyTurd's inventory...                                                          [OK]
Loading ABumGang's inventory...                                                           [OK]

And thats after:

```
<Setting name="DownloadOnlyMyLeagues" value="True" />
<Setting name="DownloadOnlyMyCharacters" value="True" /> 
<List name="MyCharacters" /> 
```

Also tried: Same Result

```
<List name="MyCharacters">
</List>
```

This is all after ive set the Download only's before the first launch of the program

What am i doing wrong if anything ? 

Feel free to contact me ingame with a solution or for any aditional info any of the names should work i guess :D

**Comment by Stickymaddness** [comment]
Hmmmm... I'll look into this, if you've set it to not download any characters it shouldn't be loading any character tabs.

**Comment by MrMeatflick** [comment]
Awesome here is a few Screenshots of my procurement showing how ive set it atm :)


http://i.imgur.com/vLxrnAf.png?1
http://i.imgur.com/TIsW63n.png?1
http://i.imgur.com/MD5OqcV.png?1

**Comment by Stickymaddness** [comment]
Are you still seeing this issue with 1.9.3 ? I've been unable to replicate.

**Comment by MrMeatflick** [comment]
Did a clean install of Procurement to 1.9.3 and its still there:

What i did was as follows

1: Went to https://github.com/Stickymaddness/Procurement/releases/tag/1.9.3
2. Clicked on Procurement.1.9.3.zip
3. Copied Everything in the poped up folder to D:\PoE - Procurement
4. Double clicked on Procurement.exe
5. Typed in my Email, Password & Account name
6. Clicked on Login and waited for everything to load
7. Went to "Settings"
8. Checkmarked "Download Only Selected Characters" & "Download Only Selected Leagues" 
9. Checkmarked "Compact Mode"
10. Unchecked "Hardcore" & "Warband" so only "Tempest" & "Standard" was Checkmarked
11. Closed Procurement
12. Double clicked on Procurement.exe
13. Typed in my Email, Password & Account name
14. Clicked on Login and waited for everything to load

And all the characters was still there altho they are no longer listed in the "my email"@hotmail.com"
folder only "characterdata.bin" was there before there was still all the characters in there listed now they are gone from there but still in the program itself :)

Hope it helps

**Comment by Stickymaddness** [comment]
Hi, 

I've only had a chance to look back at your issue again now. In the steps you listed above, when you logged in again after updating your config, did the login still show "Loading character's inventory..." for characters you deselected?

**Comment by MrMeatflick** [comment]
Yes it still showed that altho the tabs for the chars are empty

**Comment by Stickymaddness** [comment]
I somehow lost track of this issue :frowning: 

There have been quite a few releases since, please retest with 1.9.9:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
