### ISSUE TITLE
FR: Add support for blight

### ISSUE THREAD

**Issue by melink14** [Stickymaddness/Procurement#1064]
Currently, doesn't show any blight characters and seems to assume only legion or standard.

**Comment by idSmoker** [comment]
Hopefully its still being actively supported, but its been a week now.

**Comment by aydjay** [comment]
In your settings file you can manually add in Blight in the place of legion.

**Comment by melink14** [comment]
Can you describe how to do it? I did a find and replace for Legion to Blight but it didn't seem to load Blight tabs on load.

**Comment by aydjay** [comment]
There should be a settings.xml in the application folder that you can modify.

**Comment by melink14** [comment]
Yes, that's what I modified but even though I replaced all instances of
Legion with Blight it had no effect.

**Comment by Stickymaddness** [comment]
Let us know if you encounter this issue again in Metamorph, the latest release contains an updated settings file which should load all your league tabs and characters correctly.
