### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

### ISSUE THREAD

**Issue by ArcaneSpark** [Stickymaddness/Procurement#1073]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/3882762/DebugInfo.log)

**Comment by manniL** [comment]
Looks like the page unavailable when u tried it.

**Comment by Stickymaddness** [comment]
[Procurement 1.28.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.28.0) has been released, please retry with the new version of Procurement and log a new issue if the problem persists.
