### ISSUE TITLE
[Error] Cloud flare clearance failed, please wait one minute and try again

### ISSUE THREAD

**Issue by SenSei661** [Stickymaddness/Procurement#1074]
Hi.
I am using procuremnt for 2 weeks, since yesterday I have this Error, earlier it was working perfect.
Extract from DebugInfo:
"
[27-11-2019 19:13] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
[27-11-2019 19:14] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: Wystąpił przynajmniej jeden błąd. ---> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 3 attempt(s).
   w CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   w POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   w POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[27-11-2019 19:14] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': Serwer zdalny zwrócił błąd: (503) Serwer jest niedostępny.
[27-11-2019 19:14] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: Wystąpił przynajmniej jeden błąd. ---> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 3 attempt(s).
   w CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   w POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
   w POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
"

**Comment by thailyn** [comment]
The POESESSID you get from the website is only valid for a limited time.  Make sure you are still logged in to the website, or log out and log in again and get a new session id.

**Comment by SenSei661** [comment]
Thx for response, unfoucountely it's not that. I took POESESSID from other browser, so it is fressh one. I also used password reset and then copied POESESSID or reinstall procurement and all of those did not work.

**Comment by manniL** [comment]
Having the same issue since today. Tried waiting hours & refreshing the session id :|

**Comment by elnoobus** [comment]
Yo! Same problem here, I've been lurking here for THREE days :(.. And today I really got fed up and decided to post.
I am still blocked from entering Procurement ( ver 1.27.2). Same error every single time.

Acquisition tool works perfectly though.

**Comment by Grzy7316** [comment]
I Edited the source code and changed the nuget packages. If you clone my fork (https://github.com/Grzy7316/Procurement.git) and download visual studio community, you can compile it for yourself and have a working version

**Comment by manniL** [comment]
> I Edited the source code and changed the nuget packages. If you clone my fork (Grzy7316/Procurement.git) and download visual studio community, you can compile it for yourself and have a working version

@Grzy7316 I'm aware of that though most ppl using the tool have no dev background. That's why I request a simple way for these ppl to install the fix :relaxed:

**Comment by Stickymaddness** [comment]
[Procurement 1.28.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.28.0) has been released, which includes @Grzy7316 's fix.
