### ISSUE TITLE
Can't log in due to Cloud flare for over 5 hours now

### ISSUE THREAD

**Issue by Hiotsobo** [Stickymaddness/Procurement#1075]
I have Used Procurement for several years. 
I haven't had a problem with logging in before
My session ID and Alias are correct and have not changed
I have been using procurement for Blight league for the last 2 weeks
I currently have version 1.27.2 installed
It was working fine last night. Logged in after work today and I haven't been able to log in since.
I have uninstalled Malware and disabled adblocker, but nothing has been successful
Any help would be appreciated. 
Thanks

**Comment by elnoobus** [comment]
Hey dude im still having the same problem.

Any luck getting through on your side?

**Comment by Grzy7316** [comment]
I Edited the source code and changed the nuget packages to use cloudflarre instead of cloudflareutilities. .f you clone my fork (https://github.com/Grzy7316/Procurement.git) and download visual studio community, you can compile it for yourself and have a working version

**Comment by Stickymaddness** [comment]
[Procurement 1.28.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.28.0) has been released, which includes @Grzy7316 's fix.
