### ISSUE TITLE
[Error] Cloud flare clearance failed, please wait one minute and try again || - Day 3 -

### ISSUE THREAD

**Issue by elnoobus** [Stickymaddness/Procurement#1076]
Hi,
A pretty consistent error really. Happens every.single.time i try.
I've asked around and many people got hit with the same problem. 

Following things have been tried to no success :-
- Deleted poe data from my browser, re-logged, input new session ID into procurement.
- Copy Pasted account name into tool.
- Installed older version of the tool, then deleted it because no w.
- Installed "Acquisition", another merchant tool, input same Session ID, and I get through, everytime in it. But still no luck in Procurement.
- By now I must have tried over 5 IDs to enter, and different aliases.
- Shut down pc, restarted, re-logged.
- Changed wifi connection.
- Changed to few VPNs.
- Probably a few other things.

There is definitely something on cloudflare's end. But acquisition doesn't seem to get walled the same way. I looked into cloudscraper. Does procurement use that?? If so, it might need to be updated or something.

I just wanted to know if the creator/contributors have gone away for some work/vacation, and if something is in the works or expected anytime soon? I've tried to stick to procurement but 3 days of total blackout is really disheartening, especially after spending several hours trying to fix the problem from my side.

Thanks!

**Comment by Grzy7316** [comment]
I made a fix to this where I replaced the Cloudflareutilities with CloudflareRe, which allows me to log in and load my stuff.  Pull Request #1077 allows for login.

**Comment by elnoobus** [comment]
> 
> 
> I made a fix to this where I replaced the Cloudflareutilities with CloudflareRe, which allows me to log in and load my stuff. Pull Request #1077 allows for login.

Hi, thanks for replying! Im not sure what you mean by "replaced". Did you fix it by changing the name, or made some other changes?

**Comment by Grzy7316** [comment]
I Edited the source code and changed the nuget packages. If you clone my fork (https://github.com/Grzy7316/Procurement.git) and download visual studio community, you can compile it for yourself and have a working version

**Comment by elnoobus** [comment]
>  visual studio community

I see now. Thanks a lot for the link, I'll look up visual studio community.

**Comment by Stickymaddness** [comment]
[Procurement 1.28.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.28.0) has been released, which includes @Grzy7316 's fix.

**Comment by Gumaks** [comment]
Hi, i have latest version and its steel dont work...

**Comment by thailyn** [comment]
When you say the latest version, do you mean the version downloadable from #1093 ?  There have been several updates to Cloudflare and I have been making patches to handle them.  If you're still having problems with that version, please create a new issue and include your `DebugInfo.log` file.  Thanks!
