### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by pilvebaleriin** [Stickymaddness/Procurement#108]
Procurement 1.9.2 Initialized.
                                                           
Authenticating pilv                                                                       [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading mahutaja's inventory...                                                           

[Error] Error reading character data for mahutaja, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Stickymaddness** [comment]
Make sure that you have the account name field filled in, note that it is case sensitive!

**Comment by Stickymaddness** [comment]
To clarify:

![accountname](https://cloud.githubusercontent.com/assets/6553902/7933116/4fd693e8-091d-11e5-80f5-eda0bde0a530.PNG)

**Comment by jorupp** [comment]
I was getting that exact error until I fixed the account name.  I'm guessing this can be closed.
