### ISSUE TITLE
Alian and Session ID

### ISSUE THREAD

**Issue by PureOrgasm** [Stickymaddness/Procurement#1084]
I wanted to use the program, but I don't know what those 2 fields are! In youtube only appears to me that before was the email and the password!
Someone tell me what is Alias ​​and Session ID.
Thanks

**Comment by thailyn** [comment]
Please see the wiki article [here](https://github.com/Stickymaddness/Procurement/wiki/SessionID) for how to get the Session ID.  Alias is an arbitrary name you give for that login.

**Comment by PureOrgasm** [comment]
thank you very much already got it, and good new year ;)

**Comment by thailyn** [comment]
Thank you for the update.  Please close this issue now that it is resolved.
