### ISSUE TITLE
Unable to log in with session ID

### ISSUE THREAD

**Issue by Zarggg** [Stickymaddness/Procurement#1091]
I am unable to log in using a PoE session ID. The debug log implies there may be issues with Cloudflare.

Using Offline mode seems to be fine.

[DebugInfo.log](https://pastebin.com/wc4f13sw)

**Comment by thailyn** [comment]
I can replicate this issue.  It looks like Cloudflare has updated one of its challenges.  There is a [pull request](https://github.com/RyuzakiH/CloudflareSolverRe/pull/18) for the library we use for Cloudflare authentication that claims to fix this issue.  I should be able to make a PR for Procurement that patches in this bug fix, as a short-term solution.

**Comment by thailyn** [comment]
Please try the version of Procurement from PR #1093, available at [this link](https://ci.appveyor.com/api/buildjobs/aacqr4881mirn6ai/artifacts/Procurement%2Fbin%2FProcurement.zip).  It worked for me to be able to log in to Procurement.

**Comment by Zarggg** [comment]
I can confirm it lets me log in.

**Comment by arsirantala** [comment]
I can't login with sessionId either (I used the test version from above link as well).

Please see:
[DebugInfo.log](https://www.dropbox.com/s/um4vpyfqxis4xvm/DebugInfo.log?dl=0)

**Comment by thailyn** [comment]
You're getting 503 and 401 errors from the server. The former suggests an
issue on GGG's end, and you can try again later. The latter suggests you
failed to authenticate properly. I would suggest you get a new Session ID
by logging out and back in to the website, and try logging in with that in
Procurement.
