### ISSUE TITLE
ERROR in LOG IN PLEASE HELP

### ISSUE THREAD

**Issue by ameen1998** [Stickymaddness/Procurement#1098]
i installed procurment latest version and have this error [Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log , please help ?  
pealse help

**Comment by thailyn** [comment]
Please attach your `DebugInfo.log` file (which is in the same directory as `Procurement.exe`), as the error message requests, and provide more details on what you are doing when you are getting this error.  Have you successfully used Procurement before?

**Comment by ameen1998** [comment]
i have never used it before , although i added my correct alias and ID , and just pressed log in , though the log in button wasnt working untill i ran the program as administrator , and now after pressing log in multiple times because each time i press osmetimes says  or or more errors  but eventualy it works , and gives me this error for downloading stash .
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/4448640/DebugInfo.log)

**Comment by thailyn** [comment]
Ah, there is an out-of-date library in the latest release. Please follow
the link provided in the comment here --
https://github.com/Stickymaddness/Procurement/issues/1091#issuecomment-596160251
-- to download a patched version of Procurement with which you should be
able to log in.

**Comment by ameen1998** [comment]
pfft, it now needs 1 time to press the log in button but it still have the error same one here is the new log . 
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/4448739/DebugInfo.log)

**Comment by ameen1998** [comment]
dont give up on me bro haha

**Comment by thailyn** [comment]
You're getting 503 (Server Unavailable) and 404 (Not Found) errors when accessing the API.  The 503 errors suggest something is going wrong on GGG's end.  Please try to get a fresh SessionID from the browser (log out, then log in and use the guide [here](https://github.com/Stickymaddness/Procurement/wiki/SessionID)) and try to log in again.

**Comment by ifkvothe** [comment]
again the next msj: Cloud flare clearance failed, please wait one minute and try again.

impossible to login

please help me

**Comment by thailyn** [comment]
@ifkvothe , please see #1104. (You don't need to update multiple bugs when you have an issue.)

**Comment by Stickymaddness** [comment]
[Procurement 1.29.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0) has been released, which fixes this issue.
