### ISSUE TITLE
(error) One or more errors have occurred.

### ISSUE THREAD

**Issue by conner53** [Stickymaddness/Procurement#1102]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/4471078/DebugInfo.log)

also no message for the forum from poexyzis

**Comment by thailyn** [comment]
There is an out-of-date library in the latest release. Please follow the link provided in the comment [here](https://github.com/Stickymaddness/Procurement/issues/1091#issuecomment-596160251) to download a patched version of Procurement with which you should be able to log in.

I don't know what you mean by your second point.

**Comment by conner53** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/4471260/DebugInfo.log)
 


I keep getting the same error

**Comment by thailyn** [comment]
The API is returning 503 errors, which could indicate there is an issue on GGG's side.  Make sure you are using a SessionID that is still valid (create and use a new one if you aren't sure).  If you're still getting errors, please wait a little bit to see if it is a temporary issue on GGG's side.

**Comment by conner53** [comment]
![image](https://user-images.githubusercontent.com/63609185/79196653-222f9200-7e39-11ea-80da-49ae111a425f.png)

I have resolved this issue but the link for poe.trade URL does not come from poexyzis

**Comment by thailyn** [comment]
poe.trade and poexyzis are not related to Procurement.  I don't know why you're not getting a response.
