### ISSUE TITLE
Procurement Error

### ISSUE THREAD

**Issue by FoxMulderlolzzz** [Stickymaddness/Procurement#1105]
I use this software since 2 weeks ago and today have one error:

[Error] Cloud flare clearance failed, please wait one minute and try again

Please, idk what i can do to fix

**Comment by thailyn** [comment]
I made a new patched version of Procurement that uses an updated version of a library to work with Cloudflare's latest changes.  Please see the comment [here](https://github.com/Stickymaddness/Procurement/issues/1104#issuecomment-619186336) for details and a download link.

**Comment by FoxMulderlolzzz** [comment]
> I made a new patched version of Procurement that uses an updated version of a library to work with Cloudflare's latest changes. Please see the comment [here](https://github.com/Stickymaddness/Procurement/issues/1104#issuecomment-619186336) for details and a download link.

Thx! i'll check if this version will works!

**Comment by FoxMulderlolzzz** [comment]
> I made a new patched version of Procurement that uses an updated version of a library to work with Cloudflare's latest changes. Please see the comment [here](https://github.com/Stickymaddness/Procurement/issues/1104#issuecomment-619186336) for details and a download link.

Work for me!! Thx very much!!

**Comment by Stickymaddness** [comment]
[Procurement 1.29.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0) has been released, which includes @thailyn's fixes as per the build he provided above.
