### ISSUE TITLE
[Issue] when logging in, 503 error with latest patched version

### ISSUE THREAD

**Issue by Pollux3737** [Stickymaddness/Procurement#1108]
Hello, I've got the last patched version of the Procurement (no more problem with CloudFlare). I've been getting this issue instead :

> [03-05-2020 14:53] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': Le serveur distant a retourné une erreur : (503) Serveur non disponible.
> [03-05-2020 14:53] System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
> Nom de fichier : 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    à POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
>    à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
>    à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
>    à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
>    à System.Threading.Tasks.Task.Execute()
> 
> AVT : la journalisation de liaison d'assembly est désactivée.
> Pour activer la journalisation des échecs de liaison d'assembly, attribuez la valeur 1 à la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD).
> Remarque : une certaine perte de performance est associée à l'enregistrement dans le journal des échecs de liaison d'assembly.
> Pour désactiver cette fonctionnalité, supprimez la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> [03-05-2020 14:55] System.Net.CookieException: La partie 'Value'='System.Net.Http, Version=4.1.1.0' du cookie n'est pas valide.
>    à System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean set_default, Boolean isThrow)
>    à System.Net.CookieContainer.Add(Cookie cookie)
>    à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password)
>    à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, String realm)
>    à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
>    à System.Threading.Tasks.Task.Execute()

I'm guessing it has something to do wit my .Net install, but I'm not sure.

Thanks in advance.

**Comment by thailyn** [comment]
Thanks for the report.  I was concerned my latest patched version would encounter some issues, as I updated the .NET target framework from 4.5 to 4.6.2, and this appears to be the causing this problem.  I'll work on fixing the issue, but it was probably working fine for me because I have all these framework versions already installed.

**Comment by Pollux3737** [comment]
Just installed the .NET runtime framework version 4.6.2 and it didn't solve the issue. No idea if it will help you track it down.

**Comment by thailyn** [comment]
Thanks for the update.  I'm pretty sure I know how to fix it, just need a little time to do so.

**Comment by thailyn** [comment]
Hi, @Pollux3737 , please try the latest version [here](https://ci.appveyor.com/api/buildjobs/ax8u4jwg41eeokpw/artifacts/Procurement%2Fbin%2FProcurement.zip).  There is still one possible issue I need to look at, but hopefully it doesn't cause issues.

**Comment by thailyn** [comment]
Actually, the other issue appears to have be easy to fix.  I have an even newer version [here](https://ci.appveyor.com/api/buildjobs/lc4i74anq683ty81/artifacts/Procurement%2Fbin%2FProcurement.zip) you can try.

**Comment by Pollux3737** [comment]
Thank you very much, your last version is working like a charm! Only a few graphics quirks, but I'll post that in another thread.
