### ISSUE TITLE
Error One or more errors occurred.

### ISSUE THREAD

**Issue by LiteNiteFrack** [Stickymaddness/Procurement#1110]
downloaded the link from "Procurement not working #1106 
Not working.
Properties on the CloudflareSolverRe.dll  show a created date of April 24/2020
Product/File version 1.0.6
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/4600792/DebugInfo.log)
Thank you for any and all help.

**Comment by thailyn** [comment]
Sorry for the confusion, as there are now at least three different patched versions of Procurement I've made for fixing Cloudflare issues, and I link to different ones in comments in bugs as I release them. I will now keep the description of the PR with this fix, #1093, up to date with the latest link.  Please follow look at that PR for the latest download link.

**Comment by LiteNiteFrack** [comment]
Charles,

            NP. It is working fine now. I appreciate how quick Procurement gets errors looked after. I think it is pretty amazing.

 

Thank you,
