### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Fabianero** [Stickymaddness/Procurement#1112]
Hello i have error i can't log in. Before it works but now it doesn't.
I read 1 thread before that was about this problem but i doesn't work anymore.
![image](https://user-images.githubusercontent.com/65435134/82109825-687a5880-9739-11ea-9ad5-0a5b03a287eb.png)

**Comment by Reithan** [comment]
@thailyn is working on this in #1111

**Comment by thailyn** [comment]
I've created a new patched version of Procurement that uses an updated version of the Cloudflare library.  Please download it from the link in the initial description of PR #1093.

**Comment by Stickymaddness** [comment]
[Procurement 1.29.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0) has been released, which fixes this issue.
