### ISSUE TITLE
Update for Harvest

### ISSUE THREAD

**Issue by FoxMulderlolzzz** [Stickymaddness/Procurement#1115]
Hello! Do u have Procurement for Harvest version?

**Comment by thailyn** [comment]
Are you referring to some specific Harvest-related features that need to be added?  The image on the login page is for a previous league, but that's just for appearances and won't impact the functionality.

I know we could add item filters for seeds and the new items introduced (like the new uber lab keys?), but I'm not aware of any major new features.  Or is there something else I'm not aware of?

**Comment by FoxMulderlolzzz** [comment]
> Are you referring to some specific Harvest-related features that need to be added? The image on the login page is for a previous league, but that's just for appearances and won't impact the functionality.
> 
> I know we could add item filters for seeds and the new items introduced (like the new uber lab keys?), but I'm not aware of any major new features. Or is there something else I'm not aware of?

No no, 
I just ask about some new version. didn't know how to ask if I had a new version of the procurement for Harvest. 

Do u can give me the download link? B'cuz my procurement is not work for me.

**Comment by thailyn** [comment]
Ah, I see what you mean.  There hasn't be an official release in a while, but there have been Cloudflare changes which have caused a problem with Procurement.  I have been maintaining a patched version to fix this that is available in #1093, and there is another pull request that other users have said works that is available in #1114 .

**Comment by FoxMulderlolzzz** [comment]
> > Are you referring to some specific Harvest-related features that need to be added? The image on the login page is for a previous league, but that's just for appearances and won't impact the functionality.
> > I know we could add item filters for seeds and the new items introduced (like the new uber lab keys?), but I'm not aware of any major new features. Or is there something else I'm not aware of?
> 
> No no,
> I just ask about some new version. didn't know how to ask if I had a new version of the procurement for Harvest.
> 
> Do u can give me the download link? B'cuz my procurement is not work for me.

Thank you!

**Comment by GThunda** [comment]
I'm sorry. I'm not a coder. How do I download the files need to fixe the program?
