### ISSUE TITLE
Can't get it to run?

### ISSUE THREAD

**Issue by disco2008** [Stickymaddness/Procurement#1119]
Ok this is kind of a noob question but how on earth do I run this lol. I dont see an exe; only see sln files that take me into visual studio as a project. Am I missing something? Thanks

**Comment by disco2008** [comment]
before you ask yes I extracted the zip lol

**Comment by Zarggg** [comment]
Download a [release](https://github.com/Stickymaddness/Procurement/releases/tag/1.29.0), not the source code.

**Comment by thailyn** [comment]
@disco2008 , were you able to run the exe after downloading a release?
