### ISSUE TITLE
Error when updating for the first time.

### ISSUE THREAD

**Issue by deax9999** [Stickymaddness/Procurement#1120]
[Error] Downloading stash for SSF Standard and just said to report here with attached DebugInfo.log

If you need further information or help just let me know.

Thanks!
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/5349612/DebugInfo.log)

**Comment by thailyn** [comment]
I see there are some 404 errors when attempting to fetch stash tabs, but they don't look wrong.  I've seen this error a few times, but haven't been able to track down the cause.  If you log out and back in on the website and get a new SessionID, does that fix the issue?

**Comment by deax9999** [comment]
One of the things that dawned on me is that I had changed some of my stash
tab names and wonder if that's where the 404's come from. Let me try what
you suggested and get back to you.

**Comment by deax9999** [comment]
Ok I got it fixed. I had a character in the SSF Standard that hadn't been
migrated. I didn't even know it was there. Once I deleted the character and
reran Procurement everything went through with no errors. I hope this helps.
