### ISSUE TITLE
Stash Download Error

### ISSUE THREAD

**Issue by Lanzlo** [Stickymaddness/Procurement#1125]
Error downloading SSF Stash data. Here's the DebugInfo.log.
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/5491399/DebugInfo.log)

**Comment by thailyn** [comment]
You're getting a 429 error from GGG, which means you're sending too many requests (e.g., for stash contents).  GGG sets a limit for the number of stashes you can query over a time period (per SessionID), and Procurement respects that, by default.  Did you close and reopen Procurement quickly, causing it to refresh tabs again?  Are you using another app that uses the same SessionID?  Apps tends to assume they do not need to throttle their requests below GGG's limit, including Procurement, by default.

**Comment by Lanzlo** [comment]
Resolved. Restarted my machine. I think I was using another app that used the SessionID.
