### ISSUE TITLE
Error reading character data, and yes, every field has been written properly.

### ISSUE THREAD

**Issue by LordRegulus** [Stickymaddness/Procurement#113]
Procurement 1.9.2 Initialized.
                                                           
Authenticating (my email)                                                     [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 2...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading Standard Stash Tab 15...                                                          [OK]
Loading Standard Stash Tab 16...                                                          [OK]
Loading Standard Stash Tab 17...                                                          [OK]
Loading CauseImAwesomeLikeThat's inventory...                                             

[Error] Error reading character data for CauseImAwesomeLikeThat, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by LordRegulus** [comment]
Hi i changed the value of DownloadOnlyMyCharacters to true and it worked. was it supposed to stay false?

**Comment by Stickymaddness** [comment]
Have you been filling in the account name field when logging in? Case sensitive.

**Comment by LordRegulus** [comment]
As said in the title, yeah.

**Comment by Stickymaddness** [comment]
To clarify, account name is as follows:

![accountname](https://cloud.githubusercontent.com/assets/6553902/7933116/4fd693e8-091d-11e5-80f5-eda0bde0a530.PNG)

If you are **100%** certain that you have it entered correctly, it's possible that you have an old race character which cases your login error when DownloadOnlyMyCharacters = false
