### ISSUE TITLE
Procurement 1.9.2 issue

### ISSUE THREAD

**Issue by diegomengue** [Stickymaddness/Procurement#117]
Hello.

So I've been trying to log in at procurement using the SessionID method. When I imput my alias, sessionID taken from chrome and username, the program shows

Procurement 1.9.2 Initialized.
Authenticating Lohfnar.

and thats all.. It doesnt freeze or anything, but it just stays there what seems to be forever.

Any tips?

**Comment by Stickymaddness** [comment]
Procurement 1.9.3 has just been released, please test with the new version and see if the issue persists. Make sure to run as administrator !

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.3
