### ISSUE TITLE
 [Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by trOyy** [Stickymaddness/Procurement#119]
Hi there,

Procurement 1.9.2 Initialized.
                                                           
Authenticating ****                                                         [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]
Loading Standard Stash Tab 9...                                                           [OK]
Loading Standard Stash Tab 10...                                                          [OK]
Loading Standard Stash Tab 11...                                                          [OK]
Loading Standard Stash Tab 12...                                                          [OK]
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading Standard Stash Tab 15...                                                          [OK]
Loading Standard Stash Tab 16...                                                          [OK]
Loading Standard Stash Tab 17...                                                          [OK]
Loading Standard Stash Tab 18...                                                          [OK]
Loading Standard Stash Tab 19...                                                          

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
Hi, you need to send me the details logged to the DebugInfo.log file, however a new version of Procurement has just been released. 

Please test with the new version and let me know if this is still a problem.
