### ISSUE TITLE
Forum export is broken.

### ISSUE THREAD

**Issue by Brentc360** [Stickymaddness/Procurement#121]
Hello, I will attempt to explain my problem.

What is happening is when I go to Forum Export tab and go to select the tabs I want to populate it automatically fills the page with 10 tabs worth of OLD items "even though I have only clicked on ONE tab"  like it has a save somewhere and only wants to load them item. 

It also will not update my shop page with this old code either. 

I have tried uninstalling from my control panel and deleting the file folder neither seem to fix the problem.

PLEASE help it is vital to have Procurement up and working for 2.0!

**Comment by Stickymaddness** [comment]
Procurement 1.9.3 has been released, please do a full update and test with the new version.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.3

**Comment by Harest** [comment]
I was using 1.9.0 back in the days of the T/B 1m league for the first time. I updated to 1.9.2 yesterday, and yep it didn't work. Seems like i didn't choose the right time to update, it now works properly w/ 1.9.3, thanks.

**Comment by Stickymaddness** [comment]
Glad to hear it's sorted.
