### ISSUE TITLE
Cleaner UI?

### ISSUE THREAD

**Issue by basmith7** [Stickymaddness/Procurement#124]
Have you considered using a more simple, Windows themed UI?

**Comment by Stickymaddness** [comment]
It depends what you mean by a windows themed UI. 

If you mean replace the PoE window decorations and buttons with stock windows style border and buttons, sure maybe. 

If you mean overhaul the entire UI and replace everything including the stash, character inventories into say a windows style grid, that's not going to happen.

**Comment by basmith7** [comment]
Definitely the first one.

**Comment by Stickymaddness** [comment]
Alright, I'll look at updating the UI once higher priority issues have been addressed.

**Comment by Stickymaddness** [comment]
I've added support for "minimal mode" (enabled via settings file). Procurement will load with a standard window with no POE ornamentation and the standard minimize/close buttons. 

Will be included in the next release.

**Comment by basmith7** [comment]
Perfect.
