### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by iphone55** [Stickymaddness/Procurement#125]
[Error] Error reading character data for NeverFarts, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Stickymaddness** [comment]
Make sure your account name is correct (case sensetive), if that still doesn't work open your settings.xml file and set the following:

<Setting name="DownloadOnlyMyCharacters" value="True" />
