### ISSUE TITLE
No Awakening weapons, maps in data.xml

### ISSUE THREAD

**Issue by hupple** [Stickymaddness/Procurement#127]
I downloaded 1.9.3 and found that although cards are added, new weapons and maps are not in data.xml, which means if I use trading template provided with Procurement, they won't show up.

**Comment by Stickymaddness** [comment]
I'll get this added for the next release, if you happen to have an updated data.xml already feel free to share!

**Comment by Stickymaddness** [comment]
Support for awakening weapons and maps has been added.
