### ISSUE TITLE
Importing buyouts from before 1.9.3 

### ISSUE THREAD

**Issue by ladyloriana** [Stickymaddness/Procurement#128]
I still have my old buyouts.xml file from 1.9.2 before GGG broke the links. How can I import my butouts into 1.9.3? I have three full shop threads and it will take me hours to reprice everything. Thanks for your help!

**Comment by Stickymaddness** [comment]
Unfortunately there is no easy way to import them, since it was something GGG changed. If you can send me your original buyouts file as well as your current .bin files, I will see about writing an importer tool.

**Comment by ladyloriana** [comment]
Thanks for your reply! Where can I find my .bin files? How would you prefer I send them?

**Comment by Stickymaddness** [comment]
If you go to your Procurement folder, you will see a subfolder with your email address or alias, inside are the .bin files which are a cache of all your items.

Make sure that you do a new login so that all the items are up to date. 

Unfortunately github doesn't allow attachments, so you can either zip and upload the files to a file host, or email them to me.

**Comment by ladyloriana** [comment]
I sent them to you via a message on pathofexile.com. Thanks a ton!

**Comment by Stickymaddness** [comment]
I'm afraid an importer is not going to be possible, GGG didn't just change the urls from http to https as I had thought, the images are also stored on entirely different domain which makes matching up the old hash practically impossible.

I know it must be really annoying to have a large number of buyouts disappear like that, it's a bit like the rug has been pulled from under me as well, the buyout system has been working for over two years and I didn't expect GGG to suddenly change their image domain.

**Comment by ladyloriana** [comment]
Darn, that's too bad. Thanks for looking into it anyway. Appreciate your help.

**Comment by Stickymaddness** [comment]
No problem, sorry I couldn't be of more help.
