### ISSUE TITLE
Error Logging In

### ISSUE THREAD

**Issue by Monoriss** [Stickymaddness/Procurement#129]
I just tried to login inside Procurement, here is what the debug info says 

http://pastebin.com/3V0RS6YQ

**Comment by Stickymaddness** [comment]
MAke sure your account name is correct (case sensitive)

![accountname](https://cloud.githubusercontent.com/assets/6553902/8767213/77164504-2e55-11e5-9d19-aa1728dc8df5.PNG)

If you are 100% it's correct and you still get the same error, edit your settings.xml file and set the following:

<Setting name="DownloadOnlyMyCharacters" value="**True**" />

**Comment by Monoriss** [comment]
Forgot to say that 15 minutes later it decided to fix on itself :X Thanks for the response tho :P I'll have that in mind if it happens in the future
