### ISSUE TITLE
[Error] Downloading stash for , details logged to DebugInfo.log, please open a ticket at 

### ISSUE THREAD

**Issue by Xianchija** [Stickymaddness/Procurement#130]
[19-07-2015 16:06] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei

**Comment by Stickymaddness** [comment]
Have you used Procurement before? Are you a steam user?

**Comment by Xianchija** [comment]
Yes and no, iam not a steam user

**Comment by Stickymaddness** [comment]
It looks like the GGG servers are returning no data for your account, have you tried logging in with sessionID ?
