### ISSUE TITLE
Can't load character inventory

### ISSUE THREAD

**Issue by eskaip** [Stickymaddness/Procurement#133]
Hello, everytime i startup procurement and log in everything is loading fine until procurement wants to load the inventory of any chracter of mine.

>[21-07-2015 12:04] Error reading character data for character 'Wandeskaip', Exception info: 
>[21-07-2015 12:04] System.Exception: Error reading character data for Wandeskaip, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   bei POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
  bei Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

i get that error everytime and i only can load my stash tabs in procurement and none of my character inventorys

**Comment by AntiMatterDotA** [comment]
Same issue here i believe. I cannot view my characters' inventory's or equipped items in procurement and as such also cannot upload them to my trading thread.
Image displaying problem: http://gyazo.com/ec5831a30c6e9145b738ab6aaf72256c

**Comment by Stickymaddness** [comment]
@eskaip Set Procurement to not download any characters and see if that helps, in your settings set:

<Setting name="DownloadOnlyMyCharacters" value="True" />

and make sure the character list is empty: 

    <List name="MyCharacters" />

@AntiMatterDotA it sounds like you've set your Procurement not to download characters, which is why their inventories are empty.

**Comment by eskaip** [comment]
@Stickymaddness Yeah, i already did that, can start procurement now, but still can't load my characters' inventory :)

**Comment by Stickymaddness** [comment]
Alright, now the most likely reason you can't load your characters is that your account name is wrong, note that it's case sensitive :

![accountname](https://cloud.githubusercontent.com/assets/6553902/8993124/31a7a9ca-3703-11e5-90f1-2465e0ecce26.PNG)

**Comment by eskaip** [comment]
Ah nice, i didn't know it was case sensitive, thanks, that did the trick :D
