### ISSUE TITLE
[Error] No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.

### ISSUE THREAD

**Issue by JackRayleigh** [Stickymaddness/Procurement#135]
I've tried changing the settings file to only download my League characters

I've removed the leagues out that I don't want, leaving only Warbands 

I've tried using Session ID to log in, but still doesn't work. 

I have the game through steam, and my character is on Warbands but even my one on Normal and my tempest one won't work either. 

Name is entered correctly and case sensitive etc is fine because it logs in until it hits the character load part and then crashes. 

Am I doing something wrong? Thanks for any help

**Comment by Stickymaddness** [comment]
Try edit the settings file to download *no characters*, and see if you can login.
