### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Tanel468** [Stickymaddness/Procurement#136]
Hi.
Downloaded the concept, started it up inserted all the info needed which is my email username and password to log in but it just keeps telling me that the password is wrong or username is wrong. I've already gotten 3600sec protection timers when trying to login to path of exile forums, reset my password and still same issue.
What have i done wrong?

**Comment by Stickymaddness** [comment]
Have you tried logging in with session ID?

**Comment by Tanel468** [comment]
Dunno what this was about, i messed aroound the whole day with it,
restarted the pc and moved the folder around and whatever no success, it
made me reset my poe password 2 times because it just gave me massive
timers for protection. Next day login in the morning, boom, works.
Thanks for help!

2015-07-28 22:20 GMT+03:00 Stickymaddness <notifications@github.com>:

**Comment by Stickymaddness** [comment]
Haha alright, glad it's sorted!
