### ISSUE TITLE
Issues with the forum update/export feature

### ISSUE THREAD

**Issue by AntiMatterDotA** [Stickymaddness/Procurement#138]
Have a few issues probably tied together with the Forum Export page of the program.
1: Cannot paste more than one line of text into the "Forum Export" section. Regardless of where i copy from - notepad, word, the "forum template" section, etc. I can't paste any more than one line of data into the forum export.
2: Cannot manually line break. So there is no work around for adding custom text to the thread via the program if more than one line of code/text is required.

**Comment by Stickymaddness** [comment]
I can't replicate your issue, are you using the latest version (1.9.3) ?

The forum export section is saved to ForumExportTemplate.txt, you can edit that file manually as well.
