### ISSUE TITLE
Account name is case sensitive

### ISSUE THREAD

**Issue by Novarg** [Stickymaddness/Procurement#141]
Account name is case sensitive and no data can be loaded if any character is in wrong case in that field. Furthermore after closing program it saves login data and restore account name in lowercase that prevent to login and load data.

**Comment by Stickymaddness** [comment]
Nothing I can do about account name being case sensitive, it's a restriction imposed by GGG. 

Edit settings.xml and change the AccountName setting to the correct case and save, next time you run Procurement it will be in the correct cas.
