### ISSUE TITLE
Can't load characters 

### ISSUE THREAD

**Issue by MoLt1eS** [Stickymaddness/Procurement#145]
[Error] There was an error deserializing the object of type System.Collections.Generic.List`1[[POEApi.Model.JSONProxy.Character, POEApi.Model, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'.

**Comment by Stickymaddness** [comment]
The error is due to Procurement not getting valid data back when it tries to connect to the GGG servers, are you behind a firewall or proxy or anything that could be blocking the request?

**Comment by MoLt1eS** [comment]
I used the token session instead of login and started working, that's how i managed to used Procurement.

**Comment by Stickymaddness** [comment]
To confirm, are you saying you are now able to login successfully with sessionID ?

**Comment by MoLt1eS** [comment]
Yes
