### ISSUE TITLE
Wrong Errormessage if confirming with Enter on Login

### ISSUE THREAD

**Issue by wlfbck** [Stickymaddness/Procurement#146]
If you type in all 3 fields and confirm with Enter while in "Account name", you get an error message saying something like "you have to enter an account name". Clicking the button works of course.

**Comment by Stickymaddness** [comment]
This is due to a rather annoying limitation in WPF, I'll see if I can find a workaround for the next release.

**Comment by Stickymaddness** [comment]
This should be fixed with the new version, since account name is no longer required.
