### ISSUE TITLE
unhandled error when import own template

### ISSUE THREAD

**Issue by hekkktorr** [Stickymaddness/Procurement#147]
hi,

i get an unhandled error when i try to load my own template.
is there a small tutorial ?

thanks in advance

**Comment by Stickymaddness** [comment]
There's a brief wiki guide here : https://code.google.com/p/procurement/wiki/MultipleForumTemplates

**Comment by hekkktorr** [comment]
i followed the guide but i get the error when i click on the stash tabs.

**Comment by Stickymaddness** [comment]
What error do you get? Can you send me the details in the debug log

**Comment by hekkktorr** [comment]
[01-08-2015 15:47] Application Version: Procurement 1.9.3
[01-08-2015 15:47]
CurrentCulture: de-DE
CurrentUICulture: de-DE
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Current League: Standard

[01-08-2015 15:47] System.Windows.Markup.XamlParseException: Durch den 
Aufruf des Konstruktors für Typ "Procurement.Controls.ForumExport", der 
den angegebenen Bindungseinschränkungen entspricht, wurde eine Ausnahme 
ausgelöst. ---> System.ArgumentOutOfRangeException: Die Länge darf nicht 
kleiner als 0 (null) sein.
Parametername: length
    bei System.String.Substring(Int32 startIndex, Int32 length)
    bei 
Procurement.ViewModel.ForumExportVisitors.StashVisitor.getToken(Int32 
location, String current)
    bei 
Procurement.ViewModel.ForumExportVisitors.StashVisitor.getTokenLocations(String 
current)
    bei 
Procurement.ViewModel.ForumExportVisitors.StashVisitor.Visit(IEnumerable`1 
items, String current)
    bei 
Procurement.ViewModel.ForumExportViewModel.getFinal(IEnumerable`1 items)
    bei Procurement.ViewModel.ForumExportViewModel.updateText()
    bei Procurement.ViewModel.ForumExportViewModel..ctor()
    bei Procurement.Controls.ForumExport..ctor()
    --- Ende der internen Ausnahmestapelüberwachung ---
    bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, 
IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, 
Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
    bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader 
xamlReader, Boolean skipJournaledProperties, Object rootObject, 
XamlAccessLevel accessLevel, Uri baseUri)
    bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, 
ParserContext parserContext, Object parent, Boolean closeStream)
    bei System.Windows.Application.LoadComponent(Object component, Uri 
resourceLocator)
    bei Procurement.View.TradingView..ctor()
    bei Procurement.ViewModel.ScreenController.execute(Object obj)
    bei System.Windows.Controls.Button.OnClick()
    bei 
System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs 
e)
    bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, 
Object target)
    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, 
RoutedEventArgs args, Boolean reRaised)
    bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, 
RoutedEventArgs args, RoutedEvent newEvent)
    bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, 
Object target)
    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, 
RoutedEventArgs args, Boolean reRaised)
    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, 
RoutedEventArgs args)
    bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
    bei System.Windows.Input.InputManager.ProcessStagingArea()
    bei System.Windows.Input.InputProviderSite.ReportInput(InputReport 
inputReport)
    bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr 
hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, 
Int32 y, Int32 wheel)
    bei 
System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, 
WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr 
hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr 
wParam, IntPtr lParam, Boolean& handled)
    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    bei 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Int32 numArgs)
    bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object 
source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)


Am 01.08.2015 um 14:28 schrieb Stickymaddness:

**Comment by hekkktorr** [comment]
can somebody explain how to activate the own template once imported in 
the .xml ?

best regards,
hekktorr

**Comment by Stickymaddness** [comment]
It looks like there's an issue with the contents of some of your tabs, what I would suggest is making a clean install of Procurement, doing a full update and seeing if the export works with the default template. Once you have established that's working we can look at custom templates.

What are you trying to achieve with a second custom template? Do you want to run multiple shops or do you just want to change the layout of the default template?

**Comment by hekkktorr** [comment]
hi,

the default template works fine.

i'd like to import my template:


Welcome to my shop(Last Updated {LastUpdated}),

Please message me ingame if something catches your eye. My IGN is {IGN}.

If you don't like a price feel free to make an offer. Don't have the 
currency I'm asking for? Offer me equivalent (please tell me before 
putting a pile of random currency).


[spoiler=" Not Yet Sorted Gear "]
{Stash:ToSell}
[/spoiler]


[spoiler=" Featured Gear "]
{Stash:b/o}
[/spoiler]
[spoiler="    ~b/o 1 exalted Gear    "]
{Stash:1Ex}
[/spoiler]
[spoiler="    ~b/o 10-20 chaos Gear    "]
{Stash:10-20c}
[/spoiler]
[spoiler="    ~b/o <10 chaos Gear    "]
{Stash:<10c}
[/spoiler]
[spoiler="    ~b/o 1 chaos Gear    "]
{Stash:1c}
[/spoiler]
[spoiler="    ~b/o 1 alchemy    "]
{Stash:1a}
[/spoiler]
[spoiler="    Uniques as Priced   "]
{Stash:U1
[/spoiler]
[spoiler="    Uniques as Priced..   "]
{Stash:U2
[/spoiler]

**Comment by Stickymaddness** [comment]
Alright, great. Then you can just edit the existing template. Either under the forum template tab in Procurement, or you can edit the file ForumExportTemplate.txt directly before running Procurement

**Comment by hekkktorr** [comment]
ok now i figured out why it didnt work.
seems that my template was somehow broken, i used another custom 
template and it worked like a charm.

thanks for the help =)

**Comment by Stickymaddness** [comment]
Great, glad it's sorted
