### ISSUE TITLE
Error Loading Items

### ISSUE THREAD

**Issue by RAGINMONKEY** [Stickymaddness/Procurement#148]
Upon opening my Procurement, I put my e-mail, password and account name but when i click the Login button, it authenticate me e-mail and the laoding characters is done. Just after theres the Done! thing and another pop-up come and says : Error getting items for  league, are you sure your league settings are correct?

Can someone help me with this problem?

**Comment by Stickymaddness** [comment]
Can you paste me the contents of your DebugInfo.log file?

**Comment by RAGINMONKEY** [comment]
[02-08-2015 16:30] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Procurement.ViewModel.StashViewModel.getAvailableItems()

**Comment by Stickymaddness** [comment]
The error is that GGG is sending back that you have no leagues, and Procurement can't go any further. 

Have you / can you try login using sessionID ?

**Comment by RAGINMONKEY** [comment]
No, i havent tried to login using sessionID and thats what ill do now.

**Comment by RAGINMONKEY** [comment]
Ok it did worked with session ID. Thanks!

**Comment by Stickymaddness** [comment]
No problem!
