### ISSUE TITLE
Error reading character data after login

### ISSUE THREAD

**Issue by chizzle** [Stickymaddness/Procurement#150]
[Error] Error reading character data for <character>, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

I'm getting this error after logging in and the app loads all the tabs in my stash.  This is a fresh install and I've never had procurement running on this machine.  I've tried logging in with my email/password and also the session ID.

**Comment by chizzle** [comment]
Why is it....immediately after opening a ticket....I figure out my issue.  The problem was with the "account name".  Sorry for wasting cycles if you read this.  Keep up the awesome work!

**Comment by Stickymaddness** [comment]
No problem!
