### ISSUE TITLE
New divination Card not counted in

### ISSUE THREAD

**Issue by Dreidor** [Stickymaddness/Procurement#154]
The new divination Card (like The Siren) are not counted in the trading tool thus are not post'd on the forum.

**Comment by Stickymaddness** [comment]
I'll get this added for the next release.

In the meantime you can manually add it in data.xml by adding an entry for it under the DivinationCard section

**Comment by Dreidor** [comment]
Thanks for the fast response :)

**Comment by Stickymaddness** [comment]
Brilliant, thanks for commenting with the list! I've updated the xml and it'll be included in the next release.
