### ISSUE TITLE
some problem with my Procurement

### ISSUE THREAD

**Issue by doyu2008** [Stickymaddness/Procurement#156]
![qq 20150807185413](https://cloud.githubusercontent.com/assets/13409863/9134349/dc0659ec-3d35-11e5-88e3-d663105a4006.jpg)
the bottom few inch of the part is missing. not sure what happen, i do reinstall it but i just cant click anything below it. any idea?

**Comment by Stickymaddness** [comment]
Under settings tick compact mode, and restart Procurement
