### ISSUE TITLE
There was an unhandled error - Sorry!

### ISSUE THREAD

**Issue by DannyBooy** [Stickymaddness/Procurement#157]
Whenever I go to a page with this fishing rod in the screen, whether its on a character or in a bank tab, procurement crashes.

https://i.gyazo.com/c323a1cc1a90a19b28521306edd352cf.png

**Comment by Stickymaddness** [comment]
This is a known issue, if you can zip and send me all your .bin files I can take a look at what's causing this (I don't have a fishing rod)

**Comment by DannyBooy** [comment]
Hey im pretty shitty with techy stuff, so I'm not sure if this is what you mean, but this is a copy and paste of all the files within  G;/Program Files/Path of Exile > Procurement > (my other email) 
Date: Sat, 8 Aug 2015 04:15:50 -0700

**Comment by Stickymaddness** [comment]
This has, finally, been fixed in [Procurement 1.24.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.2)
