### ISSUE TITLE
[Error] Error reading character data

### ISSUE THREAD

**Issue by TrueTerror** [Stickymaddness/Procurement#158]
[Error] Error reading character data for QueenOfTheTorment, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

i can't login procurement
last used version was 1.8.6.

**Comment by Stickymaddness** [comment]
Make sure you're using the latest version, 1.9.3, and that your account name is correct, it's case sensitive.
