### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by omfgwtf6699** [Stickymaddness/Procurement#162]
From debuginfo.log:
[10-08-2015 20:44] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 

   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
[10-08-2015 20:51] JSON Serialization Failed: base64 bytes:
[10-08-2015 20:51] ZmFsc2U=
[10-08-2015 20:51] END

I have version 1.9.4

**Comment by omfgwtf6699** [comment]
I also tried logging in with sessionid. i got 
[Error] The remote server returned an error: (500) Internal Server Error.

**Comment by Stickymaddness** [comment]
It looks like GGG's servers are having issues again, error 500 means the GGG servers are down.

**Comment by omfgwtf6699** [comment]
So how do I fix this problem I'm not that tech-savy.

**Comment by Stickymaddness** [comment]
Have you tried to login again?

**Comment by omfgwtf6699** [comment]
yes

**Comment by Stickymaddness** [comment]
To clarify, what error are you getting?

**Comment by Akramlold** [comment]
Same issue for me but says hardcore
[Error] Downloading stash for Hardcore, details logged to DebugInfo.log
is there a solution?

**Comment by Akramlold** [comment]
ok so here is what I have done to fix this problem " [Error] Downloading stash for Hardcore, details logged to DebugInfo.log "
very simple, just login and go into each one of your characters, in all leagues, so they refresh, then try login to Procurement.

**Comment by Stickymaddness** [comment]
@Akramlold Interesting, did you have any old race characters?

@omfgwtf6699 Try login to all your characters and see if that helps.

**Comment by fiveball** [comment]
Same issue. Fix above didnt work

**Comment by pathofboby** [comment]
Same here, tried offline, load into stash 11 and then : [Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues .

**Comment by Stickymaddness** [comment]
Somehow I lost track of this issue :frowning: 

Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

**Comment by fiveball** [comment]
No worries !
