### ISSUE TITLE
"Error getting items for league, are you sure your league settings are correct?" 

### ISSUE THREAD

**Issue by Nuqtx** [Stickymaddness/Procurement#163]
<?xml version="1.0" encoding="utf-8"?>

**Comment by Stickymaddness** [comment]
Looking at your settings file, your account name is wrong. Account name should be your username on the POE forums. Case sensitive.

**Comment by Nuqtx** [comment]
ok but now i cant open procurement i click on the icon but nothing

**Comment by Nuqtx** [comment]
is nothing i can open procurement but very slowly

**Comment by Nuqtx** [comment]
ok i change my account name i put my name on POE forums but same message. you can see my news setting : <PopularGems>
    <Gem name="Cast when Damage Taken" />
    <Gem name="Cast On Critical Strike" />
    <Gem name="Blood Magic" />
    <Gem name="Item Quantity" />
    <Gem name="Life Gain on Hit" />
    <Gem name="Life Leech" />
    <Gem name="Multistrike" />
    <Gem name="Reduced Mana" />
    <Gem name="Spell Totem" />
    <Gem name="Chain" />
    <Gem name="Faster Attacks" />
    <Gem name="Greater Multiple Projectiles" />
    <Gem name="Lesser Multiple Projectiles" />
    <Gem name="Added Chaos Damage" />
    <Gem name="Item Rarity" />
    <Gem name="Concentrated Effect" />
    <Gem name="Elemental Hit" />
    <Gem name="Elemental Proliferation" />
    <Gem name="Elemental Weakness" />
    <Gem name="Multistrike" />
    <Gem name="Temporal Chains" />
    <Gem name="Faster Casting" />
  </PopularGems>
  <UserSettings>
    <Setting name="AccountLogin" value="thomasbaltide37@gmail.com" />
    <Setting name="AccountPassword" value="K6ZKQcmvKPKZ45p13VS6HAEAAADQjJ3fARXREYx6AMBPwpfrAQAAAA7lmeyeXndDo3rSzd7dFpIAAAAAAgAAAAAAEGYAAAABAAAgAAAAfgrF4uTVUxGQBd9I2vkDWxJELI3EpXP7lH7WKJqIEPoAAAAADoAAAAACAAAgAAAAo9gGFhrTCLDjNl5+b4/VMteV7MgE7zK7sPPZs7fwfXogAAAAQ/4PabcIugpVDQQy+C5ttJ2Rmlhwxm/pW9Kf8PjvNv5AAAAAcokP+FpA7H9cTe7NUuY3eO2UopxrkWIZ0+VHbW0TNAbKnd2sVKSuJIDbYx2OtL7jdoWkSSLMnQuBHohJg5/BYg==" />
    <Setting name="AccountName" value="toto972" />
    <Setting name="UseSessionID" value="False" />
    <Setting name="FavoriteLeague" value="" />
    <Setting name="FavoriteCharacter" value="Nuqtx" />
    <Setting name="CompactMode" value="false" />
    <Setting name="MinimalMode" value="false" />
    <Setting name="DownloadOnlyMyLeagues" value="false" />
    <Setting name="DownloadOnlyMyCharacters" value="true" />
    <Setting name="CurrencyDistributionMetric" value="Chaos" />
    <Setting name="EmbedBuyouts" value="True" />
    <Setting name="BuyoutItemsOnlyVisibleInBuyoutsTag" value="False" />
    <Setting name="OnlyDisplayBuyouts" value="false" />
    <Setting name="CheckForUpdates" value="True" />
    <Setting name="PoeTradeRefreshEnabled" value="false" />
    <Setting name="PoeTradeRefreshUrl" value="" />
  </UserSettings>
  <ProxySettings>
    <Setting name="Enabled" value="False" />
    <Setting name="Username" value="" />
    <Setting name="Password" value="" />
    <Setting name="Domain" value="" />
  </ProxySettings>
  <ShopSettings>
    <Shop League="Standard" ThreadId="" ThreadTitle="Shops Happy and Fun aka SHF" />
  </ShopSettings>
  <Lists>
    <List name="MyLeagues">
      <Item value="Standard" />
    </List>
    <List name="MyTabs">
      
      
    </List>
    <List name="MyCharacters" />
    <List name="AdditionalTemplates">
      
      
    </List>
    <List name="IgnoreTabsInRecipes" />
  </Lists>
</Settings>

**Comment by Nuqtx** [comment]
now i try this <?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Settings.xsd">
  <Ratios>
    <Orb type="Mirror" OrbAmount="1" ChaosAmount="450" />
    <Orb type="Eternal" OrbAmount="1" ChaosAmount="50" />
    <Orb type="Imprint" OrbAmount="1" ChaosAmount="0" />
    <Orb type="Exalted" OrbAmount="1" ChaosAmount="20" />
    <Orb type="Divine" OrbAmount="1" ChaosAmount="8" />
    <Orb type="GemCutterPrism" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chisel" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Regal" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chaos" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Regret" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Blessed" OrbAmount="2" ChaosAmount="1" />
    <Orb type="Scouring" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Fusing" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Alchemy" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="AlchemyShard" OrbAmount="40" ChaosAmount="1" />
    <Orb type="Chance" OrbAmount="8" ChaosAmount="1" />
    <Orb type="JewelersOrb" OrbAmount="10" ChaosAmount="1" />
    <Orb type="Alteration" OrbAmount="20" ChaosAmount="1" />
    <Orb type="Chromatic" OrbAmount="20" ChaosAmount="1" />
    <Orb type="VaalOrb" OrbAmount="1" ChaosAmount="1" />    "
  </Ratios>
  <PopularGems>
    <Gem name="Cast when Damage Taken" />
    <Gem name="Cast On Critical Strike" />
    <Gem name="Blood Magic" />
    <Gem name="Item Quantity" />
    <Gem name="Life Gain on Hit" />
    <Gem name="Life Leech" />
    <Gem name="Multistrike" />
    <Gem name="Reduced Mana" />
    <Gem name="Spell Totem" />
    <Gem name="Chain" />
    <Gem name="Faster Attacks" />
    <Gem name="Greater Multiple Projectiles" />
    <Gem name="Lesser Multiple Projectiles" />
    <Gem name="Added Chaos Damage" />
    <Gem name="Item Rarity" />
    <Gem name="Concentrated Effect" />
    <Gem name="Elemental Hit" />
    <Gem name="Elemental Proliferation" />
    <Gem name="Elemental Weakness" />
    <Gem name="Multistrike" />
    <Gem name="Temporal Chains" />
    <Gem name="Faster Casting" />
  </PopularGems>
  <UserSettings>
    <Setting name="AccountLogin" value="thomasbaltide37@gmail.com" />
    <Setting name="AccountPassword" value="K6ZKQcmvKPKZ45p13VS6HAEAAADQjJ3fARXREYx6AMBPwpfrAQAAAA7lmeyeXndDo3rSzd7dFpIAAAAAAgAAAAAAEGYAAAABAAAgAAAAfgrF4uTVUxGQBd9I2vkDWxJELI3EpXP7lH7WKJqIEPoAAAAADoAAAAACAAAgAAAAo9gGFhrTCLDjNl5+b4/VMteV7MgE7zK7sPPZs7fwfXogAAAAQ/4PabcIugpVDQQy+C5ttJ2Rmlhwxm/pW9Kf8PjvNv5AAAAAcokP+FpA7H9cTe7NUuY3eO2UopxrkWIZ0+VHbW0TNAbKnd2sVKSuJIDbYx2OtL7jdoWkSSLMnQuBHohJg5/BYg==" />
    <Setting name="AccountName" value="toto972" />
    <Setting name="UseSessionID" value="False" />
    <Setting name="FavoriteLeague" value="" />
    <Setting name="FavoriteCharacter" value="Nuqtx" />
    <Setting name="CompactMode" value="false" />
    <Setting name="MinimalMode" value="false" />
    <Setting name="DownloadOnlyMyLeagues" value="true" />
    <Setting name="DownloadOnlyMyCharacters" value="true" />
    <Setting name="CurrencyDistributionMetric" value="Chaos" />
    <Setting name="EmbedBuyouts" value="True" />
    <Setting name="BuyoutItemsOnlyVisibleInBuyoutsTag" value="False" />
    <Setting name="OnlyDisplayBuyouts" value="false" />
    <Setting name="CheckForUpdates" value="True" />
    <Setting name="PoeTradeRefreshEnabled" value="false" />
    <Setting name="PoeTradeRefreshUrl" value="" />
  </UserSettings>
  <ProxySettings>
    <Setting name="Enabled" value="False" />
    <Setting name="Username" value="" />
    <Setting name="Password" value="" />
    <Setting name="Domain" value="" />
  </ProxySettings>
  <ShopSettings>
    <Shop League="Standard" ThreadId="" ThreadTitle="Shops Happy and Fun aka SHF" />
  </ShopSettings>
  <Lists>
    <List name="MyLeagues">
      <Item value="Standard" />
    </List>
    <List name="MyTabs">
      
      
    </List>
    <List name="MyCharacters" />
    <List name="AdditionalTemplates">
      
      
    </List>
    <List name="IgnoreTabsInRecipes" />
  </Lists>
</Settings>
 
and now the message is no character found

**Comment by Stickymaddness** [comment]
Make sure your account name is in the correct case, ie: TOTO972 not toto972

**Comment by Nuqtx** [comment]
i put his on the setting or in procurement screen login ?

**Comment by Nuqtx** [comment]
still character no found sorry but is the very first time i use procurement i dont know how setup correctly 
<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Settings.xsd">
  <Ratios>
    <Orb type="Mirror" OrbAmount="1" ChaosAmount="450" />
    <Orb type="Eternal" OrbAmount="1" ChaosAmount="50" />
    <Orb type="Imprint" OrbAmount="1" ChaosAmount="0" />
    <Orb type="Exalted" OrbAmount="1" ChaosAmount="20" />
    <Orb type="Divine" OrbAmount="1" ChaosAmount="8" />
    <Orb type="GemCutterPrism" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chisel" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Regal" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chaos" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Regret" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Blessed" OrbAmount="2" ChaosAmount="1" />
    <Orb type="Scouring" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Fusing" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Alchemy" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="AlchemyShard" OrbAmount="40" ChaosAmount="1" />
    <Orb type="Chance" OrbAmount="8" ChaosAmount="1" />
    <Orb type="JewelersOrb" OrbAmount="10" ChaosAmount="1" />
    <Orb type="Alteration" OrbAmount="20" ChaosAmount="1" />
    <Orb type="Chromatic" OrbAmount="20" ChaosAmount="1" />
    <Orb type="VaalOrb" OrbAmount="1" ChaosAmount="1" />    "
  </Ratios>
  <PopularGems>
    <Gem name="Cast when Damage Taken" />
    <Gem name="Cast On Critical Strike" />
    <Gem name="Blood Magic" />
    <Gem name="Item Quantity" />
    <Gem name="Life Gain on Hit" />
    <Gem name="Life Leech" />
    <Gem name="Multistrike" />
    <Gem name="Reduced Mana" />
    <Gem name="Spell Totem" />
    <Gem name="Chain" />
    <Gem name="Faster Attacks" />
    <Gem name="Greater Multiple Projectiles" />
    <Gem name="Lesser Multiple Projectiles" />
    <Gem name="Added Chaos Damage" />
    <Gem name="Item Rarity" />
    <Gem name="Concentrated Effect" />
    <Gem name="Elemental Hit" />
    <Gem name="Elemental Proliferation" />
    <Gem name="Elemental Weakness" />
    <Gem name="Multistrike" />
    <Gem name="Temporal Chains" />
    <Gem name="Faster Casting" />
  </PopularGems>
  <UserSettings>
    <Setting name="AccountLogin" value="thomasbaltide37@gmail.com" />
    <Setting name="AccountPassword" value="K6ZKQcmvKPKZ45p13VS6HAEAAADQjJ3fARXREYx6AMBPwpfrAQAAAA7lmeyeXndDo3rSzd7dFpIAAAAAAgAAAAAAEGYAAAABAAAgAAAAfgrF4uTVUxGQBd9I2vkDWxJELI3EpXP7lH7WKJqIEPoAAAAADoAAAAACAAAgAAAAo9gGFhrTCLDjNl5+b4/VMteV7MgE7zK7sPPZs7fwfXogAAAAQ/4PabcIugpVDQQy+C5ttJ2Rmlhwxm/pW9Kf8PjvNv5AAAAAcokP+FpA7H9cTe7NUuY3eO2UopxrkWIZ0+VHbW0TNAbKnd2sVKSuJIDbYx2OtL7jdoWkSSLMnQuBHohJg5/BYg==" />
    <Setting name="AccountName" value="TOTO972" />
    <Setting name="UseSessionID" value="False" />
    <Setting name="FavoriteLeague" value="" />
    <Setting name="FavoriteCharacter" value="Nuqtx" />
    <Setting name="CompactMode" value="false" />
    <Setting name="MinimalMode" value="false" />
    <Setting name="DownloadOnlyMyLeagues" value="true" />
    <Setting name="DownloadOnlyMyCharacters" value="true" />
    <Setting name="CurrencyDistributionMetric" value="Chaos" />
    <Setting name="EmbedBuyouts" value="True" />
    <Setting name="BuyoutItemsOnlyVisibleInBuyoutsTag" value="False" />
    <Setting name="OnlyDisplayBuyouts" value="false" />
    <Setting name="CheckForUpdates" value="True" />
    <Setting name="PoeTradeRefreshEnabled" value="false" />
    <Setting name="PoeTradeRefreshUrl" value="" />
  </UserSettings>
  <ProxySettings>
    <Setting name="Enabled" value="False" />
    <Setting name="Username" value="" />
    <Setting name="Password" value="" />
    <Setting name="Domain" value="" />
  </ProxySettings>
  <ShopSettings>
    <Shop League="Standard" ThreadId="" ThreadTitle="Shops Happy and Fun aka SHF" />
  </ShopSettings>
  <Lists>
    <List name="MyLeagues">
      <Item value="Standard" />
    </List>
    <List name="MyTabs">
      
      
    </List>
    <List name="MyCharacters" />
    <List name="AdditionalTemplates">
      
      
    </List>
    <List name="IgnoreTabsInRecipes" />
  </Lists>
</Settings>

**Comment by Nuqtx** [comment]
i cant see the case ie on settings files

**Comment by Stickymaddness** [comment]
Don't worry too much about the settings file. Try login using session id and your account name.

This link will explain how to get the sessionID: https://code.google.com/p/procurement/wiki/LoginWithSessionID#How_to_retrieve_the_value

**Comment by Nuqtx** [comment]
the id session is this PHPSESSID

**Comment by Nuqtx** [comment]
now the procurement program dont open

**Comment by Nuqtx** [comment]
still dont work i use this alias TOTO972 session id PHPSESSID and accounte name TOTO972

**Comment by Stickymaddness** [comment]
Follow this video on how to get sessionID properly. 

https://www.youtube.com/watch?v=o8aHmbvWxAo

**Comment by Nuqtx** [comment]
i just follow exactly the video but i see (id session icorrect) i try Alias : TOTO972 same for account name for the session ID : i paste this b7cd93368fd79dad1cdfa761b25214b6 after i try toto972 for alias and account name but nothing

**Comment by Nuqtx** [comment]
i cant open procurement application

**Comment by Nuqtx** [comment]
ok i try and its work but look this error now Error reading character data for Nuqtx, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Nuqtx** [comment]
ok is work thank you for the help

**Comment by Nuqtx** [comment]
ok i open procurement paste the coockies and session id icorrect

**Comment by Nuqtx** [comment]
its work yesterday but now no

**Comment by Nuqtx** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Settings.xsd">
  <Ratios>
    <Orb type="Mirror" OrbAmount="1" ChaosAmount="450" />
    <Orb type="Eternal" OrbAmount="1" ChaosAmount="50" />
    <Orb type="Imprint" OrbAmount="1" ChaosAmount="0" />
    <Orb type="Exalted" OrbAmount="1" ChaosAmount="20" />
    <Orb type="Divine" OrbAmount="1" ChaosAmount="8" />
    <Orb type="GemCutterPrism" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chisel" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Regal" OrbAmount="1" ChaosAmount="2" />
    <Orb type="Chaos" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Regret" OrbAmount="1" ChaosAmount="1" />
    <Orb type="Blessed" OrbAmount="2" ChaosAmount="1" />
    <Orb type="Scouring" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Fusing" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="Alchemy" OrbAmount="2.5" ChaosAmount="1" />
    <Orb type="AlchemyShard" OrbAmount="40" ChaosAmount="1" />
    <Orb type="Chance" OrbAmount="8" ChaosAmount="1" />
    <Orb type="JewelersOrb" OrbAmount="10" ChaosAmount="1" />
    <Orb type="Alteration" OrbAmount="20" ChaosAmount="1" />
    <Orb type="Chromatic" OrbAmount="20" ChaosAmount="1" />
    <Orb type="VaalOrb" OrbAmount="1" ChaosAmount="1" />    "
  </Ratios>
  <PopularGems>
    <Gem name="Cast when Damage Taken" />
    <Gem name="Cast On Critical Strike" />
    <Gem name="Blood Magic" />
    <Gem name="Item Quantity" />
    <Gem name="Life Gain on Hit" />
    <Gem name="Life Leech" />
    <Gem name="Multistrike" />
    <Gem name="Reduced Mana" />
    <Gem name="Spell Totem" />
    <Gem name="Chain" />
    <Gem name="Faster Attacks" />
    <Gem name="Greater Multiple Projectiles" />
    <Gem name="Lesser Multiple Projectiles" />
    <Gem name="Added Chaos Damage" />
    <Gem name="Item Rarity" />
    <Gem name="Concentrated Effect" />
    <Gem name="Elemental Hit" />
    <Gem name="Elemental Proliferation" />
    <Gem name="Elemental Weakness" />
    <Gem name="Multistrike" />
    <Gem name="Temporal Chains" />
    <Gem name="Faster Casting" />
  </PopularGems>
  <UserSettings>
    <Setting name="AccountLogin" value="thomasbaltide37@gmail.com" />
    <Setting name="AccountPassword" value="sPZL98kn49mhmXM7IwfaKwEAAADQjJ3fARXREYx6AMBPwpfrAQAAAA7lmeyeXndDo3rSzd7dFpIAAAAAAgAAAAAAEGYAAAABAAAgAAAAXUMztp/GB8dyVQDXQ9mHoprlD0rRMkQwJl0uErh9cNYAAAAADoAAAAACAAAgAAAAwbnYunDbrQc4aIUxUrX0UeWkxVJxnhSz4mbmsj97oKsgAAAAWHprBarzIt2PVc29fDz6kUcv7XxrgpTFzzwCZfVdMqtAAAAAab7k0jC+2Q3cSl/8462jNLzWKzDGL7o3oaatW9S01B60y/WOWp+NXV3Rc+x4fZfONZXveayfTXxRUTq1gBoJfA==" />
    <Setting name="AccountName" value="TOTO972" />
    <Setting name="UseSessionID" value="true" />
    <Setting name="FavoriteLeague" value="Standard" />
    <Setting name="FavoriteCharacter" value="Nuqtx" />
    <Setting name="CompactMode" value="True" />
    <Setting name="MinimalMode" value="false" />
    <Setting name="DownloadOnlyMyLeagues" value="True" />
    <Setting name="DownloadOnlyMyCharacters" value="true" />
    <Setting name="CurrencyDistributionMetric" value="Chaos" />
    <Setting name="EmbedBuyouts" value="True" />
    <Setting name="BuyoutItemsOnlyVisibleInBuyoutsTag" value="False" />
    <Setting name="OnlyDisplayBuyouts" value="false" />
    <Setting name="CheckForUpdates" value="True" />
    <Setting name="PoeTradeRefreshEnabled" value="True" />
    <Setting name="PoeTradeRefreshUrl" value=" http://control.poe.xyz.is/hikininonorahi " />
  </UserSettings>
  <ProxySettings>
    <Setting name="Enabled" value="False" />
    <Setting name="Username" value="" />
    <Setting name="Password" value="" />
    <Setting name="Domain" value="" />
  </ProxySettings>
  <ShopSettings>
    <Shop League="Standard" ThreadId="1390407" ThreadTitle="Welcome to the Happy To Shop (HTS) :)" />
    <Lists>
    <List name="MyLeagues">
      <Item value="Standard" />
    </List>
    <List name="MyTabs">
      
      
    </List>
    <List name="MyCharacters" />
    <List name="AdditionalTemplates">
      
      
    </List>
    <List name="IgnoreTabsInRecipes" />
  </Lists>
</Settings>

**Comment by Nuqtx** [comment]
and at this moment i cant open again procurement 1.9.4

**Comment by Nuqtx** [comment]
sry my bad i forget to login on forum
