### ISSUE TITLE
Research result doesn't show the slottted gems.

### ISSUE THREAD

**Issue by dolnenhithoel** [Stickymaddness/Procurement#165]
Hi,

I guess it's a bug and not a feature.

When doing a research the slotted gems doesn't appear in the "result".

Even when doing an "advanced reseach" with  "All gems" it doesn't show the slotted gems.

Regards.

**Comment by Stickymaddness** [comment]
I gave this a quick test, if you search for quality gems or search for a gem by name it brings up gems that are socketed in gear in the results. 

It only seems to be "All gems" that has this issue. I'll get it sorted for the next release.

**Comment by dolnenhithoel** [comment]
Hi,

It also affect the "leveled gems".

Thanks.

Regards.

**Comment by Stickymaddness** [comment]
Ok, will fix that too!

**Comment by Stickymaddness** [comment]
This has finally been fixed, and will be in Procurement 1.9.7 which will be released today.
