### ISSUE TITLE
Error getting items for league, are you sure your league settings are correct?

### ISSUE THREAD

**Issue by adam0203** [Stickymaddness/Procurement#166]
Hi, 
I saw that someone else had this problem a couple days ago but was able to fix it. I've tried a lot of things to get it to run but seeing it's my first time using the program i figure i'm missing something. Anyways i'm trying to log in via session ID because i run the game through steam. I have made sure that the account name was correctly case sensitive and have used multiple account names because i assumed that was the issue, however none of them seemed to change the error. And i do have the session ID correct. Anyway, thanks in advance!

**Comment by Stickymaddness** [comment]
Hi,

What is the account name that you're using?

**Comment by adam0203** [comment]
I tried both adam0203 which is my account on the forums and NOTsteven which is my account name through steam

**Comment by adam0203** [comment]
I figured out what the problem was. It took forever though. It had to do with an issue I had when trying to link my steam account to the POE website. Turns out that because i tried to do that, all log ins are defaulted to an account with 0 characters. Sorry to waste your time!

**Comment by Stickymaddness** [comment]
No problem, can you explain a bit more about the linking issue, so I know for future reference and can tell other users?
