### ISSUE TITLE
81 Shrine not listed in shop.

### ISSUE THREAD

**Issue by JakeStraker** [Stickymaddness/Procurement#167]
81 shrine isnt listed in my thread even when the buyout is set, any idea of issues with the new maps? I see them listed on xyz

**Comment by Stickymaddness** [comment]
The forum template is a bit out of date, and only has tags for maps up to level 78. 

If you edit the template and add tags for the missing map levels, they will be correctly exported.

**Comment by JakeStraker** [comment]
Cheers man, Ill do that
