### ISSUE TITLE
Can't Login!! 

### ISSUE THREAD

**Issue by potasium56** [Stickymaddness/Procurement#170]
I hate when a new version comes out because there is always issues!! I can't login its says my information is incorrect but i made sure i typed my information in correctly and with it being correctly i still can't login and its pissing me off.

**Comment by Stickymaddness** [comment]
Try logging in using sessionID

**Comment by potasium56** [comment]
im sorry, I don't want to use sessionID, The reason i made this thread was so someone can help me with my issue regarding login in the normal way.

**Comment by potasium56** [comment]
I was using procurement today untill i went to the new version and then everything fucked up on me, i was able to login and everything now i can't, and im not going to use SessionID because i prefer the normal method of login into procurement.

**Comment by Stickymaddness** [comment]
What is the exact error you are getting?

**Comment by potasium56** [comment]
Its says [Error] Username or password incorrect.  however im 100% the information im putting in is correct.

**Comment by potasium56** [comment]
I double checked my email and password i logged into path of exile website and the game with the information i put into procurement, but for some reason procurment says its the wrong information

**Comment by Stickymaddness** [comment]
Have you changed your email/password recently, or are you trying to login with the same email/password you've always logged in with?

**Comment by potasium56** [comment]
Well i tried login in with the same email and password i always login in with, however after like 100 times trying to get it to work, i decided to change my password and try again,  i didn't and still didn't work so i went on the path of exile game and put my information there and i logged into the game fine.

**Comment by Stickymaddness** [comment]
Ok. There are 3 possible scenarios. 

1.) Your credentials are incorrect
2.) There is something on your pc/network, firewall/proxy/antivirus/etc blocking the login
3.) GGG servers are returning invalid login even though it is correct.

Unfortunately none of these are things that I can help with. The GGG servers have been unstable the last month or two, and often sessionID is the only work around.

This is a result of GGG not supporting developers with a proper API.

**Comment by potasium56** [comment]
Like i just logged into path of exile game!!, and then i tried logging into procurement with that same information and procurement says its the wrong information and i reado about sessionid and not likeing how unsafe that way is so i might just have to wait untill you guys fix this problem or poe fuckin fixes it. 

It juts blows my mind that i was on procurement like 5 hours ago and once i upgrade to the new version i can't login anymore.
