### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by NeGerai** [Stickymaddness/Procurement#171]
Whenver I try to open my stash in Standard League or press on the Trading tab it says There was an unhandled error

On debug info says dis :
[16-08-2015 23:26] System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length

**Comment by Stickymaddness** [comment]
Hi,

Do your stashes in other leagues work?

**Comment by NeGerai** [comment]
Hey, Yeh the warbands league stash loads just fine but Standard will just cause it to crash

**Comment by Stickymaddness** [comment]
Alright, are you sure your standard stash is up to date? Ie: Login and update standard for all tabs. If you're sure it's up to date, do you have any old race characters in standard or characters from old leagues you haven't logged into for a long time?

**Comment by NeGerai** [comment]
I use Session ID to log in but it shows it loading my new stash and the character I havnt been on for the longest is in Warbands.

**Comment by NeGerai** [comment]
I just deleted my warbands character and the standard stash is working fine now but The Trading tab still causes procurement to crash ;(

**Comment by Stickymaddness** [comment]
Deleting your warbands character shouldn't have any effect, since the data is stored separately per league. 

Delete your tabprefs.xml file if you have one, restart Procurement and see if the trading view is able to load without crashing.

Are you using the latest version of Procurement (1.9.4) ?

**Comment by NeGerai** [comment]
I deleted the tabpref file and restarted but same thing happened unfortunately also yes I am using the 1.9.4 version

**Comment by Stickymaddness** [comment]
Try login to all your standard characters, this sometimes fixes the API returning invalid data for a league.
