### ISSUE TITLE
Unable to get Chardata

### ISSUE THREAD

**Issue by Smeagol001** [Stickymaddness/Procurement#172]
Authenticating xxx [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           [OK][OK]
Loading Standard Stash Tab 2...                                                           
Loading Standard Stash Tab 2...                                                           [OK][OK]
Loading Standard Stash Tab 3...                                                           
Loading Standard Stash Tab 3...                                                           [OK][OK]
Loading Standard Stash Tab 4...                                                           
Loading Standard Stash Tab 4...                                                           [OK][OK]
Loading Standard Stash Tab 5...                                                           
Loading Standard Stash Tab 5...                                                           [OK][OK]
Loading Standard Stash Tab 6...                                                           
Loading Standard Stash Tab 6...                                                           [OK][OK]
Loading Standard Stash Tab 7...                                                           
Loading Standard Stash Tab 7...                                                           [OK][OK]
Loading Standard Stash Tab 8...                                                           
Loading Standard Stash Tab 8...                                                           [OK][OK]
Loading Standard Stash Tab 9...                                                           
Loading Standard Stash Tab 9...                                                           [OK][OK]
Loading Standard Stash Tab 10...                                                          
Loading Standard Stash Tab 10...                                                          [OK][OK]
Loading Standard Stash Tab 11...                                                          
Loading Standard Stash Tab 11...                                                          [OK][OK]
Loading Standard Stash Tab 12...                                                          
Loading Standard Stash Tab 12...                                                          [OK][OK]
Loading Standard Stash Tab 13...                                                          
Loading Standard Stash Tab 13...                                                          [OK][OK]
Loading Standard Stash Tab 14...                                                          
Loading Standard Stash Tab 14...                                                          [OK][OK]
Loading Standard Stash Tab 15...                                                          
Loading Standard Stash Tab 15...                                                          [OK][OK]
Loading Standard Stash Tab 16...                                                          
Loading Standard Stash Tab 16...                                                          [OK][OK]
Loading Standard Stash Tab 17...                                                          
Loading Standard Stash Tab 17...                                                          [OK][OK]
Loading xxx inventory...                                                        

[Error] Error reading character data for xxx, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

i don't know what going wrong since i am using session id and forced it to create a new to be sure its not a issue with an old id
i am using the prog for the first time and using win10 x64

**Comment by Stickymaddness** [comment]
Most likely your account name is incorrect, note that it is case sensitive.

![accountname](https://cloud.githubusercontent.com/assets/6553902/9308585/44ac132a-4505-11e5-8707-57cbd4d31ba8.PNG)

**Comment by Smeagol001** [comment]
i doublechecked that it isnt my name tats wrong

**Comment by Stickymaddness** [comment]
Don't be, it's a common mistake !
