### ISSUE TITLE
error handling forum templates

### ISSUE THREAD

**Issue by uNBAAL** [Stickymaddness/Procurement#174]
Not sure why it crashes, but i created the first forum template on a another computer, then downloaded procurement on the second and tried to recreate the forum template here. But something doesnt seem to align properly.

[19-08-2015 2:36] System.Windows.Markup.XamlParseException: Anropet av konstruktorn av typen Procurement.Controls.ForumExport som matchar de angivna bindningsbegränsningarna utlöste ett undantag. ---> System.ArgumentOutOfRangeException: Längden får inte vara mindre än noll.
Parameternamn: length
   vid System.String.Substring(Int32 startIndex, Int32 length)
   vid Procurement.ViewModel.ForumExportVisitors.StashVisitor.getToken(Int32 location, String current)
   vid Procurement.ViewModel.ForumExportVisitors.StashVisitor.getTokenLocations(String current)
   vid Procurement.ViewModel.ForumExportVisitors.StashVisitor.Visit(IEnumerable`1 items, String current)
   vid Procurement.ViewModel.ForumExportViewModel.getFinal(IEnumerable`1 items)
   vid Procurement.ViewModel.ForumExportViewModel.updateText()
   vid Procurement.ViewModel.ForumExportViewModel..ctor()
   vid Procurement.Controls.ForumExport..ctor()
   --- Slut på stackspårning för interna undantag ---
   vid System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   vid System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   vid System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   vid System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   vid Procurement.View.TradingView..ctor()
   vid Procurement.ViewModel.ScreenController.execute(Object obj)
   vid MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   vid System.Windows.Controls.Primitives.ButtonBase.OnClick()
   vid System.Windows.Controls.Button.OnClick()
   vid System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   vid System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   vid System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   vid System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   vid System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   vid System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   vid System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   vid System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   vid System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   vid System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   vid System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   vid System.Windows.Input.InputManager.ProcessStagingArea()
   vid System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   vid System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   vid System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   vid MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by uNBAAL** [comment]
It crashes as soon as i press the trading button now :/

**Comment by Stickymaddness** [comment]
Something is broken on your forum template, I would suggest running Procurement with the default template (delete ForumExportTemplate.txt to restore it), and then updating it from there.

**Comment by uNBAAL** [comment]
wow, thank you this fixed the problem instantly!
