### ISSUE TITLE
items wont show up on poe.xyz

### ISSUE THREAD

**Issue by hekkktorr** [Stickymaddness/Procurement#175]
hello,

i dont know why my items wont show up on poe.xyz.
any help is appreciated =)

here my template:
Welcome to my shop! (Last Updated {LastUpdated}),
 
Please message me here or ingame if something catches your eye. My IGN is {IGN}.

If you don't like a price feel free to make an offer. 
Don't have the currency I'm asking for? Offer me equivalent. 
 

[spoiler="~b/o 1 chaos"]
{Stash:1c}
[/spoiler]
[spoiler="~b/o 2 chaos"]
{Stash:2c}
[/spoiler]
[spoiler="~b/o 3 chaos"]
{Stash:3c}
[/spoiler]
[spoiler="~b/o 4 chaos"]
{Stash:4c}
[/spoiler]
[spoiler="~b/o 5 chaos"]
{Stash:5c}
[/spoiler]
[spoiler="~b/o 10-20 chaos"]
{Stash:10-20c}
[/spoiler]
[spoiler="~b/o 1ex+ "]
{Stash:1ex+}
[/spoiler]
[spoiler="~b/o uniques"]
{Stash:U1}
[/spoiler]
[spoiler="~b/o uniques2"]
{Stash:U2}
[/spoiler]

 
Thanks for visiting!

**Comment by Stickymaddness** [comment]
Template looks good, you will need to speak to xyz for poe.trade issues, Procurement has no control over what items are indexed. 

Make sure you bump your thread a few times if it is new.
