### ISSUE TITLE
Lost Buyout Prices - Strange code appeared in poe.trade

### ISSUE THREAD

**Issue by damoochie** [Stickymaddness/Procurement#176]
Once again most of my buyout prices have disappeared. Odd thing is my buyout.xml file seems to have all the correct entries still. Can I fix this somehow?

**Comment by Stickymaddness** [comment]
This is a result of GGG adding invalid json to their api on a whim, be sure to voice your frustrations with them.

I will release a new version soon, in the meantime keep your old buyouts.xml file and don't change anything.

**Comment by damoochie** [comment]
Thanks for the update. Maybe I'll remind GGG how integral Procurement has become to PoE and that they should coordinate with you a bit more ;)

**Comment by Stickymaddness** [comment]
Heh, thanks. 

New version is out which fixes the issue.
