### ISSUE TITLE
Error while trying to open procurement

### ISSUE THREAD

**Issue by Respxcted** [Stickymaddness/Procurement#177]
I run the .exe file and it won't even open it just comes up with an error message saying unhandled error please create a ticket on github/stickymadness/procurement/issues. The error did not occur after procurement was done downloading, It wouldn't even open, this is with procurement version 1.9.5

**Comment by Stickymaddness** [comment]
Do you have .NET 4.5 or later installed?

**Comment by polishmatt** [comment]
I had this issue after copying my Settings.xml from 1.9.3. This was with .NET 4.5.1 RC.

**Comment by Respxcted** [comment]
I don't have .net 4.5 installed and yeah it was after I copied my settings/buyouts over

**Comment by Stickymaddness** [comment]
It's crashing because the setting file had a new setting added in 1.9.4, open your settings file and add:

     <Setting name="MinimalMode" value="false" />

right below the line with "CompactMode"

**Comment by Respxcted** [comment]
ah okay. Thanks a ton for the help it fixed it
