### ISSUE TITLE
problem logging in

### ISSUE THREAD

**Issue by kadrix250** [Stickymaddness/Procurement#180]
tried logging into client, getting this error

[Error] There was an error deserializing the object of type System.Collections.Generic.List`1[[POEApi.Model.JSONProxy.Character, POEApi.Model, Version=1.9.5.0, Culture=neutral, PublicKeyToken=null]]. Encountered unexpected character '<'.

**Comment by Stickymaddness** [comment]
Are your sure your account name is correct?

**Comment by kadrix250** [comment]
Im using the same info i log into the path of exile site with, am i supposed to do something different since im a steam user?
