### ISSUE TITLE
Failure to Load Characters, Error reading character data for xxxxx

### ISSUE THREAD

**Issue by moustaffa** [Stickymaddness/Procurement#183]
The error I am getting is "[Error] Error reading character data for Shadowstorm_Master, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again."  I try again and (usually) it will simply do this: Loading characters...                                                                     [ER]
[Error] Failed to load characters

I've included a screenshot to show what's going on.

Sometimes it will say what he is getting, and sometimes it will simply have an error of "Error: Failed to load characters". I have DEFINITELY spelled my character name right and it's not loading ANY characters, not just the one I typed in under Account Name. I haven't used Procurement since 1.8.6, but it definitely worked then.

I uninstalled and re-installed Procurement (Using version 1.9.2, as that was the newest installer on the site?) then copied and pasted the 1.9.5 version into the installer folder. PLEASE HELP!
![procurement error](https://cloud.githubusercontent.com/assets/13972085/9482460/929648ea-4b62-11e5-8254-a9cc72ab4a7d.png)

**Comment by Stickymaddness** [comment]
Take a look at https://github.com/Stickymaddness/Procurement/wiki/Error-reading-character-data-issue

**Comment by moustaffa** [comment]
This is really frustrating, but I can at least log in now by only
downloading my stash tabs and no characters.  I had scoured your FAQ before
I posted and was able to log in, but this I still can't access my
characters.  I logged into every one of them to ensure they were still
active and the account name is defnitely spelled correctly.

On Sat, Aug 29, 2015 at 12:51 PM, Stickymaddness <notifications@github.com>
wrote:

> Take a look at
> https://github.com/Stickymaddness/Procurement/wiki/Error-reading-character-data-issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stickymaddness/Procurement/issues/183#issuecomment-136009048>
> .
>



-- 
-Kyle Rogers

"Perfectionism is slow Death"
   - Hugh Prather

**Comment by Stickymaddness** [comment]
Yeah it is annoying, I don't know why GGG added account name as a requirement to download character data.

I did see that from your screenshot you are using the account name "Adrik_Daggarkin", which does not exist:

https://www.pathofexile.com/account/view-profile/Adrik_Daggarkin
