### ISSUE TITLE
cant log into procurement

### ISSUE THREAD

**Issue by 12anch** [Stickymaddness/Procurement#186]
so i downloaded the newest version of procurement.. the old version worked fine but once i downloaded the new one i cant log in anymore. all it says is... 

[Error] The remote server returned an error: (500) Internal Server Error.

please help

**Comment by Stickymaddness** [comment]
This is an error on GGG's end, like the error message says "The remote server returned an error".

If you wait a bit and try again you should be able to login.

**Comment by 12anch** [comment]
It's been like this for 3 days now. I've tried reinstalling too

**Comment by 12anch** [comment]
It's been like that for days now

**Comment by Stickymaddness** [comment]
Are you using any kind of proxy server?

**Comment by 12anch** [comment]
Nope. I even tried reinstalling the program too and tried downloaded the older version. Still not working.

**Comment by Stickymaddness** [comment]
I somehow lost track of this issue, however it should be fixed with the server upgrades GGG did. Let me know if it is still an issue.

**Comment by 12anch** [comment]
no it did not fix.. i just started pplaying again and it took me forever to find my id again using chrome search. i found it but it told me to copy it and it;ll be on my procurement app automatically but i cant select copy.. and when i try ctrl c and paste it on the app it doesnt work.. it worked the first time and this popped up...

Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

idk what that means... please help!

**Comment by 12anch** [comment]
i had the pre release version at first and now i just downloaded the latest version out. i found my id through chrome, F12, cookies, PoE and POESESSID. it wont let me copy it.. so i highlighted my arrow on it and typed it in... now its saying..

[Error] Incorrect session id

i dont get this thing... it was working fine before then out of no where there was a new version and ever since then it doenst work at all...
