### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by wodaen** [Stickymaddness/Procurement#187]
Obviously other people have been able to use this but maybe I'm missing something. I've downloaded the zip and unzipped it. I've clicked around at whatever files I could find but nothing seemed to open the program. Probably I need some other application to start it but there was nothing in the readme to tell me what to do. Please help.

**Comment by Stickymaddness** [comment]
What operating system are you using? 

Make sure you have .NET 4.5 or later installed, then just run Procurement.exe it should have a top-hat icon.

**Comment by wodaen** [comment]
Hi,
I have Windows 7 with .net 4.6There is no procurement.exe file. I see an sln and an xaml that look like something...but no exe

**Comment by Stickymaddness** [comment]
You've downloaded the source code and not the Procurement release zip.

You need to download this file:  https://github.com/Stickymaddness/Procurement/releases/download/1.9.5/Procurement.1.9.5.zip

**Comment by wodaen** [comment]
Thanks! that was indeed the problem.
