### ISSUE TITLE
How to update Procurement ?

### ISSUE THREAD

**Issue by Ghosty29** [Stickymaddness/Procurement#188]
Hello, 

sorry to ask this, but how i update procurement ?
I got the verssion 1.9.3. and i don't want to loose my configurations.
How can i update it just to the newest version, without loosing anyhting ?

Thanks for help.

**Comment by Stickymaddness** [comment]
Hi,

1. Backup your settings.xml file, buyouts.xml file and ForumExportTemplate.txt
2. Extract the 1.9.5 zip into your Procurement folder replacing everything
3. Copy the files you backed up back into your Procurement folder replacing the ones from the zip
4. Edit settings.xml, below compact mode add:

`<Setting name="MinimalMode" value="false" />`

**Comment by Ghosty29** [comment]
Thanks for answer :D
