### ISSUE TITLE
HttpWebRequest sends double user agent

### ISSUE THREAD

**Issue by wofferl** [Stickymaddness/Procurement#190]
request.UserAgent = "User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; .NET CLR 1.1.4322)";

The "User-Agent:" is already included in the request itself and thus duplicated.

Some Firewalls or Intrusion Detection Systems will block these Requests:

ET MALWARE Double User-Agent (User-Agent User-Agent) [**] [Classification: A Network Trojan was Detected]

**Comment by Stickymaddness** [comment]
Interesting, I'll take a look into this. Thanks for the info!
