### ISSUE TITLE
there was an undandled error Sorry. Create a ticked

### ISSUE THREAD

**Issue by czaja125** [Stickymaddness/Procurement#192]
After update win for 8.1 procurement show up that error info.
debug log

[06-09-2015 8:32] Application Version: Procurement 1.9.5
[06-09-2015 8:32] 
CurrentCulture: pl-PL
CurrentUICulture: pl-PL
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[06-09-2015 8:32] System.Windows.Markup.XamlParseException: Operacja podawania wartości elementu „System.Windows.Baml2006.TypeConverterMarkupExtension” wywołała wyjątek. ---> System.MissingMethodException: Nie odnaleziono metody: 'Void System.Diagnostics.Tracing.FrameworkEventSource.BeginGetResponse(System.Object, System.String)'.
   w System.Net.FileWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   w System.Net.FileWebRequest.GetResponse()
   w MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   w System.Windows.Media.ColorContext.Initialize(Uri profileUri, Boolean isStandardProfileUriNotFromUser)
   w System.Windows.Media.ColorContext..ctor(PixelFormat pixelFormat)
   w System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   w System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   w System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   w System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   w System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   w System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   w MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   w System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   w System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   w System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   w System.Windows.Application.DoStartup()
   w System.Windows.Application.<.ctor>b__1(Object unused)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Stickymaddness** [comment]
Do you have .NET 4.5 or later installed and are you sure your settings/login details are correct?
