### ISSUE TITLE
Licensing of the code ?

### ISSUE THREAD

**Issue by Gloorf** [Stickymaddness/Procurement#194]
Hi,
I've been wondering, what's the licence of procurement ? There is pratically nothing on github, google code says it's a "GPL/artistic licence". Looking at the code, there is a couple of mentions of artistic licence 2.0 (in the differents AssemblyInfo.cs files), so i'm assuming it's that (there is also some GPLv2 code in POEApi.Transport/throttle.cs, but it's compatible with artistic licence 2.0). Could you clarify a little bit in the README.md this ?

**Comment by Stickymaddness** [comment]
Hi there,

The license is [Artistic License 2.0](https://tldrlegal.com/license/artistic-license-2.0-%28artistic%29) as per the about screen. Originally when the project was hosted on google code there was a nice sidebar description that listed the license info, and hadn't thought of this for github. I'll add some info to the readme.

throttle.cs isn't my class, so I kept the original info.

Do you have a project in mind that you'd like to use the Procurement source for?

**Comment by Gloorf** [comment]
> The license is Artistic License 2.0 as per the about screen. Originally when the project was hosted on google code there was a nice sidebar description that listed the license info, and hadn't thought of this for github. I'll add some info to the readme.

Okay, thanks :)

> Do you have a project in mind that you'd like to use the Procurement source for?

Not really, was just looking at the code and were curious, i'm not a fan of Procurement (mainly becauses linux + C# don't go together very well)
