### ISSUE TITLE
Procurement crashing when mouse over Song of the Sirens

### ISSUE THREAD

**Issue by DXArcana** [Stickymaddness/Procurement#195]
So I'm totally new to this website, or to GitHub in general. I'm only following the steps the message gave me when it crashed.

Basically, Procurement loads fine, I could set up most of the things and didn't seem to have any troubles other than crashing when I mouse over a certain item, which is the Song of the Sirens I want to sell. I linked the error message, and then, it's always followed by a ''Procurement has stopped working'', etc.

Can that be looked up?

Thank you!

**Comment by DXArcana** [comment]
![song of the sirens crash](https://cloud.githubusercontent.com/assets/14348789/9961721/68968516-5df8-11e5-8fc9-953c424eb76f.png)

**Comment by Stickymaddness** [comment]
Hi there,

This is a known issue with the fishing rod, and is on the to-do list, I just haven't had time to add support for fishing rods.

**Comment by DXArcana** [comment]
Allright, thanks for letting me know then! :)

**Comment by Stickymaddness** [comment]
This has, finally, been fixed in [Procurement 1.24.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.2)
