### ISSUE TITLE
[Error] Access is denied

### ISSUE THREAD

**Issue by Energysh0ck** [Stickymaddness/Procurement#196]
Any help please?

**Comment by Energysh0ck** [comment]
.

**Comment by Stickymaddness** [comment]
Make sure you have .NET 4.5+ installed and run Procurement as administrator.

**Comment by Energysh0ck** [comment]
@Stickymaddness  i've just downloaded 4.6.. same problem

**Comment by Stickymaddness** [comment]
Did you run as administrator? Where have you extracted Procurement to?

**Comment by Energysh0ck** [comment]
@Stickymaddness  i ran as administrator, i extracted it on my ''games drive''

**Comment by Stickymaddness** [comment]
Hmm, can you paste me your DebugInfo.log here or on http://pastebin.com/ if it's really long.

**Comment by Energysh0ck** [comment]
@Stickymaddness 20-09-2015 2:40] System.Security.Cryptography.CryptographicException: Access is denied.

   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at POEApi.Infrastructure.DPAPI.Encrypt(SecureString secret)
   at Procurement.ViewModel.LoginWindowViewModel.saveSettings(SecureString password)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by Energysh0ck** [comment]
@Stickymaddness  anything mate?

**Comment by Energysh0ck** [comment]
.

**Comment by Stickymaddness** [comment]
This is an odd error you're getting. 

Make sure you have the full .NET framework installed, and not just the Client Profile.

Move Procurement to C:\Procurement, and make sure your user has full read/write access to the folder, and run Procurement as administrator.

**Comment by Energysh0ck** [comment]
@Stickymaddness im downlaoded NET yesterday,how to know if it the cilent profile or full?

**Comment by Stickymaddness** [comment]
You can download the full .NET 4.6 from here:

https://www.microsoft.com/en-us/download/details.aspx?id=48137
