### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by bleecampbell** [Stickymaddness/Procurement#200]
ive tried doing everything changing values, logging into all my characters i dnno if this was maybe from the patch?

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
