### ISSUE TITLE
Cant load tabs

### ISSUE THREAD

**Issue by Dumbledoge** [Stickymaddness/Procurement#202]
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

what to do :(

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg

**Comment by Dumbledoge** [comment]
thank you for your reply


Marc Okimura
