### ISSUE TITLE
Stash Tab Error

### ISSUE THREAD

**Issue by TheBeardo** [Stickymaddness/Procurement#203]
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Seems I am not the only one with this issue but I would like to have it resolved so I can continue to use Procurement to make my life a lot easier.

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
