### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by Darktransat** [Stickymaddness/Procurement#207]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           [OK][OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[02-10-2015 14:03] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei POEApi.Model.Map..ctor(Item item)
   bei POEApi.Model.ItemFactory.Get(Item item)
[02-10-2015 14:03] ItemFactory unable to instanciate type : Gorge Map
[02-10-2015 14:03] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Gorge Map
   bei POEApi.Model.ItemFactory.Get(Item item)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei POEApi.Model.Stash..ctor(Stash proxy)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-10-2015 14:03] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
