### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by bigroc** [Stickymaddness/Procurement#208]
] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
 this is all i know to paste ty for your awesome shop program it is worth a paypal donation

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
