### ISSUE TITLE
 [Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by ferelinstincts** [Stickymaddness/Procurement#216]
Hi,

My Procurement has been working just fine until the most recent update for PoE. Now, when I try to log into Procurement, I get the following message:

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

I have never used session ID to log in because I play the game via Steam and I have never had this issue before. Any help you can give would be much appreciated.

Thank you

**Comment by FixEd-It** [comment]
It's because of the changes to maps. I sold all my maps in Standard league, and now Procurement loads again. It will cost you all of your maps in Standard this way though. (I never play standard anymore, so I don't care :) )

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
