### ISSUE TITLE
Unable to login to account

### ISSUE THREAD

**Issue by clmaz** [Stickymaddness/Procurement#220]
Hi!

I've been using your software for a while now and it's great.
I can't seem to login to POE anymore. I used to have a Warband and Standard account.
Since the end of warband, I can't seem to login with session ID. 

I have deleted all of the "Remove Only" tabs from the account.

The following text appears when logging in:

"Authenticating Frank_Fontaine                                                             [OK]
Loading characters...                                                                       [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           [OK][OK]
Loading Standard Stash Tab 3...                                                           
Loading Standard Stash Tab 3...                                                           [OK][OK]
Loading Standard Stash Tab 4...                                                           
Loading Standard Stash Tab 4...                                                           [OK][OK]
Loading Standard Stash Tab 5...                                                           
Loading Standard Stash Tab 5...                                                           [OK][OK]
Loading Standard Stash Tab 6...                                                           
Loading Standard Stash Tab 6...                                                           [OK][OK]
Loading Standard Stash Tab 7...                                                           
Loading Standard Stash Tab 7...                                                           [OK][OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues"

Thanks!

**Comment by Stickymaddness** [comment]
Hi there, 

This was due to the recent patch which changed maps to have "tiers".

The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
