### ISSUE TITLE
Error  Downloading stash for Standard

### ISSUE THREAD

**Issue by Draven1977** [Stickymaddness/Procurement#224]
I have a problem with downloading stash in standard

Procurement 1.9.5 Initialized.
                                                           
Authenticating Draven                                                                     [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 2...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Standard Stash Tab 5...                                                           [OK]
Loading Standard Stash Tab 6...                                                           [OK]
Loading Standard Stash Tab 7...                                                           [OK]
Loading Standard Stash Tab 8...                                                           [OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log

[03-10-2015 20:32] System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij POEApi.Model.Map..ctor(Item item)
   bij POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 20:32] ItemFactory unable to instanciate type : Superior Museum Map
[03-10-2015 20:32] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Superior Museum Map
   bij POEApi.Model.ItemFactory.Get(Item item)
   bij System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij POEApi.Model.Stash..ctor(Stash proxy)
   bij POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bij POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   bij POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-10-2015 20:32] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bij POEApi.Model.POEModel.GetStash(String league, String accountName)
   bij Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bij Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bij System.Threading.Tasks.Task.Execute()

**Comment by Draven1977** [comment]
seems its a mapissue, they release a new update, tier maps

**Comment by zionarbadon** [comment]
My guess is because all of our stuff from ladder went to standard and are now in 'remove only' tabs.  Not sure what to do other than go through every dang tab and take stuff out and i dont want to do that lol

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg

**Comment by Draven1977** [comment]
Thx for your response, and all your efforts. Iam really enjoying Procurement!
 
 Regards,
Bart
 
Date: Sun, 4 Oct 2015 02:08:17 -0700
