### ISSUE TITLE
"Error"

### ISSUE THREAD

**Issue by zaustintb2** [Stickymaddness/Procurement#226]
It appears that since the patch yesterday the program will not boot completely without error. "[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues"  It has the error after completing "stash tab #4".  

Procurement 1.9.5 Initialized.
                                                           
Authenticating austintbowers@yahoo.com                                                    [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 2...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Please help...really have enjoyed using the program.

**Comment by frutality** [comment]
+1
[03-10-2015 11:14] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by zaustintb2** [comment]
I have no idea what this email means.  I don't know programming nor am I familiar with the website GitHub that I was directed to by the procurement program.  I'm so lost!  Please just tell me what to do, I can certainly follow directions.
Regards,
Austin 


     On Friday, October 2, 2015 9:15 PM, frutality <notifications@github.com> wrote:
   

 +1
[03-10-2015 11:14] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
 в POEApi.Model.POEModel.GetStash(String league, String accountName)
 в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
 в Procurement.ViewModel.LoginWindowViewModel.d__6.MoveNext()
 в System.Collections.Generic.List1..ctor(IEnumerable1 collection)
 в System.Linq.Enumerable.ToListTSource
 в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.b__1()
 в System.Threading.Tasks.Task.Execute()—

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
