### ISSUE TITLE
Can't Open

### ISSUE THREAD

**Issue by blooski** [Stickymaddness/Procurement#227]
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Log File
----------
2015/10/02 21:41:16 ***** LOG FILE OPENING *****
2015/10/02 21:41:16 25213099 14c [INFO Client 2036] Send protocol version
2015/10/02 21:41:16 25213162 1b6 [INFO Client 2036] Web root: http://patchcdn.pathofexile.com/2.0.4.2/
2015/10/02 21:41:16 25213162 1b7 [INFO Client 2036] Backup Web root: http://patch527.pathofexile.com:8095/patch/2.0.4.2/
2015/10/02 21:41:16 25213162 1c2 [INFO Client 2036] Requesting root contents 1
2015/10/02 21:41:16 25213224 1ea [INFO Client 2036] Got file list for "" 0
2015/10/02 21:41:17 25213677 222 [INFO Client 2036] Requesting folder Data 1
2015/10/02 21:41:17 25213677 222 [INFO Client 2036] Requesting folder Metadata 2
2015/10/02 21:41:17 25213801 1ea [INFO Client 2036] Got file list for "Data" 1
2015/10/02 21:41:21 25217577 230 [INFO Client 2036] Queue file to download: Data/PassiveJewelDistanceList.pjd
2015/10/02 21:41:21 25217592 1ea [INFO Client 2036] Got file list for "Metadata" 1
2015/10/02 21:41:22 25218747 222 [INFO Client 2036] Requesting folder Metadata/Terrain 2
2015/10/02 21:41:22 25218872 1ea [INFO Client 2036] Got file list for "Metadata/Terrain" 0
2015/10/02 21:41:22 25219449 222 [INFO Client 2036] Requesting folder Metadata/Terrain/Missions 1
2015/10/02 21:41:23 25219527 1ea [INFO Client 2036] Got file list for "Metadata/Terrain/Missions" 0
2015/10/02 21:41:23 25219714 222 [INFO Client 2036] Requesting folder Metadata/Terrain/Missions/Ranger 1
2015/10/02 21:41:23 25219776 1ea [INFO Client 2036] Got file list for "Metadata/Terrain/Missions/Ranger" 0
2015/10/02 21:41:23 25219870 248 [INFO Client 2036] Finished checking files
2015/10/02 21:46:21 25517707 ee [INFO Client 2036] Changing to OpenAL device "Generic Software on Speakers (Realtek High Definition Audio)"
2015/10/02 21:50:47 25784063 63b [DEBUG Client 2036] Got Instance Details from login server
2015/10/02 21:50:47 25784266 657 [INFO Client 2036] Just before calling client instance session
2015/10/02 21:50:48 25784531 b3 [INFO Client 2036] Connecting to instance server at 173.192.25.26:6112
2015/10/02 21:50:48 25784609 f3 [DEBUG Client 2036] Connect time to instance server was 63ms
2015/10/02 21:51:01 25797978 5d [INFO Client 2036] Tile hash: 750952238
2015/10/02 21:51:01 25797978 5e [INFO Client 2036] Doodad hash: 0

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
