### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tiendat243** [Stickymaddness/Procurement#230]
Procurement 1.9.5 Initialized.
                                                           
Authenticating WhiteShark                                                                 [OK]
Loading characters...                                                                     [OK]
Loading Hardcore Stash Tab 1...                                                           [OK]
Loading Hardcore Stash Tab 2...                                                           [OK]
Loading Hardcore Stash Tab 3...                                                           [OK]
Loading Hardcore Stash Tab 4...                                                           [OK]

[Error] Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
