### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by MadCaDDy** [Stickymaddness/Procurement#243]
Hello,

Procurement won't start anymore and I continue to get this message.
WHat am I doing wrong?

Regards

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
