### ISSUE TITLE
Stupid Map Error Im Pissed 

### ISSUE THREAD

**Issue by potasium56** [Stickymaddness/Procurement#252]
Is it really that big of a deal for the people who made this to go and fix it like come on!! I sick of all these errors and issues with this. Its soo annoying, And then they try and trick me to go in to session way which is risky and would rather do the email and password way. so idk Fix it!! lol

**Comment by Stickymaddness** [comment]
Your complaint is with GGG, if they proper supported 3rd party developers these kind of issues would not happen.

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg

**Comment by potasium56** [comment]
ty for the information, but when i made this complaint the new version wasn'y out yet i know you still have to wait for ggg, but was surprised that you didn't make the changes. but know that i see you did make the changes in 1.9.6 now we all just have to wait for ggg.
