### ISSUE TITLE
Download Stash for Standard Error Please help

### ISSUE THREAD

**Issue by daraluens** [Stickymaddness/Procurement#253]
[03-10-2015 21:27] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

Here my error please help:)

**Comment by kuratsak** [comment]
workaround (until bug is fixed) - it seems certain items and especially maps from warbands that were moved to standard confuse procurement.
I personally removed (to guild stash) the maps i had from warbands.
not just old style tier maps - all maps i had.
then it started up.

**Comment by Stickymaddness** [comment]
The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg
