### ISSUE TITLE
STOP OPENING issues for stash bug.

### ISSUE THREAD

**Issue by kuratsak** [Stickymaddness/Procurement#254]
I'm sure the people who can fix it will do it once they have some time for it.
meanwhile, here's a solution that worked for me:
workaround (until bug is fixed) - it seems certain items and especially maps from warbands that were moved to standard confuse procurement.
I personally removed (to guild stash) the maps i had from all tabs in my stash.
Not just old style tier maps - all maps i had.
Then it started up with no errors.

**Comment by UreKismet** [comment]
Hear hear u beat me to pointing out that 1057 'notifications' for the same problem is about 1056 too many.
Thanks to him/her/them working on this I sorta worked out what the probable cause was likely to be but as a soloer a guild stash isn't an option but not too worry I'm sure everything will be fixed.

**Comment by Stickymaddness** [comment]
RIP my inbox, new release coming soon.

**Comment by kuratsak** [comment]
I'd gladly help myself if you want it. I'm a programmer ☺

**Comment by Stickymaddness** [comment]
@kuratsak  I'll gladly accept pull requests for Procurement, a lot of great functionality has come from developers in the community! In this instance I only had time now to add a fix and do a new release.

The new version of Procurement is out, which fixes this issue: https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6

Unfortunately until GGG decide to support the dev community, these type of issues will continue to happen as it is out of our hands. http://i.imgur.com/yrPtajM.jpg

**Comment by kuratsak** [comment]
Cool,  I got a few features I'd like to add myself. Intuitive stuff 😊
I'll try to get to it when I have some time.

**Comment by kuratsak** [comment]
you work on it with VS2010?
or is there a way to compile/work without installing VS2010?

On Sun, Oct 4, 2015 at 12:20 PM, Dan Koretsky <dankoretsky@gmail.com> wrote:

> Cool,  I got a few features I'd like to add myself. Intuitive stuff 😊
> I'll try to get to it when I have some time.
> On Oct 4, 2015 11:16 AM, "Stickymaddness" <notifications@github.com>
> wrote:
>
>> @kuratsak <https://github.com/kuratsak> I'll gladly accept pull requests
>> for Procurement, a lot of great functionality has come from developers in
>> the community! In this instance I only had time now to add a fix and do a
>> new release.
>>
>> The new version of Procurement is out, which fixes this issue:
>> https://github.com/Stickymaddness/Procurement/releases/tag/1.9.6
>>
>> Unfortunately until GGG decide to support the dev community, these type
>> of issues will continue to happen as it is out of our hands.
>> http://i.imgur.com/yrPtajM.jpg
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Stickymaddness/Procurement/issues/254#issuecomment-145329583>
>> .
>>
>


-- 
Dan.
