### ISSUE TITLE
[Error] Invalid length for a Base-64 char array or string

### ISSUE THREAD

**Issue by xenovirus** [Stickymaddness/Procurement#255]
[Error] Invalid length for a Base-64 char array or string 

what can i do ?

**Comment by Stickymaddness** [comment]
It means invalid data came back when Procurement tried to login. 

Have you used Procurement before?

**Comment by SneakyYasuoMain** [comment]
I am having exactly the same issue and have not used Procurement before

**Comment by Stickymaddness** [comment]
If you have not used Procurement before, try logging in with sessionID. If that still doesn't work, contact GGG support and tell them that your account hasn't been properly associated and is not returning any data from the API.

**Comment by SneakyYasuoMain** [comment]
sessionID worked, thank you

**Comment by Stickymaddness** [comment]
@xenovirus have you been able to fix this with sessionID ?
