### ISSUE TITLE
Need help Error reading character

### ISSUE THREAD

**Issue by daraluens** [Stickymaddness/Procurement#256]
[04-10-2015 11:48] System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

Idk what causing that but i need help guys )

**Comment by Stickymaddness** [comment]
Have you used Procurement before, or are you a new user? Are you a steam user?

**Comment by armed109106** [comment]
I have same problem : im use yes dont long time before Awakening patch : but this time cant connect

**Comment by Stickymaddness** [comment]
If you're still having this issue, download Procurement 1.9.8-RC:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

However, note that GGG are currently having issues with their server currently, so you might have problems logging in, details are covered in the following issue:

#397
