### ISSUE TITLE
The item didn't update into trading template after 1.9.6

### ISSUE THREAD

**Issue by fljsdbd** [Stickymaddness/Procurement#258]
Hi, Stickymaddness. Sorry to bother you. It worked really well before this new update, right now, after clicking the tabs i want to put on form, the code with the trading template didn't autoly be generated, just have a welcome message and totally blank. how should i fix this problem? Thanks

**Comment by Stickymaddness** [comment]
Hi, 

Have you tried doing a full new install and loading up your tabs from scratch?

**Comment by fljsdbd** [comment]
yes, i tried before. but still didnt work.

**Comment by Stickymaddness** [comment]
That's weird, have you double checked your settings to make sure you don't have something like only add items with buyout etc?

If you're still stuck, zip and send me your .bin files.
