### ISSUE TITLE
NOT AN ISSUE - FEEL FREE TO CLOSE - Would like to add auto-pricing to procurement

### ISSUE THREAD

**Issue by ajamess** [Stickymaddness/Procurement#261]
Hey Sticky,

Didn't know the best way to get in touch now that GitHub has removed the PM feature...

I'd like to help add a feature to procurement: Auto Pricing based on ExileTools' elastic search item DB.  I wanted to reach out to learn a bit more about how you are storing & how to retrieve item data so I can get started.  Mind sending me a note at ajamess@gmail.com?

Later,

Adam.

**Comment by Stickymaddness** [comment]
I've dropped you an email!
