### ISSUE TITLE
Error loading stash tabs

### ISSUE THREAD

**Issue by Sn4kehead** [Stickymaddness/Procurement#265]
Hi there, this is my debuginfo.log, file was not supported as an attachment.

http://pastebin.com/NHE5Wbff

As some additional info, my stash is on Standard and when I initialized Procurement it said 9 of them loaded just fine. Please help :)

**Comment by Stickymaddness** [comment]
Hi,

Have you tried running Procurement 1.9.6? It has a fix for the error in your debug log.

**Comment by Sn4kehead** [comment]
Thanks for the suggestion, will update it now and get back to you.

**Comment by Sn4kehead** [comment]
Yep, it works now, thanks again!!

**Comment by Stickymaddness** [comment]
No problem!
