### ISSUE TITLE
Error: Procurement crashes 

### ISSUE THREAD

**Issue by Frane123** [Stickymaddness/Procurement#271]
Hello

After I start procurement all goes fine until I go the trading button.
Then after a few seconds it says:
There was an unhandled error.
And then procurement just shuts down.

Hope you can help me

**Comment by Stickymaddness** [comment]
Are you still having this issue? 

If so, delete your DebugInfo.log, click the trading button which causes it to crash, and paste the contents of the newly created DebugInfo.log file.
