### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by armed109106** [Stickymaddness/Procurement#275]
Error reading character data for Spresli, if you are in offline mode you will need to login and update. Make sure that your account name is entered correctly and with the correct casing. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
![error](https://cloud.githubusercontent.com/assets/15844010/11162615/c15fb2ce-8ac3-11e5-8d74-4792df52ee7c.jpg)
Im play poe 3 year and before patch Awakening im use don't long time Procurement
please help me for fix this problem ! 

ty

**Comment by Stickymaddness** [comment]
The character that it can't load, have you tried logging into that character?

**Comment by armed109106** [comment]
yes

**Comment by Stickymaddness** [comment]
First up download Procurement 1.9.8-RC, this is a preview release which I haven't fully released yet but does fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Secondly, note that GGG are having issues with their server currently, so you might have problems logging in, details are covered in the following issue:

#397
