### ISSUE TITLE
Error. Procurement Crashes

### ISSUE THREAD

**Issue by xSirk** [Stickymaddness/Procurement#282]
Hi, I just upgraded my Windows 8 to Windows 8.1 and now my Procurement is crashing, it was working fine before the upgrade.

Here is my DebugInfo file.
Edit: I changed it from .log to .txt just for attaching purpouse.
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/54883/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Updating to .NET Framework 4.6 should fix this issue.

**Comment by xSirk** [comment]
Ty, that error is fixed, now I have this one :(
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/60706/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Ah bad timing, GGG changed the API which caused that error.

Luckily I've just released 1.9.7 which fixes it, so you should be good to go.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7

**Comment by xSirk** [comment]
Everything is fine now, tyvm.
