### ISSUE TITLE
Error downloading stash

### ISSUE THREAD

**Issue by FEFalk** [Stickymaddness/Procurement#289]
[13-12-2015 23:59] Error downloading stash for Standard, exception details: System.Net.WebException: Fjärrservern returnerade ett fel: (500) Internt serverfel.
   vid System.Net.HttpWebRequest.GetResponse()
   vid POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   vid POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   vid POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   vid POEApi.Model.POEModel.GetStash(String league, String accountName)
[13-12-2015 23:59] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   vid POEApi.Model.POEModel.GetStash(String league, String accountName)
   vid Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   vid Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   vid System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   vid System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   vid Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   vid System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
GGG have changed the API, I'll release a fix as soon as possible.

**Comment by Stickymaddness** [comment]
Please see https://github.com/Stickymaddness/Procurement/issues/284 for updates

**Comment by FEFalk** [comment]
Ah okay, thanks!
