### ISSUE TITLE
System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by beyondgodlike** [Stickymaddness/Procurement#303]
[14-12-2015 3:44] Error downloading stash for Hardcore, exception details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 3:44] System.Exception: Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
