### ISSUE TITLE
Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket 

### ISSUE THREAD

**Issue by dontchodeme** [Stickymaddness/Procurement#305]

**Comment by corryboy85** [comment]
keeps crashing hear I need pro to work so I can sell stuff

**Comment by corryboy85** [comment]
Downloading stash for Hardcore, details logged to DebugInfo.log,

**Comment by aitee** [comment]
A pull request has been started to resolve this issue.
[https://github.com/Stickymaddness/Procurement/pull/315]

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
