### ISSUE TITLE
Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at

### ISSUE THREAD

**Issue by finalkenpachi** [Stickymaddness/Procurement#308]
[14-12-2015 8:25] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   konum: POEApi.Model.POEModel.GetStash(String league, String accountName)
   konum: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   konum: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   konum: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   konum: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()
[14-12-2015 8:27] System.Net.WebException: İşlem zaman aşımına uğradı
   konum: System.Net.HttpWebRequest.GetResponse()
   konum: POEApi.Transport.HttpTransport.GetCharacters()
   konum: POEApi.Transport.CachedTransport.GetCharacters()
   konum: POEApi.Model.POEModel.GetCharacters()
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
[14-12-2015 8:27] System.Exception: Failed to load characters
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()
[14-12-2015 8:38] Error downloading stash for Standard, exception details: System.Net.WebException: Uzak sunucu hata döndürdü: (500) İç Sunucu Hatası.
   konum: System.Net.HttpWebRequest.GetResponse()
   konum: POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   konum: POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   konum: POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   konum: POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 8:38] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   konum: POEApi.Model.POEModel.GetStash(String league, String accountName)
   konum: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   konum: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   konum: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   konum: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()
[14-12-2015 8:41] System.Runtime.Serialization.SerializationException: 'Element' durumu bekleniyor.. Karşılaşılan: 'Text' adı: '', ad alanı: ''. 
   konum: ReadArrayOfRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   konum: System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   konum: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   konum: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   konum: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   konum: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   konum: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   konum: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   konum: POEApi.Model.POEModel.GetCharacters()
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()
[14-12-2015 8:43] Error downloading stash for Standard, exception details: System.Net.WebException: Uzak sunucu hata döndürdü: (500) İç Sunucu Hatası.
   konum: System.Net.HttpWebRequest.GetResponse()
   konum: POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   konum: POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   konum: POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   konum: POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 8:43] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   konum: POEApi.Model.POEModel.GetStash(String league, String accountName)
   konum: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   konum: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   konum: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   konum: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
