### ISSUE TITLE
Downloading Stash Tab for Talisman

### ISSUE THREAD

**Issue by TheBrainbug** [Stickymaddness/Procurement#309]
Please look at the debuglogg below

[14-12-2015 8:06] Error downloading stash for Talisman, exception details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 8:06] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[14-12-2015 8:09] Error downloading stash for Talisman, exception details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (500) Interner Serverfehler.
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 8:09] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7

**Comment by TheBrainbug** [comment]
I still have the same problem

**Comment by Stickymaddness** [comment]
Please delete your debuglog if you have one, attempt to login and paste the contents so I can see the new log.

**Comment by TheBrainbug** [comment]
[14-12-2015 12:54] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   bei POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   bei POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[14-12-2015 12:54] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei ReadArrayOfRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   bei System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetCharacters()
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[14-12-2015 12:55] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei ReadArrayOfRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   bei System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetCharacters()
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[14-12-2015 12:57] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[14-12-2015 12:57] JSON Serialization Failed: base64 bytes:
[14-12-2015 12:57] ZmFsc2U=
[14-12-2015 12:57] END
[14-12-2015 12:57] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 12:57] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Top of the log: Incorrect session id

**Comment by TheBrainbug** [comment]
yes i changed that i forgot 1 number still does not work the bottom part with 12:57

**Comment by TheBrainbug** [comment]
is there a problem with an item in my tab 1?

Procurement 1.9.7 Initialized.
                                                           
Authenticating Brainbug                                                                   [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues


bug log:


[14-12-2015 13:02] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[14-12-2015 13:02] JSON Serialization Failed: base64 bytes:
[14-12-2015 13:02] ZmFsc2U=
[14-12-2015 13:02] END
[14-12-2015 13:02] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 13:02] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
No, I think that it's the GGG server that's acting up. It's the same issue as issue #321.

Basically the server is sending back empty data so Procurement can't continue

**Comment by TheBrainbug** [comment]
ok thanks

**Comment by Stickymaddness** [comment]
It's pretty annoying, you could also try contact GGG about it. Unfortunately there's nothing I can do about their API sending back null data.

**Comment by Stickymaddness** [comment]
Please try logging out of the forum, logging back in and then trying to login with the new sessionID, some users have reported that this fixed the issue.

**Comment by Stickymaddness** [comment]
Please take a look at the following wiki article which covers this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
