### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by luxiaczek** [Stickymaddness/Procurement#310]
[14-12-2015 8:23] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   w System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
