### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by n0m0rebl00d** [Stickymaddness/Procurement#313]
Error] Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/60954/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
