### ISSUE TITLE
Error while loading.

### ISSUE THREAD

**Issue by nayerre** [Stickymaddness/Procurement#314]
Procurement 1.9.6 Initialized.
                                                           
Authenticating ****************                                                     [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/60967/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
