### ISSUE TITLE
[Error] Downloading stash for Talisman

### ISSUE THREAD

**Issue by greenlupo** [Stickymaddness/Procurement#317]
Procurement 1.9.6 Initialized.
                                                           
Authenticating green.llh.89@gmail.com                                                     [OK]
Loading characters...                                                                     [OK]
Loading Talisman Stash Tab 1...                                                           

[Error] Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
Procurement 1.9.7 has been released, please retest and open a new issue if you still have a problem.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.7
