### ISSUE TITLE
New Version, same error: [Error] Downloading stash for Talisman

### ISSUE THREAD

**Issue by Sloxus** [Stickymaddness/Procurement#321]
[14-12-2015 11:30] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei

**Comment by Stickymaddness** [comment]
Ok, this issue is separate to the issue 1.9.7 fixed. 

The error is that you're getting back empty data from GGG. Are you a new user or have you used Procurement before? Have you tried logging in with sessionID ?

**Comment by Sloxus** [comment]
I have used Procurement many times before without problems and yesterday everything was working fine in the TL. And i don´t know in the moment how to login with a session id, but i will look how this works.

**Comment by Stickymaddness** [comment]
That's strange that everything was fine and you suddenly got the error. The GGG api has been very unstable lately.

I assume you've tried logging in with a fresh 1.9.7 installation and default settings? Otherwise test sessionID and let me know.

**Comment by Sloxus** [comment]
Hm, i have changend nothing, but now it works again. I don´t know what happened. Anyway thx for your help and your effort and this great program :)

**Comment by Stickymaddness** [comment]
It's the GGG server acting up. The error you pasted is basically Procurement saying "I got nothing back from the GGG server, what do?" 

When you tried it again the server sent back data, so Procurement could continue to load.

Glad it's sorted!
