### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by freemanlav** [Stickymaddness/Procurement#324]
[14-12-2015 19:34] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by freemanlav** [comment]
[14-12-2015 20:00] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 20:00] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Have you used Procurement before? Are you logging in with sessionID?

**Comment by freemanlav** [comment]
Before yes,and after 2.1.0 procurement have work,but yesterday this fault.Session ID also this fault

**Comment by Stickymaddness** [comment]
Are you still having this issue? Have you entered your account name correctly?

**Comment by freemanlav** [comment]
ofc,no problem fefore.using procurement long time.

**Comment by freemanlav** [comment]
[15-12-2015 13:16] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-12-2015 13:16] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The error is that you're getting back blank data from GGG, which is a bit tricky to track down why. If you login to the forum, can you see your stash? Do you have any old characters you haven't logged into in a long time?

**Comment by Stickymaddness** [comment]
Please take a look at the following wiki article which covers this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
