### ISSUE TITLE
Error downloading stash for Talisman

### ISSUE THREAD

**Issue by pkulas** [Stickymaddness/Procurement#325]
> [14-12-2015 17:59]
> System.Runtime.Serialization.SerializationException: Expecting state
> 'Element'.. Encountered 'Text'  with name '', namespace ''.     at
> System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator
> xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)    at
> System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator
> xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex,
> ExtensionDataObject extensionData)    at
> ReadRootObjectFromJson(XmlReaderDelegator ,
> XmlObjectSerializerReadContextComplexJson , XmlDictionaryString ,
> XmlDictionaryString[] )    at
> System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator
> jsonReader, XmlObjectSerializerReadContextComplexJson context)    at
> System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator
> jsonReader, XmlObjectSerializerReadContextComplexJson context)    at
> System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator
> reader, String name, String ns, Type declaredType, DataContract&
> dataContract)    at
> System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator
> xmlReader, Type declaredType, DataContract dataContract, String name,
> String ns)    at
> System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator
> xmlReader, Boolean verifyObjectName)    at
> System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator
> reader, Boolean verifyObjectName, DataContractResolver
> dataContractResolver)    at
> System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader
> reader)    at POEApi.Model.POEModel.GetStash(Int32 index, String
> league, String accountName, Boolean forceRefresh) [14-12-2015 17:59]
> JSON Serialization Failed: base64 bytes: [14-12-2015 17:59] ZmFsc2U=
> [14-12-2015 17:59] END [14-12-2015 17:59] Error downloading stash for
> Talisman, exception details: System.Exception: Downloading stash,
> details logged to DebugInfo.log, please open a ticket at
> https://github.com/Stickymaddness/Procurement/issues    at
> POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix) 
> at POEApi.Model.POEModel.GetStash(Int32 index, String league, String
> accountName, Boolean forceRefresh)    at
> POEApi.Model.POEModel.GetStash(String league, String accountName)
> [14-12-2015 17:59] System.Exception: Downloading stash for Talisman,
> details logged to DebugInfo.log, please open a ticket at
> https://github.com/Stickymaddness/Procurement/issues    at
> POEApi.Model.POEModel.GetStash(String league, String accountName)   
> at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character
> character)    at
> Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext() 
> at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)  
> at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)    at
> Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
> at System.Threading.Tasks.Task.Execute()

Same problem since yesterday.

**Comment by Stickymaddness** [comment]
Can you give me some more details on your Procurement usage. Are you a new user? Are you logging in with sessionID?

**Comment by Stickymaddness** [comment]
Please take a look at the following wiki article which covers this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
