### ISSUE TITLE
Error loading stash for Talisman

### ISSUE THREAD

**Issue by endysek** [Stickymaddness/Procurement#328]
Hi, 

sorry Im totally lost, so if anybody can help me to correct this it would be great.

Thanks

[14-12-2015 20:43] System.Runtime.Serialization.SerializationException: OÄŤekĂˇvĂˇ se stav Element.. Nalezeno Text s nĂˇzvem , obor nĂˇzvĹŻ . 
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   v System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   v ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   v System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   v System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[14-12-2015 20:43] JSON Serialization Failed: base64 bytes:
[14-12-2015 20:43] ZmFsc2U=
[14-12-2015 20:43] END
[14-12-2015 20:43] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
[14-12-2015 20:43] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
   v Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   v Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   v System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   v System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   v Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   v System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
The error is that the GGG API is returning "false" instead of the data for your stash, tracking down why it's doing this is going to be a bit tricky.

Can you give me some more info on your Procurement usage, have you used Procurement before? Are you logging in with sessionID, etc.

**Comment by Aza211** [comment]
Hi there,
I'm having a similar issue, first time using Procurement and logging in with sessionID gives me a separate error message upon authenticating: [Error] The remote server returned an error: (500) Internal Server Error.

**Comment by endysek** [comment]
Hi, thanks for the attention!

Yes I have used procurement 1.9.5 and 1.9.6. The 1.9.6. was running OK, till like the upgrade yesterday, and even before I did download the 1.9.7. version it stopped working. The message in older version is the same, have a look at the debug log if it helps.

Thanks again!


[15-12-2015 6:33] System.Runtime.Serialization.SerializationException: Očekává se stav Element.. Nalezeno Text s názvem , obor názvů . 
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   v System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   v ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   v System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   v System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
[15-12-2015 6:33] JSON Serialization Failed: base64 bytes:
[15-12-2015 6:33] ZmFsc2U=
[15-12-2015 6:33] END
[15-12-2015 6:33] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-12-2015 6:33] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
   v Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   v Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   v System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   v System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   v Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   v System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
@endysek 1.9.7 fixed the "Error 500" Error due to GGG changing their API, so you have to use 1.9.7 or you will get that error. 

The error you now have is the API is returning "false" instead of your items. Take a look at my reply to issue #333

@Aza211 install Procurement 1.9.7

**Comment by Stickymaddness** [comment]
@endysek 

Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
