### ISSUE TITLE
Error loading stash for  talisman league 

### ISSUE THREAD

**Issue by Tracteur** [Stickymaddness/Procurement#335]
Hi, procurement refuse log due to this exception, i'm quite new to this so i might do something wrong.

[15-12-2015 20:09] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[15-12-2015 20:09] JSON Serialization Failed: base64 bytes:
[15-12-2015 20:09] ZmFsc2U=
[15-12-2015 20:09] END
[15-12-2015 20:09] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-12-2015 20:09] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please take a look at the following wiki article which covers this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
