### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by zepti** [Stickymaddness/Procurement#342]
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/63816/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
Please take a look at the following wiki article which covers this issue:

https://github.com/Stickymaddness/Procurement/wiki/Expecting-state-'Element'-error

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
