### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by marduk87** [Stickymaddness/Procurement#345]
[17-12-2015 17:13] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:13] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:13] ZmFsc2U=
[17-12-2015 17:13] END
[17-12-2015 17:13] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:13] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:16] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:16] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:16] ZmFsc2U=
[17-12-2015 17:16] END
[17-12-2015 17:16] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:16] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:41] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:41] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:41] ZmFsc2U=
[17-12-2015 17:41] END
[17-12-2015 17:41] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:41] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:45] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:45] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:45] ZmFsc2U=
[17-12-2015 17:45] END
[17-12-2015 17:45] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:45] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:46] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:46] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:46] ZmFsc2U=
[17-12-2015 17:46] END
[17-12-2015 17:46] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:46] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:49] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   a következő helyen: POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   a következő helyen: POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:49] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:49] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:49] ZmFsc2U=
[17-12-2015 17:49] END
[17-12-2015 17:49] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:49] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()
[17-12-2015 17:52] System.Runtime.Serialization.SerializationException: A program a(z) Element állapotot várja.. A program a(z) Text elemet észlelte (név: , névtér: ). 
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   a következő helyen: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   a következő helyen: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   a következő helyen: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   a következő helyen: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   a következő helyen: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[17-12-2015 17:52] JSON Serialization Failed: base64 bytes:
[17-12-2015 17:52] ZmFsc2U=
[17-12-2015 17:52] END
[17-12-2015 17:52] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   a következő helyen: POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
[17-12-2015 17:52] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   a következő helyen: POEApi.Model.POEModel.GetStash(String league, String accountName)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   a következő helyen: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   a következő helyen: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   a következő helyen: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   a következő helyen: System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
