### ISSUE TITLE
[Error] Downloading stash for Hardcore

### ISSUE THREAD

**Issue by smelcami** [Stickymaddness/Procurement#346]
I'm having trouble starting the program, I need help?

**Comment by Stickymaddness** [comment]
Can you be more specific?

**Comment by smelcami** [comment]
Opening the procurement wrong, [Error] it appears Downloading stash for Hardcore. Which will not let me use the program.

**Comment by Stickymaddness** [comment]
Please paste the contents of your debuglog file.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
