### ISSUE TITLE
Procurement "Method not found"

### ISSUE THREAD

**Issue by apthyprjkt** [Stickymaddness/Procurement#354]
[Error] Method not found: 'System.String POEApi.Model.POEModel.GetAccountName()'.

I'm a steam user and this is the message I get when I try to log in using my session ID.

**Comment by Stickymaddness** [comment]
It sounds like your Procurement installation did not extract properly. Download a new copy of 1.9.8-RC1 and extract all the files into a new folder to test.

**Comment by apthyprjkt** [comment]
Got it! thanks a lot.

**Comment by Stickymaddness** [comment]
No problem!
