### ISSUE TITLE
Error when Bumping thread

### ISSUE THREAD

**Issue by Xebtria** [Stickymaddness/Procurement#355]
Error bumping shop thread: System.Net.WebException: Timeout für Vorgang überschritten
       bei System.Net.HttpWebRequest.GetResponse()
       bei POEApi.Transport.HttpTransport.downloadPageData(String url)
       bei POEApi.Transport.HttpTransport.validateAndGetHash(String url, String threadTitle, String hashRegex)
       bei POEApi.Transport.HttpTransport.BumpThread(String threadID, String threadTitle)

hope you don't mind the few german words as I have a german windows I guess.
but prior to talisman league it worked....

**Comment by Stickymaddness** [comment]
Timeouts are a connection related issue, either on your end or GGG's, so there's not much I can do about it unfortunately.

**Comment by Xebtria** [comment]
I get considerable less of these when I downgraded from the 1.9.8c to 1.9.7. maybe my feelings trick me with this, but that is how it feels. :/

**Comment by Stickymaddness** [comment]
I think it's just confirmation bias, the code to bump threads has not changed in a long time.

I do know that it isn't very reliable, and I'm looking for a better way to do this.
