### ISSUE TITLE
Procurement does not list any items with a buyout

### ISSUE THREAD

**Issue by Danimoth** [Stickymaddness/Procurement#36]
For the last few days (and after Rampage league ended, maybe this is related), procurement does not list any item that has a buyout. It will show everything else that doesn't have a buyout though.

I tried uninstalling-reinstalling procurement a couple of times, and setting up everything from scratch. It works at first, but after an update in the items (like adding or removing an item) the same situation occurs. Anything I can test to fix this?

**Comment by Stickymaddness** [comment]
I haven't been able to replicate this issue, what are your exact trade settings, and are you using a modified or default forum template?

**Comment by AlmightyZing** [comment]
This issue was only happening during the 1 week Beyond/Rampage league. I
have not had any issues during the Torment league.

**Comment by Stickymaddness** [comment]
Alright, I'm going to close the ticket then, log a new one if it happens again, and be sure to specify template and trade setting details.
