### ISSUE TITLE
Error Downloading Stash for STandard

### ISSUE THREAD

**Issue by kreskowka13** [Stickymaddness/Procurement#361]
Authenticating                                                    [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at

**Comment by Stickymaddness** [comment]
I need your DebugInfo.log in order to help
