### ISSUE TITLE
[Error] Downloading stash for Talisman, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by Martzz1988** [Stickymaddness/Procurement#363]
Authenticating Martzz1988                                                                 [OK]
Loading characters...                                                                     [OK]
Loading Talisman Stash Tab 1...                                                           
Loading Talisman Stash Tab 1...                                                           
Loading Talisman Stash Tab 1...                                                           

[Error] Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

[27-12-2015 4:05] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:10] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User Martzz.g@gmail.com
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:18] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:18] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:18] ZmFsc2U=
[27-12-2015 4:18] END
[27-12-2015 4:18] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:18] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:20] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.GetCharacters()
   à POEApi.Transport.CachedTransport.GetCharacters()
   à POEApi.Model.POEModel.GetCharacters()
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
[27-12-2015 4:20] System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:21] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:21] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:21] ZmFsc2U=
[27-12-2015 4:21] END
[27-12-2015 4:21] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:21] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:23] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.GetCharacters()
   à POEApi.Transport.CachedTransport.GetCharacters()
   à POEApi.Model.POEModel.GetCharacters()
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
[27-12-2015 4:23] System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:25] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:27] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:28] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:28] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:28] ZmFsc2U=
[27-12-2015 4:28] END
[27-12-2015 4:28] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:28] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:31] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.GetCharacters()
   à POEApi.Transport.CachedTransport.GetCharacters()
   à POEApi.Model.POEModel.GetCharacters()
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
[27-12-2015 4:31] System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:33] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:36] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:36] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:36] ZmFsc2U=
[27-12-2015 4:36] END
[27-12-2015 4:36] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:36] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:38] System.FormatException: L'entrée n'est pas une chaîne Base 64 valide, car elle contient un caractère non-Base 64, plus de deux caractères de remplissage ou un caractère non conforme parmi les caractères de remplissage. 
   à System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   à System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   à System.Convert.FromBase64String(String s)
   à POEApi.Infrastructure.DPAPI.Decrypt(String cipher)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:39] System.Security.Cryptography.CryptographicException: Paramètre incorrect.

   à System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   à POEApi.Infrastructure.DPAPI.Decrypt(String cipher)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:39] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:39] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:39] ZmFsc2U=
[27-12-2015 4:39] END
[27-12-2015 4:39] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:39] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:41] System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.GetCharacters()
   à POEApi.Transport.CachedTransport.GetCharacters()
   à POEApi.Model.POEModel.GetCharacters()
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
[27-12-2015 4:41] System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:42] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:42] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   à POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   à POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()
[27-12-2015 4:44] System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-12-2015 4:44] JSON Serialization Failed: base64 bytes:
[27-12-2015 4:44] ZmFsc2U=
[27-12-2015 4:44] END
[27-12-2015 4:44] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-12-2015 4:44] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   à POEApi.Model.POEModel.GetStash(String league, String accountName)
   à Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 has been released:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Please retest with this version, if you are using sessionID first log out of the forum, clear your cookies and then log back in using the POESESSID cookie to get your sessionID.
