### ISSUE TITLE
same issue as other getting error on data download in standard & talisman

### ISSUE THREAD

**Issue by UreKismet** [Stickymaddness/Procurement#367]
I don't mean to hassle you as I am sure u are well aware of the errors listed here.
I just felt I should say this problem (procurement unable to get more than  150 or so pages) has been around for me for several weeks.
I put it down to having too many tabs (327 last time I checked) which it may be for everyone since those who have opened a talisman game will now have double the pages even though 90% of the talisman tabs are prolly empty.
On reflection I must have 650+ tabs by now and for whatever reason my machine must be struggling to keep up when I try to run procurement.  I won't bore you with my machine stats other than to say they shouldn't struggle with this at all.

Anyway thanks for a great app and maybe sometime it will work for me again.

**Comment by Stickymaddness** [comment]
GGG are having load issues on their API for the last couple of weeks which would explain your issue. It has got worse in the past two days, and even people with a small amount of tabs are unable to login.

I have alerted GGG about the issue so that they can look into it.
