### ISSUE TITLE
[Error] Loding Stash Tabs for Talisman (Or any other League)

### ISSUE THREAD

**Issue by xSephirax** [Stickymaddness/Procurement#372]
This was done with 1.9.8-RC1

[01-01-2016 21:37] Error downloading stash for Talisman, exception details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (502) Ungültiges Gateway.
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 21:37] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
