### ISSUE TITLE
Crashed when loading stash

### ISSUE THREAD

**Issue by xlkong** [Stickymaddness/Procurement#373]
[22-12-2015 9:02] POEApi.Infrastructure.LogonFailedException: Username or password incorrect. User seuxlkong@gmail.com
   在 POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   在 POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   在 Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   在 System.Threading.Tasks.Task.Execute()
[01-01-2016 12:04] Error downloading stash for Talisman, exception details: System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.HttpWebRequest.GetResponse()
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   在 POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   在 POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 12:04] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
   在 Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   在 Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   在 System.Threading.Tasks.Task.Execute()
[01-01-2016 13:02] Error downloading stash for Talisman, exception details: System.Net.WebException: 操作超时
   在 System.Net.HttpWebRequest.GetResponse()
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   在 POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   在 POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 13:02] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
   在 Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   在 Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   在 System.Threading.Tasks.Task.Execute()
[01-01-2016 14:45] Error downloading stash for Talisman, exception details: System.Net.WebException: 远程服务器返回错误: (502) 错误的网关。
   在 System.Net.HttpWebRequest.GetResponse()
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   在 POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   在 POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   在 POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
[01-01-2016 14:45] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   在 POEApi.Model.POEModel.GetStash(String league, String accountName)
   在 Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   在 Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   在 System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
