### ISSUE TITLE
Stash issues

### ISSUE THREAD

**Issue by Mischek** [Stickymaddness/Procurement#374]
[01-01-2016 21:11] Error downloading stash for Hardcore Talisman, exception details: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (504) Gatewaytimeout.
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
