### ISSUE TITLE
Error Login w/ SessionID

### ISSUE THREAD

**Issue by kjy112** [Stickymaddness/Procurement#378]
[01-01-2016 15:31] System.Runtime.Serialization.SerializationException: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. 

Now this error has not yet occurred again. Issue with loading stash tab similar to others within the past hours. 1-1-2016

**Comment by Stickymaddness** [comment]
First up download Procurement 1.9.8-RC, this is a preview release which I haven't fully released yet but does fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Secondly, note that GGG are having issues with their server currently, so you might have problems logging in, details are covered in the following issue:

https://github.com/Stickymaddness/Procurement/issues/397
