### ISSUE TITLE
Thread doesn't update.

### ISSUE THREAD

**Issue by whrsmycoffee** [Stickymaddness/Procurement#384]
I've had this problem before, it's really two problems:

1) when I click "Update Forum Thread" it only sometimes actually does that. I get the "Thread succesfully updated!" but when I go there to actually check in the forum thread, the post says "Updated last time.." before I tried to update it last time. So it didn't update.

2) When I try to set an individual buyout in a tab that doesn't have a tab buyout, the buyout sometimes doesn't register. Or very often actually. The item is posted without a buyout, but when looking at it in procurement, it has a buyout. 

I have the latest version of procurement but I've had this issue in other versions as well. 

Appreciate any help.

**Comment by Stickymaddness** [comment]
I'll look into these issues for the next release, I'll see what I can do to try improve the updating.

Have you tried ticking and unticking a tab in the trade view after making changes?
