### ISSUE TITLE
Stash load error.

### ISSUE THREAD

**Issue by Vihulainen** [Stickymaddness/Procurement#389]
[02-01-2016 20:58] Error downloading stash for Hardcore Talisman, exception details: System.Net.WebException: Toiminto aikakatkaistiin
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 20:58] System.Exception: Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()
[02-01-2016 21:12] Error downloading stash for Hardcore Talisman, exception details: System.Net.WebException: Etäpalvelin palautti virheen: (502) Virheellinen yhdyskäytävä.
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 21:12] System.Exception: Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()
[02-01-2016 21:51] Error downloading stash for Hardcore Talisman, exception details: System.Net.WebException: Toiminto aikakatkaistiin
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 21:51] System.Exception: Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()
[02-01-2016 21:54] Error downloading stash for Hardcore Talisman, exception details: System.Net.WebException: Toiminto aikakatkaistiin
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 21:54] System.Exception: Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()
[02-01-2016 22:07] Error downloading stash for Standard, exception details: System.Net.WebException: Toiminto aikakatkaistiin
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 22:07] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()
[02-01-2016 22:13] Error downloading stash for Standard, exception details: System.Net.WebException: Etäpalvelin palautti virheen: (502) Virheellinen yhdyskäytävä.
   kohteessa System.Net.HttpWebRequest.GetResponse()
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   kohteessa POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-01-2016 22:13] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
As there are a high number of duplicate reports for this issue, please see the consolidated issue I have created for this here:

https://github.com/Stickymaddness/Procurement/issues/397

Please follow this issue for updates and ask any questions there.
