### ISSUE TITLE
[Consolidated Issue] Error 502, Timeouts, Slow Login Times

### ISSUE THREAD

**Issue by Stickymaddness** [Stickymaddness/Procurement#397]
GGG are having load issues on their API which causes Procurement to timeout and 

I have alerted GGG about the issue so that they can look into it, but in the meantime there is nothing I can do as the issue is on their end, however some users have been able to login by downloading **only** the tabs for the one league they are playing in. YMMV on this due to the current load on GGG's API and how many tabs you have.

I will update this issue once I have heard back from GGG.

**Comment by DrakeCoker** [comment]
Thanks for the update and explanation.

**Comment by Stickymaddness** [comment]
GGG have said the issue is due to a rise in load on their servers, they are rolling out more servers in the next couple of days.

In the meantime you can do your part to reduce load by only downloading the tabs for the league you are currently playing in.

**Comment by Stickymaddness** [comment]
GGG have said that the API should now be stabilised, in my testing Procurement now loads up quickly.

Can anyone else confirm?
