### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by MurphBear** [Stickymaddness/Procurement#406]
Trying to get started - get this error, cannot continue

Procurement 1.9.7 Initialized.
                                                           
Authenticating deliverme314@yahoo.com                                                     [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
You need to include your DebugInfo.log for me to see the error.
