### ISSUE TITLE
Error Downloading Stash

### ISSUE THREAD

**Issue by Draconis418** [Stickymaddness/Procurement#408]
Timing out downloading stash

[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/77545/DebugInfo.txt)

**Comment by Draconis418** [comment]
Sorry for not reading other tickets.

I will see if this changes in the next few days after more servers have been rolled out.
I am only trying to download the stash tabs for talisman.

**Comment by Stickymaddness** [comment]
No problem, GGG are looking into the issue as well. I'm going to close this and will post updates in the consolidated one.
