### ISSUE TITLE
[bug] item listed but it shouldnt

### ISSUE THREAD

**Issue by Vexxorian** [Stickymaddness/Procurement#409]
i have 2 corrupted Studded Belts, one rare triple res, second is The Magnate. i listed rare one for b/o of 10c, when someone said me that my weared magnate belt also listed for 10c. it was under "triple res" spoiler, so i guess its because of same base name and/or corruption. i double checked, magnate does not have any price set on it, it never been it stash at all.
i always use option "only display items with b/o" and manually set all b/o's and i 146% sure magnate listed is some kind of inner mistake.
after turning "select all" check off and on and updating thread problem disappeared. not sure how to repeat that problem :(

**Comment by Stickymaddness** [comment]
Are you able to replicate the pricing error, or did toggling select all fix the issue?

**Comment by Vexxorian** [comment]
toggling select all fixed the issue, but it was already turned on, i clicked it twice to "regenerate" list. dont know how to replicate error
