### ISSUE TITLE
Installer Doesn't Update/Replace Previous Version

### ISSUE THREAD

**Issue by UncleSlug** [Stickymaddness/Procurement#41]
I went from 1.8.5 to 1.8.6 on win7 64bit using the installer. Firstly the installer comes up with the default install location (c:\Procurement) instead of the current location. Secondly after choosing the existing directory, finishing the install and going into control panel -> programs there are two entries one for 1.8.5 and one for 1.8.6. 

If you try and reinstall 1.8.6 it remembers the directory etc.

Uninstalling the old and installing the new seems to work as a workaround.

**Comment by Stickymaddness** [comment]
Closing as I ended up ditching the installer.
