### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by Rads28** [Stickymaddness/Procurement#411]
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/78467/DebugInfo.txt)

**Comment by Stickymaddness** [comment]
First up download Procurement 1.9.8-RC, this is a preview release which I haven't fully released yet but does fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

Secondly, note that GGG are having issues with their server currently, so you might have problems logging in, details are covered in the following issue:

#397
