### ISSUE TITLE
Hardcore stash loading issue.. details + solution inside.

### ISSUE THREAD

**Issue by wh01683** [Stickymaddness/Procurement#418]
I'm very positive the error was caused because I had a hardcore character on standard but not on the new league. I created a character in hardcore and the program was able to load successfully.

DebugInfo files are attached.

The first debug info file is from version 1.9.7. Per Sticky's suggestion on another issue, I tried 1.9.8-RC1 but the error persisted. With the above fix, 1.9.8-RC1 worked. I did not test 1.9.7.

EDIT: This solution also works with 1.9.7

[DebugInfo1.9.7.txt](https://github.com/Stickymaddness/Procurement/files/83246/DebugInfo.txt)
[DebugInfo1.9.8-RC1.txt](https://github.com/Stickymaddness/Procurement/files/83248/DebugInfo1.9.8-RC1.txt)

**Comment by Stickymaddness** [comment]
Interesting, thanks for providing the info. What were your settings - set to default to download all leagues, or set to download specific leagues?

**Comment by wh01683** [comment]
This was my first time using Procurement on this computer, so the settings were all on default.
Also, changing the settings to download only for Talisman standard league after it started working did not affect its usability.
Anytime, happy to help!
