### ISSUE TITLE
System.Net.WebException

### ISSUE THREAD

**Issue by Myst789** [Stickymaddness/Procurement#420]
[10-01-2016 0:03] System.Net.WebException: O servidor remoto retornou um erro: (500) Erro Interno do Servidor.
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   em POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   em System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
GGG were having issues with their servers, this issue should now be fixed.
