### ISSUE TITLE
Suggestion: multiple item buyout at once

### ISSUE THREAD

**Issue by tswierkot** [Stickymaddness/Procurement#424]
At the moment, when you right-click an item, you can set a buyout for it and other stuff. 

My suggestion: make it possible to right-click and drag mouse over items to select many of them and then apply the result of the popup window to each item selected. This would make it way **easier** for setting buyouts for rows of **currenc**y.

Basically:
1. **OnMouseRightClickDown**, when mouse is over an item, **add** that item to a list.
2. **When mouse is dragged to a new item, **add** that item to list too.
3. **OnMouseRightClickUp** **show** the Buyout/Offer/Price window.
4. **Apply** the data input in the window to **every** item in the list.

**Comment by Stickymaddness** [comment]
A better currency buyout system is something I'd like to add, I just don't know when I will have time to do it.
