### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by Usernamewar** [Stickymaddness/Procurement#425]
Procurement 1.9.8-RC1 Initialized.
                                                       
Authenticating Usernamewar                                                                [OK]
Fetching account name...                                                                  

[Error] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

ja fiz tudo que podia, não sei mas o que posso faze para corrigir o erro

**Comment by Stickymaddness** [comment]
I need your debuginfo.log to help
