### ISSUE TITLE
Hey. Issues with latest version of procurement.

### ISSUE THREAD

**Issue by whitegiantfire** [Stickymaddness/Procurement#430]
[Error] Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Reinstalled, rebooted pc, poe is shut down .

**Comment by Stickymaddness** [comment]
Have you tried Procurement 1.9.8-RC1?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

**Comment by whitegiantfire** [comment]
Hey. Yeah tried dling it, installing and launching. Everything except launching worked : the application gets blocked and deleted by my Panda Antivirus, saying it's a virus. :/
