### ISSUE TITLE
[Error] Downloading stash for Talisman, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by nothinqqq** [Stickymaddness/Procurement#431]
Hello, debug
[16-01-2016 11:23] System.Runtime.Serialization.SerializationException: Očekává se stav Element.. Nalezeno Text s názvem , obor názvů . 
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   v System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   v ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   v System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   v System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   v System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   v System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[16-01-2016 11:23] JSON Serialization Failed: base64 bytes:
[16-01-2016 11:23] ZmFsc2U=
[16-01-2016 11:23] END
[16-01-2016 11:23] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   v POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
[16-01-2016 11:23] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   v POEApi.Model.POEModel.GetStash(String league, String accountName)
   v Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   v Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   v System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   v System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   v Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   v System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
