### ISSUE TITLE
Error : Loading Standard Stash Tab 1...

### ISSUE THREAD

**Issue by rvrr** [Stickymaddness/Procurement#432]
Hi 

Procurement 1.9.7 Initialized.
                                                           
Authenticating daxxwxxx@hotmail.com                                                      [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Help me please

**Comment by Darkis133** [comment]
same issue

**Comment by rvrr** [comment]
already solved, everything perfect
