### ISSUE TITLE
Downloading stash for Standard

### ISSUE THREAD

**Issue by Chiwt** [Stickymaddness/Procurement#433]
Authenticating fernandotrag1                                                              [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           
Loading Standard Stash Tab 1...                                                           

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Help me pls

**Comment by Stickymaddness** [comment]
Have you tried Procurement 1.9.8-RC1?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
