### ISSUE TITLE
Error Loading Stash

### ISSUE THREAD

**Issue by nhoxbodvn** [Stickymaddness/Procurement#444]
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
You need to include DebugInfo.log so I can see what the error is.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
