### ISSUE TITLE
[Error] Error getting items from league, are you sure you league settings are correct?

### ISSUE THREAD

**Issue by higorbrazillian** [Stickymaddness/Procurement#450]
[25-01-2016 0:26] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
   em Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-01-2016 0:26] Application Version: Procurement 1.9.7
[25-01-2016 0:26] 
CurrentCulture: pt-BR
CurrentUICulture: pt-BR
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Current League: 

[25-01-2016 0:26] System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   em Procurement.ViewModel.ScreenController.<initScreens>b__0()
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-01-2016 0:27] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
   em Procurement.ViewModel.StashViewModel.getAvailableItems()

[25-01-2016 0:27] Application Version: Procurement 1.9.7
[25-01-2016 0:27] 
CurrentCulture: pt-BR
CurrentUICulture: pt-BR
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Current League: 

[25-01-2016 0:27] System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   em Procurement.ViewModel.ScreenController.<initScreens>b__0()
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[25-01-2016 0:28] 
Error: attempted to get items for the non existant league ''
Current leagues are:

**Comment by Stickymaddness** [comment]
It looks like no league info is being returned by GGG for your account, are you logging in using sessionID?

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
