### ISSUE TITLE
[Error] Downloading stash for Hardcore Talisman with debug info log 

### ISSUE THREAD

**Issue by JouluPerkele** [Stickymaddness/Procurement#464]
Sorry about the language :D

[31-01-2016 6:49] System.Runtime.Serialization.SerializationException: Odotetaan tilaa Element.. Löydettiin Text, jolla on nimi , nimitila . 
   kohteessa System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   kohteessa System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   kohteessa ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   kohteessa System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   kohteessa System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   kohteessa System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   kohteessa System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   kohteessa System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   kohteessa System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   kohteessa System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[31-01-2016 6:49] JSON Serialization Failed: base64 bytes:
[31-01-2016 6:49] ZmFsc2U=
[31-01-2016 6:49] END
[31-01-2016 6:49] Error downloading stash for Hardcore Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   kohteessa POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   kohteessa POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
[31-01-2016 6:49] System.Exception: Downloading stash for Hardcore Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   kohteessa POEApi.Model.POEModel.GetStash(String league, String accountName)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   kohteessa System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   kohteessa System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   kohteessa Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   kohteessa System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
1.9.7-RC1 should fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
