### ISSUE TITLE
ERROR DOWNLOADING STASH

### ISSUE THREAD

**Issue by prokillking** [Stickymaddness/Procurement#468]
[02-02-2016 14:02] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[02-02-2016 14:02] JSON Serialization Failed: base64 bytes:
[02-02-2016 14:02] ZmFsc2U=
[02-02-2016 14:02] END
[02-02-2016 14:02] Error downloading stash for Standard, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-02-2016 14:02] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
1.9.7-RC1 should fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
