### ISSUE TITLE
Error Downloading stash for Talisman

### ISSUE THREAD

**Issue by ghettomos** [Stickymaddness/Procurement#469]
[03-02-2016 22:45] POEApi.Infrastructure.LogonFailedException: Incorrect session id
   bei POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   bei POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[03-02-2016 22:48] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[03-02-2016 22:48] JSON Serialization Failed: base64 bytes:
[03-02-2016 22:48] ZmFsc2U=
[03-02-2016 22:48] END
[03-02-2016 22:48] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-02-2016 22:48] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[03-02-2016 22:48] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[03-02-2016 22:48] JSON Serialization Failed: base64 bytes:
[03-02-2016 22:48] ZmFsc2U=
[03-02-2016 22:48] END
[03-02-2016 22:48] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-02-2016 22:48] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()
[03-02-2016 22:50] System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[03-02-2016 22:50] JSON Serialization Failed: base64 bytes:
[03-02-2016 22:50] ZmFsc2U=
[03-02-2016 22:50] END
[03-02-2016 22:50] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[03-02-2016 22:50] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
1.9.7-RC1 should fix this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
