### ISSUE TITLE
[Error] Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by CobraCombs** [Stickymaddness/Procurement#477]
What do I do now?

**Comment by Stickymaddness** [comment]
I need your debuginfo.log in order to help, but most likely 1.9.7-RC1 will fix the issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
