### ISSUE TITLE
Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by tonyman2009** [Stickymaddness/Procurement#492]
[27-02-2016 21:23] System.Runtime.Serialization.SerializationException: Αναμένεται κατάσταση 'Element'.. Παρουσιάστηκε 'Text'  με όνομα '', χώρος ονομάτων ''. 
   σε System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   σε System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   σε ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   σε System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   σε System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   σε System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   σε System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   σε System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   σε System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   σε System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   σε POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
[27-02-2016 21:23] JSON Serialization Failed: base64 bytes:
[27-02-2016 21:23] ZmFsc2U=
[27-02-2016 21:23] END
[27-02-2016 21:23] Error downloading stash for Talisman, exception details: System.Exception: Downloading stash, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   σε POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   σε POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   σε POEApi.Model.POEModel.GetStash(String league, String accountName)
[27-02-2016 21:23] System.Exception: Downloading stash for Talisman, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
   σε POEApi.Model.POEModel.GetStash(String league, String accountName)
   σε Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   σε Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   σε System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   σε System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   σε Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   σε System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 will fix this issue.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1
