### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by thailyn** [Stickymaddness/Procurement#494]
In #194, you stated the license for Procurement is Artistic License 2.0, and it's documented in the about screen.  Can we have a LICENSE or LICENSE.txt file in the repo stating this and making it explicit?  I would need such a file present before contributing any more code (it's been a while...).

In terms of what that license should be, I trust you understand licenses well.  I, however, do not, especially when trying to get them to interoperate.  My interpretation of the GPLv2 (which is probably wrong) brings a few complications to mind:
- According to this [list of licenses](https://www.gnu.org/licenses/license-list.html#GNUGPL), the Artistic License 2.0 [is compatible](https://www.gnu.org/licenses/license-list.html#ArtisticLicense2) with the GNU GPL licenses.  Thus, all of the code except for RequestThrottle can be licensed under the Artistic License 2.0.  However, according to [this FAQ question](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean), the combined work (Procurement as a whole) must be distributed under the GPLv2.  I could be wrong, but that's how I'm reading it.
- You modified the RequestThrottle class, even if simply to put it in a namespace to fit in with the rest of Procurement, but section 2a of the [GPLv2](https://tldrlegal.com/license/artistic-license-2.0-%28artistic%29#fulltext) says, "you must cause the modified files to carry prominent notices stating that you changed the files and the date of any change," and I don't see any such notice in the file.

My apologies for perhaps splitting hairs on all this, but I just want to make sure there isn't any possibility of license complications with these multiple licenses intermingling.

**Comment by Stickymaddness** [comment]
Hi Thailyn,

I actually do not understand licenses well myself at all. Case in point, I did not realise the namespace addition in RequestThrottle required a notice explaining the change, nor did I consider that multiple licenses might be a problem.

Prior to Procurement I had no experience with creating an open source project, and certainly did not expect it to become as big as it did or still be going 3 years down the road. I just wanted to share Procurement and picked a license that google code supported that seemed to me to be the most straight forward.

Point taken on what you have brought up above though.

I'm happy to add a LICENSE.txt with the Artistic License 2.0, and will need to look into the potential issues with GPLv2/RequestThrottle that you have brought up.

**Comment by thailyn** [comment]
Hi, Stickymaddness.

I'm glad I'm not the only one whose brain hurts just thinking about licenses. :)

I did a little more research about the GPL licenses, since I'm currently traveling and haven't started playing PoE again just yet, which would make me want to futz with Procurement instead.

From everything I've seen, without making any [non-comments] code changes, you need to release Procurement under the GPL, since you use GPL-licensed code/libraries (and it's not behind a binary wrapper, yadda yadda yadda...): it's a "derived work" of the GPL-licensed code, not a "[combined work](https://en.wikipedia.org/wiki/License_compatibility#Kinds_of_combined_works)."  This [Stack Exchange answer](http://programmers.stackexchange.com/questions/204410/how-are-gpl-compatible-licenses-like-mit-usable-in-gpl-programs-without-being-su/204497#204497) essentially covers our situation, and it links to a bunch of FSF and related pages for more information.  Specifically, see the "Where it gets tricky" section.

However, we have a big, unresolved question (at least in my mind).  Everything I've found talks about combining a GPL project (such as a library) with a non-GPL-licenced (but GPL-compatible) project that already exists, and addressing what the union of those two projects would be ("Foo+Bar", in that SE example).

With Procurement, do we have all of these pieces: Foo, Bar, and Foo+Bar?  Say, Foo is the RequestThrottle class, and Bar is everything else in this Procurement repo (what you wrote and what others have contributed to Procurement).  Foo+Bar would be what you've been releasing as "Procurement".

But: is "Bar" actually a separate "project"?  This is perhaps a philosophical question, but it's definitely a legal question and I don't know the answer for sure.  Another way to ask this: was there "Procurement" before you added the RequestThrottle class?  Or, from the very start of "Procurement", was RequestThrottle already present?  Because you moved to GitHub from Google Code (and didn't import the entire history... *grumble*), the [file history](https://github.com/Stickymaddness/Procurement/commits/1d37d099cdff5fdacfcee4822701779374c5c26b/POEApi.Transport/Throttle.cs) doesn't help.  Did you have Procurement releases before adding that class?  If so, the "Bar" could be Procurement before adding that class, and "Foo+Bar" Procurement after adding it.  From that point on, Procurement releases would be under the GPL.  But, at least the code you wrote before adding RequestThrottle would be correctly under the Artistic License, and we might be able to argue "Procurement" now is the union of those two projects.

Two other points:

1. If we rewrote RequestThrottle from scratch, we could get rid of the GPL-licnesed code, and release Procurement after that point unabashedly under the Artistic License, since you can relicense code you own however you want (in isolation).  I don't think it would be that hard to rewrite it.
1. I'm not sure how contributions to Procurement from other people are licensed.  Since the contributors know they're giving you the code I'm assuming it might just go under the license of your choice.  You also have the option of making that explicit, but you don't have a CONTRIBUTING file or anything like that.  I only mention this in light of (1): if what other people contribute are GPL-licenced because "Procurement" was GPL-licensed at the time of contribution (I don't know if this is logical, though), can you re-license those pieces of code?  Since you didn't make it explicit that contributors revoke their copyright over the code they contributed.  But you might gain that right, anyway, when the contribution is made.

So, I see these options going forward:

1. Just give up on the Artistic License and make Procurement GPL-licensed. (Easy, but amounts to giving up.)
2. Figure out when Procurement turned into "Procurement+RequestThrottle", and license the union under the GPL.  I don't know if this means any edits/additions to Procurement files other than RequestThrottle since that point would need to be GPL-licensed, though. (See [this other](http://stackoverflow.com/a/11815617) really helpful SE answer.)
3. Rewrite RequestThrottle so we can have everything under the Artistic License. (To be most correct, though, we would still need to do (1) or (2) retroactively for code/releases between adding RequestThrottle and later removing it.  But the important part is knowing how the code is licensed going forward.)

**Comment by Stickymaddness** [comment]
Hi Thailyn,

It's been a while - I can relate to taking long breaks though! 

Interesting that you're employer holds copyright for your work, I wasn't really aware of things like that. I'll take a look at the PR, it'll be nice to have this solved!
