### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by noeddebo** [Stickymaddness/Procurement#495]
Hey, nice addon you have made here, I've heard alot good about it, however, i doesn't seem to be working on my computer, when i try to login i get this error message:

 
> Procurement 1.9.7 Initialized.
>                                                            
> Authenticating XXXXXX                                                                  [OK]
> Loading characters...                                                                     [OK]
> Loading Standard Stash Tab 1...                                                           
> 
> [Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Thanks for the help in advance! ::)

**Comment by noeddebo** [comment]
Never find, I solved the error! I simply downloaded the 1.9.8-RC version!!! 
I think you should update the link on https://www.pathofexile.com/forum/view-thread/172710 (the first link on google search) to the newest version! 
Cheers!

**Comment by Stickymaddness** [comment]
Glad you got it sorted, I want to get a proper release out asap but I'll update the links in the mean time!
