### ISSUE TITLE
Shop text character limit

### ISSUE THREAD

**Issue by DarknessStorm** [Stickymaddness/Procurement#496]
Greetings. When i was migrating from procurement medved edition to originall proc. (1.9.8-RC1) and set the price to all my items, i got an error: 
http://www.picshare.ru/uploads/160304/Lw375UvvsR.jpg
I'm absolutely sure that Medved ed. can go higher than this limit... so, original procurement can not?

**Comment by Stickymaddness** [comment]
Hi there,

The 50k limit is something GGG imposed on the forum - you can't make a post longer than 50k characters.
