### ISSUE TITLE
Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

### ISSUE THREAD

**Issue by Liktor** [Stickymaddness/Procurement#502]

**Comment by Stickymaddness** [comment]
I need to see what's in your debuginfo.log or I can't help

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
