### ISSUE TITLE
Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

### ISSUE THREAD

**Issue by twiices** [Stickymaddness/Procurement#507]
[06-03-2016 14:36] Error downloading account name, exception details: System.Runtime.Serialization.SerializationException: Se espera el estado 'Element'.. Se encontró 'Text' con el nombre '', espacio de nombres ''. 
   en System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   en System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   en ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   en System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   en System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   en System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   en System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   en System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   en System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   en System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   en POEApi.Model.POEModel.GetAccountName()
[06-03-2016 14:36] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   en POEApi.Model.POEModel.GetAccountName()
   en Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   en System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.9.8-RC1 fixes this issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC1

If you have problems logging in due to Perandus coins look at issue #506

**Comment by twiices** [comment]
Already have this version and still have the problem.

**Comment by cchopps** [comment]
I'm having this issue, too. It just sits on the loading screen. All that it says in the box below is "Procurement 1.9.8-RC1 Initialized." 

I do have P.Coins but I already took the steps in #506.

**Comment by Stickymaddness** [comment]
@twiices What happens when you try login with 1.9.8-RC1? Do you get an error?

@cchopps It sounds like something is blocking Procurement's connection, check your firewall/av/etc and open a separate issue for yourself.

**Comment by cchopps** [comment]
That did it. Thanks!

**Comment by Stickymaddness** [comment]
Np!
