### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Trapstarx** [Stickymaddness/Procurement#513]
[07-03-2016 16:00] System.Exception: Downloading stash for Hardcore Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   в System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please see issue #506 on how to get around this error until a new release of Procurement is available.
