### ISSUE TITLE
Error downloading account name

### ISSUE THREAD

**Issue by finalkenpachi** [Stickymaddness/Procurement#522]
[08-03-2016 9:11] Error downloading account name, exception details: System.Runtime.Serialization.SerializationException: 'Element' durumu bekleniyor.. Karşılaşılan: 'Text' adı: '', ad alanı: ''. 
   konum: System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   konum: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   konum: ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   konum: System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   konum: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   konum: System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   konum: System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   konum: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   konum: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   konum: System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   konum: POEApi.Model.POEModel.GetAccountName()
[08-03-2016 9:11] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   konum: POEApi.Model.POEModel.GetAccountName()
   konum: Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   konum: System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement is getting an empty response when trying to download your account name, I would check that you don't have any firewall/av/etc blocking the connection.

**Comment by finalkenpachi** [comment]
Nope. I was using same firewall like 4-5 months. But i get this error with new ascendancy update.

**Comment by Stickymaddness** [comment]
So Procurement has been working fine until the ascendancy update?

Try login a few more times and see if you can login, I suspect this may be due to issues with GGG's servers.

**Comment by finalkenpachi** [comment]
Yes it was works fine before the update. After update it's said your Session ID is wrong. So i go to GGG  site and getting my new session id. After change my session id i can able to login but got this error now.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
