### ISSUE TITLE
logged in but not showing tabs/inventory - perandus

### ISSUE THREAD

**Issue by danflowson** [Stickymaddness/Procurement#530]
I get logged in to procurement fine after taking coins out of stash, I've added all the info below into the settings. When I get logged in it only shows 1 stash tab, and it doesn't show its contents.  The only thing I can get it to list is what my character is wearing. Also, When I hit inventory in the procurement app it crashes.  Any ideas?
 added several `<item value="stash#"/>` to my settings

**Comment by danflowson** [comment]
oops this is what I added to settings

<List name="MyTabs">
      
      <Item value="Stash1" />
      <Item value="Stash2" />
      <Item value="Stash3" />
      <Item value="Stash4" />
      <Item value="Stash5" />
      <Item value="Stash6" />
      <Item value="Stash7" />
      <Item value="Stash8" />
      <Item value="Stash9" />
      <Item value="Stash10" />
      <Item value="Stash11" />

**Comment by danflowson** [comment]
<List name="MyTabs">
      
      <Item value="Stash1" />
      <Item value="Stash2" />
      <Item value="Stash3" />
      <Item value="Stash4" />
      <Item value="Stash5" />
      <Item value="Stash6" />
      <Item value="Stash7" />
      <Item value="Stash8" />
      <Item value="Stash9" />
      <Item value="Stash10" />
      <Item value="Stash11" />

**Comment by danflowson** [comment]
<List name="MyTabs">
  
      <Item value="Stash1" />
      <Item value="Stash2" />
      <Item value="Stash3" />
      <Item value="Stash4" />
      <Item value="Stash5" />
      <Item value="Stash6" />
      <Item value="Stash7" />
      <Item value="Stash8" />
      <Item value="Stash9" />
      <Item value="Stash10" />
      <Item value="Stash11" />

**Comment by danflowson** [comment]
this is what I added in settings ect.
      
      <Item value="Stash1" />
      <Item value="Stash2" />
      <Item value="Stash3" />

**Comment by danflowson** [comment]
this is what I added in settings ect.
<Item value="Stash1" /> <Item value="Stash2" /> <Item value="Stash3" /> <Item value="Stash4" />

**Comment by danflowson** [comment]
this is what I added in settings. with out the extra -- 
   --  -- 
   --   <Item value="Stash1" />-- 
    --  <Item value="Stash2" />--
   --   <Item value="Stash3" />--
   --   <Item value="Stash4" />--
 -- --

**Comment by Stickymaddness** [comment]
Hmm, it sounds like you settings may be incorrect and it hasn't downloaded any tabs. 

If you're using non premium tabs, one that the value should simply be the number. "1", "2", etc. Please send me your full MyTabs config section so I can take a look.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
