### ISSUE TITLE
[Error] Downloading stash for Perandus

### ISSUE THREAD

**Issue by EarleWindom** [Stickymaddness/Procurement#534]
don't know where to get debug info

**Comment by Stickymaddness** [comment]
It should be in the same directory as Procurement.exe, however take a look at issue #506  if you have perandus coins in your stash.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
