### ISSUE TITLE
Update online status every minute

### ISSUE THREAD

**Issue by xyzz** [Stickymaddness/Procurement#538]
Hello, control.poe.trade has been updated to limit online status to 5 minutes (previously it was an hour). Could procurement be updated to send online status update every minute or so?

**Comment by Stickymaddness** [comment]
Thanks for letting me know, I'll update it to every 5 minutes and include it in the next release, which will be soon.

**Comment by xyzz** [comment]
Thanks, but please make sure to make it less than 5 minutes to ensure the status is updated before user is automatically switched to offline.

**Comment by Stickymaddness** [comment]
Alright, would every 4 minutes be sufficient?

**Comment by xyzz** [comment]
Yes, should work fine.

**Comment by Stickymaddness** [comment]
Great, I've merged the change. It will be included in the next release which should be very soon.
