### ISSUE TITLE
Cant see bottom of precurement screen

### ISSUE THREAD

**Issue by unseenblkman** [Stickymaddness/Procurement#540]
#im trying to see the bottom of the program but it is cut off and it wont let me scroll down
![bug](https://cloud.githubusercontent.com/assets/17732443/13690581/9fffbadc-e6ff-11e5-8258-0060d2caa612.png)

**Comment by Stickymaddness** [comment]
Click the tickbox labled "Compact Mode" and restart Procurement, this will drop the big fancy header and footer so it fits properly.

**Comment by unseenblkman** [comment]
thank you this worked out !!!
