### ISSUE TITLE
[Error] Downloading stash for Perandus

### ISSUE THREAD

**Issue by OldManCasual** [Stickymaddness/Procurement#542]
won't let me log in due to error in title. 

account name: casual2567

**Comment by Stickymaddness** [comment]
Have you tried Procurement 1.9.8-RC2?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC2

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
