### ISSUE TITLE
[Error] Downloading stash for Hardcore Perandus

### ISSUE THREAD

**Issue by blitzscreen003** [Stickymaddness/Procurement#544]
[Error] Downloading stash for Hardcore Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues
Account name: blitzscreen

**Comment by Stickymaddness** [comment]
Have you tried Procurement 1.9.8-RC2?

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC2

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
