### ISSUE TITLE
Crash: ascendancy class avatar not found

### ISSUE THREAD

**Issue by qrthur** [Stickymaddness/Procurement#546]
Hey,

When I click Inventory, Procurement crashes. Here's what I found in the debug log:

[13-03-2016 16:05] System.Windows.Markup.XamlParseException: Cannot locate resource 'images/avatars/raider.png'. ---> System.IO.IOException: Cannot locate resource 'images/avatars/raider.png'.

I am using 1.9.8-RC2

**Comment by Stickymaddness** [comment]
Thanks for reporting this. 

The crash is due to the new ascendancy classes, which Procurement does not support (yet). I'll fix this for the next release.

**Comment by hakkotsu** [comment]
Fixed in https://github.com/Stickymaddness/Procurement/pull/552

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
