### ISSUE TITLE
automatic online refresh

### ISSUE THREAD

**Issue by EarleWindom** [Stickymaddness/Procurement#550]
for some reason i'm not listed as online on poe.trade even though i got my personal trade url and set procurement to automatically refresh my online status.
if i open my trade url to manually go online, i get online but only for 5 minutes and then offline again
what am i doing wrong?
cheers

**Comment by Stickymaddness** [comment]
poe.trade was recently updated to set you as offline after 5 minutes, I've updated Procurement to refresh every 4 minutes, and the update will be included in the next release.

**Comment by EarleWindom** [comment]
ah i see, looking forward for the next release then :D 
thanks for your help and have a nice day!

**Comment by Stickymaddness** [comment]
New release is out!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
