### ISSUE TITLE
Crashing on Loading perandus stash tab

### ISSUE THREAD

**Issue by SteveDeeks** [Stickymaddness/Procurement#551]
Hi My procurement application keeps crashing when trying to load the stash tabs and tells me i should log a ticket here lol, 
Procurement 1.9.7 Initialized.
                                                           
Authenticating Steve Deeks                                                                [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]
Loading Standard Stash Tab 2...                                                           [OK]
Loading Standard Stash Tab 3...                                                           [OK]
Loading Standard Stash Tab 4...                                                           [OK]
Loading Sherlock_spiff's inventory...                                                     [OK]
Loading Perandus Stash Tab 1...                                                           [OK]

[Error] Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Any help would be grateful cheers

**Comment by hakkotsu** [comment]
Can you upload DebugInfo.log?

**Comment by SteveDeeks** [comment]
Sure Ive had to add it as a word doc as the txt file didnt want to know lol


[debug.docx](https://github.com/Stickymaddness/Procurement/files/177720/debug.docx)

**Comment by Stickymaddness** [comment]
1.9.8-RC2 will fix your specific issue:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8-RC2

Note that you might still run into issues due to ascendancy changes, which will be fixed soon in the next release.

**Comment by Stickymaddness** [comment]
Procurement 1.9.8 has been released, please retest and open a new issue if you still have problems

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.8
