### ISSUE TITLE
wont go auto online

### ISSUE THREAD

**Issue by zowy12** [Stickymaddness/Procurement#559]
wont go auto online , only goes online when i start the program and stays for 5 mins and then stays offline

**Comment by hakkotsu** [comment]
try to request new poe.trade url

**Comment by zowy12** [comment]
tried gives the same one

**Comment by hakkotsu** [comment]
Try last version of Procurement from this page https://github.com/Stickymaddness/Procurement/releases

**Comment by zowy12** [comment]
am already using it , :(

**Comment by Stickymaddness** [comment]
This has finally been fixed in the latest release, please open a new ticket if you run into further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
