### ISSUE TITLE
Not staying auto-online

### ISSUE THREAD

**Issue by Ehlol** [Stickymaddness/Procurement#561]
Newest version of Procurement is installed. Poe.trade URL is listed under "Trade Settings". "Enable automatic poe.trade online refresh" is ticked. Forum thread has been bumped and updated through Forum Export in Procurement. Tried to request new URL through the pathofxile.com forum, but I just received the same URL once again. I show up as online for 5min when I manually go to my personal url and click "become online", but then I show as offline again even though both Procurement is open and I'm online ingame.

Any suggestions, please? And thanks for the hard work on the software!

**Comment by babylone99** [comment]
Same error here

**Comment by DarknessStorm** [comment]
same here. why i'm always offline?

**Comment by Stickymaddness** [comment]
This has finally been fixed in the latest release, please open a new ticket if you run into further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
