### ISSUE TITLE
My shop not showing on the poe.trade

### ISSUE THREAD

**Issue by Peucoz** [Stickymaddness/Procurement#564]
Hi.
My shop not showing on the poe.trade , i update and bump all time but i can't see my items on poe.trade if i go to search, can be fixed this ? 
My shop on forum : https://www.pathofexile.com/forum/view-thread/1558904
Thank you !!!

**Comment by Stickymaddness** [comment]
Hi,

I don't have any control over poe.trade (not my site), take a look at the poe.trade thread on the forum and read the FAQ there on how to get your shop to appear, if you still have issues I would suggest asking in the thread.
