### ISSUE TITLE
Procurement wont start/show online

### ISSUE THREAD

**Issue by PyroIsBack** [Stickymaddness/Procurement#566]
Well basicly i got 3 kind of errors.

1. When i try to start i get
"[Error] Could not find a part of the path 'C:\Users\XXXXX\Desktop\Procurement\XXXXXXXXXXXX\characterdata.bin'."
2. Sometimes i pass the point above and make into Procurement. Then my Editing/Bumbping etc. work BUT it wont show me online in poe.trade even if i am online in forum.
3. Since this morning i cant get into Procurement at all. I get the message:
[Error] Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
[DebugInfo.txt](https://github.com/Stickymaddness/Procurement/files/190442/DebugInfo.txt)

BTW: I had never Problems with Procurement. Problems show up after getting newest version.

**Comment by Stickymaddness** [comment]
The error looks like a timeout, which is a connection related issue either on your side or on GGG's.

Create a new clean installation in C:\Procurement with the latest version (1.9.8) and try login again.
