### ISSUE TITLE
Recipes not updated after tab refresh

### ISSUE THREAD

**Issue by OchseGit** [Stickymaddness/Procurement#567]
The list of recipes is not updated after a tab refresh.

**Comment by Stickymaddness** [comment]
I'll take a look into this.

**Comment by Stickymaddness** [comment]
This should be fixed now

**Comment by robertsmieja** [comment]
Is there any estimate for when a new release with this fix will be available?

**Comment by aydjay** [comment]
Looks like 1.20 will have your fix. Please let us know if this is not working as intended.
