### ISSUE TITLE
error getting itens for league

### ISSUE THREAD

**Issue by KHOLLYNS** [Stickymaddness/Procurement#568]
error getting itens for league

**Comment by Stickymaddness** [comment]
I need your debuglog

**Comment by Hjalmarssoon** [comment]
I have the same problem, how do i get "debuglog"
I've been using procurement for a couple of months without any issues, but since i downloaded 1.9.8 it stoped working.
Sorry im bad at this stuff.

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
