### ISSUE TITLE
Not refreshing online status

### ISSUE THREAD

**Issue by DarknessStorm** [Stickymaddness/Procurement#571]
So, as the title says...
I'm using the latest build of Procur. checked the checkbox to autorefresh, but my status is always offline. Tried to pm for the new link for my control panel, but it's always the same as in past.
I can go online but only from control panel manually which is shitty. What's happening with procurement? Or is it caused by author of poetrade to force use of Acquisition?

**Comment by djgamerdude** [comment]
Same here. It started with 1.9.8

**Comment by Stickymaddness** [comment]
@xyzz made a change which reduced the refresh time from 1 hour to 5 minutes. In 1.9.8 I set Procurement to refresh every 4 minutes, but it appears this isn't often enough.

I've released 1.9.9 which sets the refresh to every 2 minutes, hopefully this fixes the issue.

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

**Comment by rigoparis** [comment]
Hello!

First of all, I want to thank you for this awesome tool!

Now, this issue has not been fixed yet, I'm still unable to automatically refresh my online status, I have to manually keep going to my URL and activating.

Can you please look into this and get a fix, please

Many thanks for your time!

**Comment by Stickymaddness** [comment]
This has finally been fixed in the latest release, please open a new ticket if you run into further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
