### ISSUE TITLE
Procurement loads forever, or makes Errors. No Online Refresh at Poe.trade

### ISSUE THREAD

**Issue by KomodoOne** [Stickymaddness/Procurement#572]
as the Theme says..
Procurment takes almost 5 minutes to load everything even having only 1 league loaded.
Happens since about 4 days.
A lot of Bump or Update forum Errors.
Online Status doesnt get refreshed at Poe.trade 

Uploading the Debug doesnt work either here so : 

[02-04-2016 7:38] Error downloading stash for Perandus, exception details: System.Net.WebException: Timeout für Vorgang überschritten
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-04-2016 7:38] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()
[02-04-2016 7:42] Error downloading stash for Perandus, exception details: System.Net.WebException: Timeout für Vorgang überschritten
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   bei POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   bei POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-04-2016 7:42] System.Exception: Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetStash(String league, String accountName)
   bei Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__25.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass24_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This looks like it was due to GGG server side issues, Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
