### ISSUE TITLE
Search function doesn't work after buying a currency tab

### ISSUE THREAD

**Issue by Grigore1** [Stickymaddness/Procurement#585]
As title says, I bought a currency tab, and after restarting Procurement, the search functions no longer works, eg, it will no longer narrow down tabs to the search term.

**Comment by everyothernameistaken** [comment]
Same here.  Please fix.  This is killing me!!

**Comment by damoochie** [comment]
Here's a link to the thread with a temporary (custom) version of procurement which has the search function working. [https://github.com/Stickymaddness/Procurement/issues/565](url)

**Comment by ongobongo** [comment]
Fixed in #593

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

**Comment by everyothernameistaken** [comment]
Thank you.  Playing without procurement have been a NIGHTMARE. 
 

    On Saturday, May 21, 2016 7:32 AM, Stickymaddness <notifications@github.com> wrote:
 

 Procurement 1.9.9 has been released, which fixes this issue!https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9—
