### ISSUE TITLE
[Error] Downloading stash for Hardcore

### ISSUE THREAD

**Issue by Addibee** [Stickymaddness/Procurement#589]
Help! =( cant log in!

[DebugInfo.pdf](https://github.com/Stickymaddness/Procurement/files/225492/DebugInfo.pdf)

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
