### ISSUE TITLE
Error downloading stash for perandus

### ISSUE THREAD

**Issue by mthegreat** [Stickymaddness/Procurement#591]

**Comment by mthegreat** [comment]
[Error] Downloading stash for Perandus, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, please retest and reopen your issue if your error persists:

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
