### ISSUE TITLE
Feauture Request (life% search)

### ISSUE THREAD

**Issue by IceLancerSR** [Stickymaddness/Procurement#592]
Hello!
Could i request ability to search % life ?
it would enable search jewels with %life,since jewels do not have +life.
Same could also be applied to ES %
craft mods/jewels
Thanks

**Comment by Stickymaddness** [comment]
Hi there,

I've released Procurement 1.9.9 which includes the % Life and ES search you requested!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9

**Comment by IceLancerSR** [comment]
Thank you! Well done
