### ISSUE TITLE
Mismatching count in currency tab.

### ISSUE THREAD

**Issue by ruodokas** [Stickymaddness/Procurement#597]
Procurement doesn't count the extra slots in currency tab (the 5 at bottom, where you can put any currency you wish); these were changed by GGG soon after the initial launch of aforementioned tabs. Picture attached (see wisdom scrolls), as it explains ir more easily rather than me writing a 200 words long novel.
![snap2](https://cloud.githubusercontent.com/assets/10427426/14941390/a4452f94-0fa1-11e6-975c-9b1ad143f445.png)

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
