### ISSUE TITLE
ERROR advanced search!!

### ISSUE THREAD

**Issue by lehi92** [Stickymaddness/Procurement#598]
when i click in a advanced search and choose any alternative, the program chashed an i received message to go here and related this.

**Comment by genbtc** [comment]
You must have some item in your stash that the program does not expect to see - causing the crash, because it is working for me.

**Comment by Stickymaddness** [comment]
Procurement 1.9.9 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.9
