### ISSUE TITLE
Error getting items from League, are you sure your league settings are correct?

### ISSUE THREAD

**Issue by Slosserman** [Stickymaddness/Procurement#606]
New to ALL trading.
Procurement looks very cool.
Created account on PoE
Authentication worked fine, but before getting anywhere I got that error message.
Tried to go to Settings in Procurement and change perandus to Prophecy. Didn't work
Tried to go to Settings in Procurement and remove any league but standard and Hardcore.

attached screenshot
![login problem](https://cloud.githubusercontent.com/assets/19887695/15990435/7bc99110-3092-11e6-9003-a3c63c6f7fd9.png)

Best regards 
Kris

**Comment by Stickymaddness** [comment]
Hey Kris,

The error is due to GGG returning that you have no items in your stash, it can sometimes happen to new players.

The new release has the correct settings for the new leagues, so test with it again:

https://github.com/Stickymaddness/Procurement/releases/tag/1.10.0

**Comment by LucasA2** [comment]
I am also this problem!! I installed the program now have the 1.10.0 version. What can I do?
