### ISSUE TITLE
Item note is considered having a buyout.

### ISSUE THREAD

**Issue by mirle** [Stickymaddness/Procurement#62]
Hi,

Here's something I don't expect to work that way.
I've enabled "only items with buyouts" in the trade settings screen and usually select all my tabs.
If I add a note to an item, the note is stored in the buyouts.xml. Apparently that's enough for the forum exporter to believe it has a buyout and it's added to the post (without a buyout).

I'd expect the exporter to only include items that actually have a valid buyout value.

Cheers.

**Comment by Stickymaddness** [comment]
This has been fixed, and will be in the next release.
