### ISSUE TITLE
Can't Log on

### ISSUE THREAD

**Issue by Purefox** [Stickymaddness/Procurement#620]
I just recently downloaded Procurement 1.9.9 for the first time. This was my first attempt to log in- after inputting my email and password it starts authenticating my account and once it says "Done!" I get a message called "Error loading items- Error getting items for league, are you sure your league settings are correct?". Is there a solution for this? 
Thanks.

**Comment by Stickymaddness** [comment]
Are you a steam user? Have you tried logging in using sessionID?

**Comment by Purefox** [comment]
Yep, i've fixed the problem, thanks for the help, much appreciated. Keep up
the good work.
