### ISSUE TITLE
Error when hovering over "Reefbane" Item

### ISSUE THREAD

**Issue by Rebosch** [Stickymaddness/Procurement#622]
http://pathofexile.gamepedia.com/Reefbane

**Comment by Rebosch** [comment]
When the mouse hits the reefbane icon following error leads to shutdown: "There was an unhandled error - Sorry! Please create a ticket......"

**Comment by yazilliclick** [comment]
Just tested, this happens when it's 4 sockets.

**Comment by Stickymaddness** [comment]
Makes sense, the socket/link placement code was written very early on so this will need to be updated to handle the unusual placement.

**Comment by Stickymaddness** [comment]
This has, finally, been fixed in [Procurement 1.24.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.2)
