### ISSUE TITLE
Cant Log On

### ISSUE THREAD

**Issue by 4DaNguyen** [Stickymaddness/Procurement#624]
I just downloaded Procurement 1.9.9 and after i run the program it ask me to log in using my email and password.  After i enter my info it Autenticates, fetches account name, load characters, then it says Done! Right after that i get an error message ( Error getting items for league , are you sure your league settings are correct?) and it crashes telling me to submit a ticket.  I don't know how to check my league settings when i haven't even been able to log onto procurement yet to change the settings.  I found this thru a youtube video guide and this will be my first time using the program.  Thank you

**Comment by Stickymaddness** [comment]
Are you a steam user? Have you tried logging in using sessionID?
