### ISSUE TITLE
Can't log into Version 1.10.0

### ISSUE THREAD

**Issue by zzzileaN** [Stickymaddness/Procurement#630]
[08-10-2016 20:12] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Procurement.ViewModel.StashViewModel.getAvailableItems()

[08-10-2016 20:12] Application Version: Procurement 1.10.0
[08-10-2016 20:12] 
CurrentCulture: de-DE
CurrentUICulture: de-DE
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[08-10-2016 20:12] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   bei Procurement.View.InventoryView..ctor()
   bei Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08-10-2016 20:17] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Procurement.ViewModel.StashViewModel.getAvailableItems()

[08-10-2016 20:17] Application Version: Procurement 1.10.0
[08-10-2016 20:17] 
CurrentCulture: de-DE
CurrentUICulture: de-DE
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[08-10-2016 20:17] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   bei Procurement.View.InventoryView..ctor()
   bei Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08-10-2016 20:28] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Procurement.ViewModel.StashViewModel.getAvailableItems()

[08-10-2016 20:28] Application Version: Procurement 1.10.0
[08-10-2016 20:28] 
CurrentCulture: de-DE
CurrentUICulture: de-DE
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[08-10-2016 20:28] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   bei Procurement.View.InventoryView..ctor()
   bei Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08-10-2016 20:29] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Procurement.ViewModel.StashViewModel.getAvailableItems()

[08-10-2016 20:29] Application Version: Procurement 1.10.0
[08-10-2016 20:29] 
CurrentCulture: de-DE
CurrentUICulture: de-DE
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[08-10-2016 20:29] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   bei Procurement.View.InventoryView..ctor()
   bei Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[08-10-2016 20:33] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()
[08-10-2016 20:35] System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.
   bei Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()
[08-10-2016 20:37] Error downloading account name, exception details: System.Net.WebException: Timeout für Vorgang überschritten
   bei System.Net.HttpWebRequest.GetResponse()
   bei POEApi.Transport.HttpTransport.GetAccountName()
   bei POEApi.Model.POEModel.GetAccountName()
[08-10-2016 20:37] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetAccountName()
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()

**Comment by zzzileaN** [comment]
it keeps bringing up the following:

[Error] No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.

**Comment by Stickymaddness** [comment]
A new version of Procurement has been released, please retest and open a new ticket if you have further issues:

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
