### ISSUE TITLE
Unhandled Error.

### ISSUE THREAD

**Issue by alorg** [Stickymaddness/Procurement#634]
Hi I have recently downloaded your 1.10 version and I can not use it. I had been using 1.9.9 and everything woked fine. 

This is the message I recieved after all the images were loaded:

"There was an unhandled error - Sorry! Please create a ticket on github http://github.com/stickymaddness/Procurement/issues. If the crash occured after Procurement was done downloading, zip & include your .tab files."
and then it just closes.

I am running Windows XP as the O/S.

I have zipped the whole Procurement folder, as I could not find  the above mentioned *.tab file"

[Procurement.zip](https://github.com/Stickymaddness/Procurement/files/537326/Procurement.zip)

Any assistance would be highly appreciated.

**Comment by Stickymaddness** [comment]
Thanks for your .bin files, Procurement 1.11.0 has been released which should sort your issue: 

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
