### ISSUE TITLE
error downloading stash

### ISSUE THREAD

**Issue by lokiloni** [Stickymaddness/Procurement#636]
cant load stash. this problem start from today, 
was able to use procurement smoothly days before. ur help would be appreciated

[Debug.info.docx](https://github.com/Stickymaddness/Procurement/files/548361/Debug.info.docx)

**Comment by Stickymaddness** [comment]
A new version of Procurement has been released, please retest and open a new ticket if you have further issues:

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
