### ISSUE TITLE
Feature Suggestion! 

### ISSUE THREAD

**Issue by potasium56** [Stickymaddness/Procurement#638]
Hey man, would it be hard to make it so procurement shows how long an item has been listed on poe.trade, would make life easier.. well at least for me after more then 2 months I either delete items or change there price and adding this to procurement would save me the time for individually searching my item on poe.trade unless there is another quick way of seeing all the items on poe.trade at once...

**Comment by Stickymaddness** [comment]
There isn't anything exactly like this, but when you set a buyout on an item, there's a button for timestamp. You can use this to track when you priced an item and check how long ago it was priced.
