### ISSUE TITLE
Unhandled Error when mousing over Fishing Rod in stash

### ISSUE THREAD

**Issue by Ovenchips** [Stickymaddness/Procurement#64]
When mousing over a rare corrupted fishing rod with 4 link B-R-W-R socket setup in my stash, an Unhandled Error message pops up instantly and crashes out Procurement. Can supply more info/details if needed.

**Comment by Stickymaddness** [comment]
This has, finally, been fixed in [Procurement 1.24.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.2)
