### ISSUE TITLE
Not Online On Poe.trade But Procurement is Opened?

### ISSUE THREAD

**Issue by potasium56** [Stickymaddness/Procurement#641]
for sum reason when i search my items using poe.trade thread id search i have to click offline players in order to see my items.....which is werid because i have procurement opened and have everything setup right in the settings... this is probably why im not making sales today at all...usually make at least 5 sales min everytime i bump my shop thread. not sure if this is because of the new release of procurment or poe.trade issues but if you all know how to fix this let me know thanks...

**Comment by Stickymaddness** [comment]
This has been fixed in the new version of Procurement:

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
