### ISSUE TITLE
Procuremente ERRO

### ISSUE THREAD

**Issue by ggdtec** [Stickymaddness/Procurement#642]
Segue  abaixo o log de erro conforme solicitado!

[02-12-2016 15:26] Error downloading stash for Standard, exception details: System.Net.WebException: O tempo limite da operação foi atingido
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   em POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   em POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   em POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   em POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   em POEApi.Model.POEModel.GetStash(String league, String accountName)
[02-12-2016 15:26] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetStash(String league, String accountName)
   em Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   em Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Procurement 1.11.0 has been released, please retest and open a new ticket if you have any further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
