### ISSUE TITLE
support for multiple forum threads in one league

### ISSUE THREAD

**Issue by c2pdev** [Stickymaddness/Procurement#65]
I have problem with multiple shops since there is char limit in forum thread I was forced to make more than one shop in the same league, but updating and bumping those posts via procurement is a pain now because I can save only one forum id there. It would be good to be able to save multiple forum threads to make the process easier. Is there any chance to add that function?

**Comment by Stickymaddness** [comment]
I'll add this when I can, I'll set it up so that each shop can have its own template and url to bump/update.

**Comment by lekne** [comment]
This issue seems to be open. Just reminding. This is a very important feature for me.

**Comment by shankapotimusrex** [comment]
I have worked around this issue by making copies of the whole procurement folder...each with its own template/ID. The only bug with this work-around is that the "online status" feature no longer works.

**Comment by Stickymaddness** [comment]
Is there still demand for this?
