### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by livejamie** [Stickymaddness/Procurement#652]
Put in my login and nothing happens

Aquisition works just fine

**Comment by aydjay** [comment]
Close this - not enough info.

**Comment by livejamie** [comment]
What other information can I provide? I've tried it on multiple computers.

**Comment by aydjay** [comment]
Are you using your poe session id as described in the wiki: https://code.google.com/archive/p/procurement/wikis/LoginWithSessionID.wiki

Otherwise post your DebugInfo.log which in in the installation directory.

**Comment by Stickymaddness** [comment]
Procurement 1.11.0 has been released, please retest and open a new ticket if you have any further issues.

https://github.com/Stickymaddness/Procurement/releases/tag/1.11.0
