### ISSUE TITLE
[Error] Downloading stash for Bloodlines

### ISSUE THREAD

**Issue by Gekiro** [Stickymaddness/Procurement#66]
"[Error] Downloading stash for Bloodlines, details logged to DebugLog.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues"
Can't find any file called DebugLog.log, but there's a file called DebugInfo.log :

System.Exception: No characters found in the leagues specified. Check spelling or try setting DownloadOnlyMyLeagues to false in settings.

**Comment by Stickymaddness** [comment]
The error is that Procurement can't find any characters in your league, are you a steam user? Often steam users need to ask GGG support to associate their email address with their steam account (if using email to login) 

Have you tried sessionID?
