### ISSUE TITLE
Question marks everywhere

### ISSUE THREAD

**Issue by Thirsk** [Stickymaddness/Procurement#660]
Every place where there's a space in the template a question mark appears instead. I haven't noticed this with any other thread created by Procurement, and I can't figure out why it's happening. 
Currently I need to manually remove the question marks from the forum export section every time. 
![capture](https://cloud.githubusercontent.com/assets/16472201/21544835/69146efe-cd87-11e6-96f4-58f08ea330fe.PNG)

**Comment by Stickymaddness** [comment]
The spacing in the template is ASCII character 255, so it looks like a space but actually spaces out the test on the forum.

If you edit your forum template and remove the spaces, when your thread is created it will no longer have the question marks.
