### ISSUE TITLE
SSL connection on XP fails in WebClient

### ISSUE THREAD

**Issue by bsun0000** [Stickymaddness/Procurement#661]
I tried to run this program on XP and got this error:

> ---------------------------
> There was an unhandled error - Sorry! Please create a ticket on github https://github.com/Stickymaddness/Procurement/issues. If the crash occured after Procurement was done downloading, zip and include your .tab files.
> ---------------------------

After spending a half of hour by looking in source codes & debugging, i found this error:
EN:
> [02-01-2017 11:21] WebException in CachedTransport.GetImage: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

RU:
> [02-01-2017 11:21] WebException in CachedTransport.GetImage: Базовое соединение закрыто: Не удалось установить доверительные отношения для защищенного канала SSL/TLS.

I'm not a .NET programmer, but can you fix it somehow? Or just replace http**s** with http scheme, for image loading - it works for me.

POEApi.Transport\HttpTransport.cs
GetImage function, row 168:

return new MemoryStream(client.DownloadData(**url.Replace("https://", "http://")**));

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0) and create a new ticket if this is still an issue.
