### ISSUE TITLE
Compact Mode = System Window

### ISSUE THREAD

**Issue by livejamie** [Stickymaddness/Procurement#665]
Procurement is awesome but I'd like to have it take less screen real estate, the giant POE logo at the top and the decorations around the window don't fit well on my second monitor which is small.

The compact mode is great it would be awesome if it was just like any other system window so I could resize it and it would work with window managers and it was rectangular sized.

Thanks so much for everything you do.

**Comment by Stickymaddness** [comment]
Hi have you tried enabling compact and minimalist mode?

**Comment by livejamie** [comment]
I've enabled compact mode, I mentioned that in the original bug. :)

I'm not sure what minimalist mode is.

Here's an example of what it looks like on my monitor:

![image](https://cloud.githubusercontent.com/assets/49513/23631890/8d234b20-0285-11e7-9197-d3c044cebbc9.png)

Here's Acquisition in the same spot: http://i.imgur.com/1yTAunY.png
Here's Looty in the same spot: http://i.imgur.com/kuWZHTH.png

**Comment by aydjay** [comment]
Proposing a won't fix as the way procurement is built at the moment having a correctly resizing window is a complete bastard.

**Comment by Stickymaddness** [comment]
Resizable is not possible due to stash etc being a fixed size.

Closest Procurement can offer is MinimalMode, sorry!
