### ISSUE TITLE
Procurement skipping stash tab 2

### ISSUE THREAD

**Issue by chisero** [Stickymaddness/Procurement#666]
After a while this started happen and now if i want to pose in the forums i need to correct all the stash numbers and it takes forever i did re install POE and Procurement and the problem is still there 

![capture](https://cloud.githubusercontent.com/assets/25773513/22936823/8eb4fafe-f2ce-11e6-8069-74a0091bce91.PNG)

![2](https://cloud.githubusercontent.com/assets/25773513/22936824/8eb7f43e-f2ce-11e6-8280-e91cbbd56b7f.PNG)

**Comment by aydjay** [comment]
I'm also experiencing this stash tab skipping issue - in my case it appeared to be stash tab 2 and 3 it skipped.

**Comment by Stickymaddness** [comment]
@aydjay This was introduced around the time of hideouts being added to PoE, if I recall correctly the first tab in a players stash was duplicated and I had to build something in to handle this, GGG have probably changed this behavior yet again.

**Comment by chisero** [comment]
Is there any solution please :)

**Comment by aydjay** [comment]
Looks fixed to me.
