### ISSUE TITLE
[Feature Req] Support for periodically and automagically updating threads

### ISSUE THREAD

**Issue by Koveras** [Stickymaddness/Procurement#67]
And please introduce a minimum timelimit, i.e. every  60 minutes, I wouldn't want GGG to disallow this due to server load.
Also, if you implement the multiple shop threads support, let us choose which threads to update automagically.
Thanks :)

**Comment by Stickymaddness** [comment]
I do plan on implementing multiple shop threads, and will take a look into automatically updating threads as well.

**Comment by Stickymaddness** [comment]
GGG have said API improvements are coming "soon" for how items are posted and shops updated, I'm going to see what they come up with and hopefully work that into Procurement automatically updating and post items.
