### ISSUE TITLE
[Error] Incorrect session id

### ISSUE THREAD

**Issue by Needfacelift** [Stickymaddness/Procurement#670]
Keep getting this error everytime. I edited the settings to allow session ID (set value to True) Is there something i've missed i followed the wiki on it. Iam using chrome i exited out of all of it and brought up new tab logged in hit f12 did all that same error.

**Comment by GlazShot** [comment]
same here need a fix

**Comment by Stickymaddness** [comment]
Make sure there isn't a trailing space at the end of the sessionID, sometimes it will copy over from the browser with a space at the end.

**Comment by Needfacelift** [comment]
Ok i tried that same error i deleted the last one and the first just to be safe 1 at a time.

**Comment by Needfacelift** [comment]
Here's the debuginfo. Its that over and over

POEApi.Infrastructure.LogonFailedException: Incorrect session id
   at POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   at POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   at Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()POEApi.Infrastructure.LogonFailedException: Incorrect session id

**Comment by Needfacelift** [comment]
Also i am using steam to play Poe would it be better to just download the poe client? WOuld Procurement work better that way?

**Comment by Needfacelift** [comment]
Ok so i uninstalled everything redownloaded it all now iam getting this.

Procurement 1.11.0 Initialized.
                                                          
Authenticating Bishop                                                                     [OK]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Legacy Stash Tab 1...                                                             [OK]
Loading Legacy Stash Tab 2...                                                             [OK]
Loading Legacy Stash Tab 3...                                                             [OK]
Loading Legacy Stash Tab 4...                                                             [OK]
Loading Legacy Stash Tab 5...                                                             [OK]
Loading Needfacelift's inventory...                                                       

[Error] Error reading character data for Needfacelift, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Needfacelift** [comment]
Ok.... fixed it i copied session id from chrome pasted it on to a notepad copied it from there then pasted it back into procurement session id logged in no problem.

**Comment by aydjay** [comment]
Glad to see you made it in. We can close this ticket now. 👍
