### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by Vladeh** [Stickymaddness/Procurement#678]
Can't get pass this.

[Error] Error reading character data for Vladeeh, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by archanist123** [comment]
Bump

**Comment by alin-faur** [comment]
Try logging to a standard char then log in again with the legacy char, then try again with procurement.

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
