### ISSUE TITLE
Leaguestones don't get updated to forum thread.

### ISSUE THREAD

**Issue by Zibokwe** [Stickymaddness/Procurement#680]
Leaguestones are not supported, they don't appear in any category when you price them.

**Comment by aydjay** [comment]
You are correct. I have fixed this issue. Thanks for the report.

See:
https://www.pathofexile.com/forum/view-thread/1866871

Fix in #684

**Comment by Stickymaddness** [comment]
This has finally been released as part of Procurement 1.12.0
