### ISSUE TITLE
Error downloading stash tab

### ISSUE THREAD

**Issue by casmiel** [Stickymaddness/Procurement#686]
bei System.Threading.Tasks.Task.Execute()System.Runtime.Serialization.SerializationException: Status "Element" wird erwartet.. Gefunden: "Text" mit dem Namen "", Namespace "". 
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   bei ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   bei System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   bei System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   bei System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   bei System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   bei System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)JSON Serialization Failed: base64 bytes:ZmFsc2U=ENDSystem.Exception: Downloading stash, details logged to DebugLog.log, please open a ticket at https://code.google.com/p/procurement/issues/list
   bei POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   bei POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   bei POEApi.Model.POEModel.GetStash(String league)
   bei Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   bei Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   bei System.Threading.Tasks.Task.Execute()

First time user, thank you for your hard work!

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0) and create a new ticket if this is still an issue.
