### ISSUE TITLE
ERROR on 1.9

### ISSUE THREAD

**Issue by Noltop** [Stickymaddness/Procurement#69]
Im getting an error on launch: [Error] Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues

Pastebin of Debuginfo: http://pastebin.com/18yVPAgV

**Comment by Stickymaddness** [comment]
The issue is that the GGG servers aren't returning any data for hardcore for you. Are you a new/steam user? Often steam users either need to ask GGG to associate their email address with their account in order to login with email/password, or login with sessionID.

**Comment by Noltop** [comment]
I log in using session ID. I had no problems with the previous version. I have no characters on hardcore, is that the problem?

**Comment by Noltop** [comment]
UPDATE SOLVED: So i made a character on bloodlines and put an item into the inventory and that didnt help but i did have a char from a hardcore race that i hadnt logged into since that race so i logged onto it and added something to the stash and the error went away.

**Comment by Stickymaddness** [comment]
Of course, that makes sense. Race characters that haven't been used in a while can cause issues. Glad you got it sorted!
