### ISSUE TITLE
Error Downloading Stash

### ISSUE THREAD

**Issue by idSmoker** [Stickymaddness/Procurement#695]
Great work on the application!

Hope this helps with your debugging.

[DebugInfo.zip](https://github.com/Stickymaddness/Procurement/files/998239/DebugInfo.zip)

**Comment by Stickymaddness** [comment]
Are you still experiencing this issue? From the debuglog I can see that GGG returned empty data when Procurement asked for your items.

**Comment by idSmoker** [comment]
No, it seems to have been a one-time occurrence for me.
