### ISSUE TITLE
[Error] Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

### ISSUE THREAD

**Issue by deatheater94** [Stickymaddness/Procurement#696]
[Error] Downloading stash for Hardcore, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.

Please help me. Thank you

[DebugInfo.zip](https://github.com/Stickymaddness/Procurement/files/1016822/DebugInfo.zip)

**Comment by Stickymaddness** [comment]
Have you used Procurement before? Are you logging in with sessionID or email?

The error is that the GGG servers came back with no data when Procurement asked for your items.
