### ISSUE TITLE
Procurement AppVeyor integration

### ISSUE THREAD

**Issue by Stickymaddness** [Stickymaddness/Procurement#698]
I've added appveyor integration to Procurement to add build and deployment automation.

This is **long overdue**, previously changes would often not be released until I got around to making changes of my own and creating a release manually. 

My intent with this addition is to deploy as soon as PRs are merged so that changes are released immediately instead of months later.

Tagging in recent contributors, @aydjay @CrossCRS

**Comment by aydjay** [comment]
This will be great 👍

**Comment by aydjay** [comment]
Adding on to this - might be really nice to have HockeyApp integration for error reporting. I had a little stab at it and it looked simple enough.
