### ISSUE TITLE
Multiple Leagues

### ISSUE THREAD

**Issue by PaulNations** [Stickymaddness/Procurement#70]
I'm having a problem when I switch leagues, sometimes the trade settings for that league switch and sometimes they don't.  Many times when I look at the Forum Export tab and it's saying Torment league then I switch back to the Stash tab it's displaying the Standard league stash.  This is with the latest update.

Another item, when I updated the program it should pick up the trade settings from before.

Thanks for a great program.

**Comment by Stickymaddness** [comment]
Which settings specifically change when you switch leagues?

Usually it does keep your settings,the last release was an exception since the format of the settings file changed.

**Comment by PaulNations** [comment]
I log in to my default Torment league and switch over to the Trading tab, update my forum thread, then switch back to the Stash tab.  

I change leagues to Standard in the league selector dropdown and switch over to the Trading tab and update that forum thread.  

Then switch back to the Stash tab and the league selector reads Torment, but the Trading tab is still pointing to the Standard league forum thread and the Stash tab is displaying Standard league loot.

So, I have to bump the league selector back to Standard (it's displaying Standard in the Stash tab window and Standard in the Trading tab, but Torment in the selector dropdown) and finally switch it to Torment.

This dance usually works, but at times I've had to completely close and reopen Procurement.

And thanks for the info on the settings.
