### ISSUE TITLE
[Error] Downloading stash

### ISSUE THREAD

**Issue by zappyle** [Stickymaddness/Procurement#701]
Hi,

First time using Procurement and I got the following error: Downloading stash

with the log that follows:

> System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.HttpWebRequest.GetResponse()
   à POEApi.Transport.HttpTransport.GetCharacters()
   à POEApi.Transport.CachedTransport.GetCharacters()
   à POEApi.Model.POEModel.GetCharacters()
   à Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()System.Exception: Failed to load characters
   à Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)JSON Serialization Failed: base64 bytes:ZmFsc2U=ENDSystem.Exception: Downloading stash, details logged to DebugLog.log, please open a ticket at https://code.google.com/p/procurement/issues/list
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league)
   à Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)JSON Serialization Failed: base64 bytes:ZmFsc2U=ENDSystem.Exception: Downloading stash, details logged to DebugLog.log, please open a ticket at https://code.google.com/p/procurement/issues/list
   à POEApi.Model.POEModel.logNullStash(Stream stream, String errorPrefix)
   à POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   à POEApi.Model.POEModel.GetStash(String league)
   à Procurement.ViewModel.LoginWindowViewModel.loadStash(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

> 

I couldnt find any fix, is there something im missing? Thanks everyone :)

**Comment by aydjay** [comment]
Looks like you have a connection timeout to the servers.

Open the application directory and zip up any bin files you have - these are the files that are downloaded from the poe api. If you don't have any bin files you are not connecting properly.

**Comment by zappyle** [comment]
I do not see any BIN files, this is what I can see (plus empty common/account folder)

![image](https://user-images.githubusercontent.com/14113129/27698680-cfc2888e-5cc5-11e7-9b6d-c8abbcf78896.png)

How can I connect properly? Thanks

**Comment by zappyle** [comment]
Also, the first error happens when DownloadOnlyMyCharacter is set to true
When it is set to false, I have the following error: Error reading character data

> System.Runtime.Serialization.SerializationException: État attendu 'Element'.. Détection de 'Text' avec le nom '', espace de noms ''. 
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.HandleMemberNotFound(XmlReaderDelegator xmlReader, ExtensionDataObject extensionData, Int32 memberIndex)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetJsonMemberIndex(XmlReaderDelegator xmlReader, XmlDictionaryString[] memberNames, Int32 memberIndex, ExtensionDataObject extensionData)
   à ReadRootObjectFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   à System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   à System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   à System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   à System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   à System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   à System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   à POEApi.Model.POEModel.GetInventory(String characterName)System.Exception: Error reading character data for Zappyle, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   à POEApi.Model.POEModel.GetInventory(String characterName)
   à Procurement.ViewModel.LoginWindowViewModel.loadCharacterInventory(Character character)
   à Procurement.ViewModel.LoginWindowViewModel.<Login>b__1()
   à System.Threading.Tasks.Task.Execute()

**Comment by zappyle** [comment]
Welp, I just deleted everything and downloaded again, now it works!

**Comment by aydjay** [comment]
Great to see you are up and running - please close this issue :)
