### ISSUE TITLE
Expired Name Error

### ISSUE THREAD

**Issue by delta50** [Stickymaddness/Procurement#704]
Characters with an expired name cause the following exception to be thrown:

`Error reading character data for <CharacterName>, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.`

**Comment by Stickymaddness** [comment]
This should be fixed in  to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)
