### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by Kilsaber** [Stickymaddness/Procurement#709]
I can't seem to login into procurement getting this error: [Error] Error reading character data for Kilsaber, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by delta50** [comment]
If you have a character with an expired name you will get this error. If that's the case you can log into the expired characters and give them a new name to fix the problem.

**Comment by SabreCat** [comment]
Running into this myself, and for a current character--nothing expired. Using session ID login.

**Comment by alsocoder** [comment]
same shit

**Comment by SabreCat** [comment]
Still doing this to me on 1.16.0.

**Comment by Ciapciaq** [comment]
I have same problem. Load all to point "Loading TryDuelMyFists's inventory... " 
Then Error reading character data for TryDuelMyFists, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

I log in with sesion id and forum account name. Both correct. Sesion was fresh. 1.16.0 version. 

Btw i hear is and option to go around and don't load Character data, or do it manualy. I have do that (have this wall of text) but idk what is the next step.

**Comment by evilight** [comment]
what's the option to go around and don't load Character data

**Comment by driz** [comment]
empty list MyCharacters - DownloadOnlyMyCharacters=True

**Comment by aydjay** [comment]
In the application installation folder there will be a folder with your profile name on it. Inside there will be a load of bin files. Can you please zip up the bin files for me and I will try and replicate and resolve this issue.

**Comment by SabreCat** [comment]
Hah, I went back to retry it and it worked. So never mind on my end!

**Comment by Stickymaddness** [comment]
If this is still an issue, update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0) and create a new ticket if there are further issues.
