### ISSUE TITLE
1.15.0 Doesnot update online status

### ISSUE THREAD

**Issue by LepuavkoDV** [Stickymaddness/Procurement#713]
title says enough. but as i can see, earlier versions had some alert like "poe.trade settings saved", but for now clicking Save poe.trade settings seems does nothing

**Comment by byrzd** [comment]
i am getting this aswell

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0), and create a new ticket if this is still an issue.
