### ISSUE TITLE
Could not find a part of the path '...\characterdata.bin'

### ISSUE THREAD

**Issue by idSmoker** [Stickymaddness/Procurement#715]
I was able to get Procurement 1.16 to run once and log in successfully, but every time I start it after that gets the error in the title.

[DebugInfo.zip](https://github.com/Stickymaddness/Procurement/files/1219350/DebugInfo.zip)

**Comment by Stickymaddness** [comment]
There should be a folder with your email address or alias, delete that and rerun Procurement.

**Comment by aydjay** [comment]
Can you attach the bin files that are in the application directory under you username. Thanks,

**Comment by idSmoker** [comment]
Deleting the folder allows me to start the cycle again... Procurement runs successfully once, but after exiting and re-running, I get the same error.  The log I attached was captured after the 2nd unsuccessful run.

Here's what the user directory looks like after the first successful run of the cycle.
[my email address.zip](https://github.com/Stickymaddness/Procurement/files/1219886/my.email.address.zip)

That folder gets deleted during the 2nd, error'd run of the cycle.

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
