### ISSUE TITLE
sessionID with Steam issue ?

### ISSUE THREAD

**Issue by Mycose** [Stickymaddness/Procurement#716]
I'm having an issue with while login with the session id with my POE steam account...

Authenticating Mycose                                                                     [OK]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Harbinger Stash Tab 1...                                                          [OK]
Loading Harbinger Stash Tab 2...                                                          [OK]
Loading Harbinger Stash Tab 3...                                                          [OK]
Loading Harbinger Stash Tab 4...                                                          [OK]
Loading Harbinger Stash Tab 5...                                                          [OK]
Loading xMycose's inventory...                                                            

[Error] Error reading character data for xMycose, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

Everything is okay except when it arrives to check my inventory ?

am i doing something wrong ?

**Comment by dallbee** [comment]
Experiencing the same issue.

**Comment by boyanov83** [comment]
same issue, why is this still open without a comment from a dev for 12 days ? am i wrong to expect help from here

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
