### ISSUE TITLE
Acess denied to game folder

### ISSUE THREAD

**Issue by ShadowErrant** [Stickymaddness/Procurement#719]
I'm getting a problems with the access to me game folder in documents. I'm running the program as an admin so I'm not sure what's causing the problem.
The error happens after the program has already authenticated the mail and loaded the stashes and starts loading the images of currency.

EDIT : I found a similar problem in the forum post here https://www.pathofexile.com/forum/view-thread/172710/page/121
And I tried doing what the article said (modifying the machinekeys). After that it loaded more images but it still gave me the error in the end. So I'm not sure what to do now.

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
