### ISSUE TITLE
My shop doesnt get updated

### ISSUE THREAD

**Issue by vRawon** [Stickymaddness/Procurement#72]
wrote this on your PoE forum post:" Hey! I dont know what happens with my procurement, but I have some items for ~3 days and they are not on poe.trade nor on my shop post, and also there are prices wich I changed many days ago and also are not updated, is there something I can do?(when i click the update icon its does all as" ok")

Regards!"

just checked again, and my PoE shop shows a pair of Rainbowstrides that I sold about 5 days ago!

e/, just looked, on my post says: "Welcome to my shop! (Last Updated Tuesday, January 13, 2015 11:54 PM)," and i have uptaded my shop at least 1 time per day, on my procurement i can see how it says is going to update to the current day/hour, and always get the message "Your shop was succesfully updated!" O_O

e2/ Now the shop got updated, but clicked button at 2:22, and updated the prices i got at 2:12 O_O
e3/ Changed a random price, clicked again to update, and got updated at 2:24, now all prices/items are ok on the forum.

**Comment by Stickymaddness** [comment]
Hey there,

Is your shop updating correctly now, or are you still having issues?

**Comment by vRawon** [comment]
Solved! Found the mistake when tried to update manually...was because Procurement was not 100%refreshed, so when it tried to copy the lanes on the forum, this should make any error because any item was not where procurement thoughs.

This makes me create a suggestion, maybe you can do something on Procurement so it refreshed all tabs is going to update before doing it :)

Thanks!!

**Comment by Stickymaddness** [comment]
That makes sense, glad you got it sorted.

Updating all tabs is something I've wanted to add for a while, and I'm going to try add in a near release.

**Comment by vRawon** [comment]
thanks for your work :dancer:
