### ISSUE TITLE
Error reading character data

### ISSUE THREAD

**Issue by psnstyle** [Stickymaddness/Procurement#725]
[Error] Error reading character data for ####, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
