### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by boyanov83** [Stickymaddness/Procurement#727]
[DebugInfo - Copy.txt](https://github.com/Stickymaddness/Procurement/files/1248739/DebugInfo.-.Copy.txt)

first of all in the error the client gave me after i failed to connect you tell me to upload a .log file here and GITHUB DOESNT SUPPORT THAT UPLOAD. im uploading a txt version of it. i woke up on 24.08 and couldnt connect. prior to that ive had a lot of issues with procurement including very late updating (more than  3 hours) and multiple listings (the most i saw was 7) of the same item. poe.trade claim this is procurements fault and not their own.

**Comment by aydjay** [comment]
Please attach your bin files which are under your account name in the application directory.

**Comment by boyanov83** [comment]
i see those have my email so do they also have my password ? if they do i can send them to you directly but not upload them here openly for obvious reasons

**Comment by Stickymaddness** [comment]
For future reference, the bin files do not have your password - it is only stored in the config file with a machine specific hash. The bin files are plaintext, so you can always open them with notepad or other editor if you want to see their contents.
