### ISSUE TITLE
Default interface

### ISSUE THREAD

**Issue by LepuavkoDV** [Stickymaddness/Procurement#729]
Hello! First of all thanks for your application. Ok so i was wondering if its possible to get procurement application without that tricky graphics interface? just default looking windows application instead custom grapics. But stash interface leave as it is.
Is it possible?

**Comment by aydjay** [comment]
Not possible sorry.

**Comment by Stickymaddness** [comment]
Under settings there's an option for minimalist mode, enable that and restart Procurement.
