### ISSUE TITLE
Certain tabs not updating code

### ISSUE THREAD

**Issue by Airtaz** [Stickymaddness/Procurement#73]
When I make any buyouts, either single buyouts or tab buyouts, the code under the trading tab does not update... it remains the default. This only occurs for tab 10 and 11.

I've tried renaming tabs back and forth and it doesn't seem to do any different.

**Comment by Airtaz** [comment]
I did more experimenting... I removed all tab buyouts. I then selected 1 item under each tab and priced it in chaos to match the tab number. For example, Tab 1, I priced 1 item buyout for 1 chaos... tab 2, priced 1 item for 2 chaos.... and so on. (btw, when I right clicked on tabs 14 and 15 to set a tab buyout, I received an error that mentioned to come here and post the issue).  

Here's the results of the single item buyouts in the Trading tab code:

Tab - Chaos (they should equal each other and show up)
1 - 1
2 - nothing changed
3 - 3
4 - 4
5 - 5
6 - nothing changed
7 - nothing changed
8-8 
9 - 9
10 - nothing changed
11 - nothing changed
12 - 12
13 - 13
14 - nothing changed
15 - 15

**Comment by Airtaz** [comment]
I moved everything from that tab to another, and the other to this tab. Now, the tab works... but the other isn't.  This appears to be related to the items.  I'm trying to set up a crafting tab that has only craftable items... would range from normal to magic socketed/linked items.     I placed a rare item in the middle of the items and that showed, just not the normal-magic items.

**Comment by Stickymaddness** [comment]
Hi there,

Can you paste what's in your debug file, it's possible that your tabs that you're setting buyout out that aren't working are due to a silent error.

It's unusual that it works or some tabs but not others though, is there somewhere you can zip and upload your .bin files? That way I can load up your items and track down the issue.

**Comment by Airtaz** [comment]
It's working... And it's kind of fun tbh.  The problem was the normal items. I was wanting to make a crafting type of tab using socketed items.  It discusses it in the wiki, but I feel I had to kind of guess at what to do.  The way it's written I think expects the use to be an experienced user and not new to the program.   Regardless, it appears you be working.   Thanks!

**Comment by Stickymaddness** [comment]
The documentation is currently a bit lacking and out of date, I want to put up to date documentation on github and maybe include a guide in the zip.

Glad you got it sorted!
