### ISSUE TITLE
error downloding name

### ISSUE THREAD

**Issue by Zoologe** [Stickymaddness/Procurement#730]
System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetAccountName()
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
