### ISSUE TITLE
SessionID giving Error

### ISSUE THREAD

**Issue by Seforian** [Stickymaddness/Procurement#732]
[Error] Error reading character data for %%%, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

Can not test e-mail login, as I'm connecting into Forums / Game using Steam. SessionID is only option.

Looks to be Known Issue since the release of the latest.

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.
