### ISSUE TITLE
Currency breakdown calculates currency incorrectly by a huge margin

### ISSUE THREAD

**Issue by tails11** [Stickymaddness/Procurement#733]
It inflates chaos number by about 30%
(set all currency values to 0.1 relative to chaos for more clear example.)
![2017-09-03 16_29_51-procurement 1 16 0](https://user-images.githubusercontent.com/10291326/30003433-802c1f86-90c5-11e7-8c05-c35b97d2974c.png)

**Comment by aydjay** [comment]
Open your settings XML in the application folder and adjust the ratios at the top of the file. You should get a more sensible breakdown.
