### ISSUE TITLE
Mangled white jewelry tab

### ISSUE THREAD

**Issue by SabreCat** [Stickymaddness/Procurement#734]
I've got a tab called "1x1" where I dump jewelry items for crafting. When loaded in Procurement, it looks like a hot mess:

![image](https://user-images.githubusercontent.com/4501321/30182924-240e2b6a-93de-11e7-976f-aae66d2b4c68.png)

**Comment by aydjay** [comment]
Is this a quad tab by any chance?

**Comment by SabreCat** [comment]
It is not! Premium tab yes, but not a quad.

**Comment by Stickymaddness** [comment]
This may be related to PR #718

**Comment by SabreCat** [comment]
Aha, quite likely. "Loot" before that tab is a quad.
