### ISSUE TITLE
Essences do not display correctly

### ISSUE THREAD

**Issue by SabreCat** [Stickymaddness/Procurement#735]
I have a premium Essence tab with a modest variety of Essences in it. However, only a tiny few actually appear in Procurement:

![image](https://user-images.githubusercontent.com/4501321/30182971-52ed1784-93de-11e7-99eb-25af91eac973.png)

**Comment by aydjay** [comment]
Premium Essence tabs are not handled correctly - this is in the same vain to currency tabs.

See #609 for further info.

**Comment by aydjay** [comment]
Closed by #752
