### ISSUE TITLE
Unable to cast object of type when downloading inventory

### ISSUE THREAD

**Issue by lythix** [Stickymaddness/Procurement#737]
[DebugInfo.zip](https://github.com/Stickymaddness/Procurement/files/1290305/DebugInfo.zip)

**Comment by aydjay** [comment]
In the application installation folder there will be a folder with your profile name on it. Inside there will be a load of bin files. Can you please zip up the bin files for me and I will try and replicate and resolve this issue.

**Comment by lythix** [comment]
Cool, miss it. There's nothing in the folder that can reveal my account right? Especially passwords
[procurement.zip](https://github.com/Stickymaddness/Procurement/files/1290701/procurement.zip)

**Comment by aydjay** [comment]
#738 should fix you @lythix.

Please pull it and try it both online and offline.

**Comment by lythix** [comment]
Hmm, no go. Pulled your branch from your repo and tried it. Will debug it later and see if I can see what's going on but it still had some issues when in online mode.

**Comment by aydjay** [comment]
My hunch is it has something to do with characters Mortrend and Messycrime scene.

If you could look at the GetCharacters when in online mode you may see that there are extra properties which are important but we are ommiting.

**Comment by lythix** [comment]
It doesn't like charges...


[cid:af6f43db-cd20-4c7d-963f-fcae064e9a49]


It hit that much earlier than first try, so it probably just ignores this one...

________________________________

**Comment by aydjay** [comment]
Have a look at proxymapper.cs in: https://github.com/Stickymaddness/Procurement/pull/738/commits/c8baf141e7af87c7218214fe982cbb5b7ec8b573

Bear in mind that this isn't the end off the world as it will log an exception and give you a stack size of 1/1

**Comment by aydjay** [comment]
Can you try again with the latest version please

**Comment by lythix** [comment]
Will do. Sorry have been crazy busy. Will report back how it goes. Thanks!

**Comment by Stickymaddness** [comment]
Please test with [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0), and create a new ticket if this is still an issue.
