### ISSUE TITLE
No Offering to the Goddess

### ISSUE THREAD

**Issue by byrzd** [Stickymaddness/Procurement#739]
Hey,i can see the "Offering to the Goddess" on Procurement stash tab but can't see it on the forum thread.Bumped it,updated it and restarted the Procurement several times.

**Comment by aydjay** [comment]
Sounds like there isn't an appropriate forum "runner" I'll do my best to
get a fix out for this asap

**Comment by byrzd** [comment]
Thank you very much!

**Comment by aydjay** [comment]
I've just realised that i've added support for a divine vessel and not an offering to the godess. Small but important distinction. This issue is not closed with #740 and is still outstanding
