### ISSUE TITLE
Logging problem

### ISSUE THREAD

**Issue by shpend94** [Stickymaddness/Procurement#743]
I'm trying to login with ssid but it gives continuous errors..
[DebugInfo - Copia.txt](https://github.com/Stickymaddness/Procurement/files/1303548/DebugInfo.-.Copia.txt)

**Comment by Stickymaddness** [comment]
Please retest with [1.17.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.17.0)

**Comment by shpend94** [comment]
It works, thanks!
