### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by titania2305** [Stickymaddness/Procurement#750]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1327760/DebugInfo.log)

[titania2305.zip](https://github.com/Stickymaddness/Procurement/files/1327762/titania2305.zip)

Hi I've been using latest Procurement since release day, today i got this error twice and the game crashed. Any solutions?

**Comment by titania2305** [comment]
Correction, Procurement crashed and not the game.

**Comment by aydjay** [comment]
Thanks for the report - what stash tab and league was it that caused this exception?

**Comment by titania2305** [comment]
It was happening when i tried to switch from Harbinger to Standard in the League selection.
