### ISSUE TITLE
Error loading items

### ISSUE THREAD

**Issue by theplastichero** [Stickymaddness/Procurement#751]
I'm signing in with my steam profile and it verifies everything but then I get a error message stating "Error getting items for league, are you sure your settings are correct?" any help would be great, thank you.
Or even how do I go about getting my session id from internet explorer?

**Comment by theplastichero** [comment]
can someone at least explain how to get my session id please

**Comment by aydjay** [comment]
https://code.google.com/archive/p/procurement/wikis/LoginWithSessionID.wiki
