### ISSUE TITLE
Items duplicated

### ISSUE THREAD

**Issue by drigoz** [Stickymaddness/Procurement#755]
I don't know why but my post is duplicating the items.

**Comment by aydjay** [comment]
Going to need a little more detail than that dude.

**Comment by drigoz** [comment]
I updated my procurement yesterday to 1.17 and when a search an item like mine to check the price ( I used TRADEMACRO pressing CRT+ALT +D on my item) I saw that my post are duplicated. 

And I have no ideia why.

http://poe.trade/search/uotobaiyasikoi

![duplicated](https://user-images.githubusercontent.com/32345428/30992273-67242038-a47f-11e7-9623-6d6d05030fd2.png)

**Comment by aydjay** [comment]
I've checked your forum thread and I can only see the steel ring once in the forum post. 

Duplicate items on POE trade don't have anything to do with procurement as they are not linked.
