### ISSUE TITLE
Error loading Account Name

### ISSUE THREAD

**Issue by J0Kuss** [Stickymaddness/Procurement#765]
System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   bei POEApi.Model.POEModel.GetAccountName()
   bei Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   bei System.Threading.Tasks.Task.Execute()

**Comment by aydjay** [comment]
"Include your DebugInfo.log"

**Comment by Stickymaddness** [comment]
Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
