### ISSUE TITLE
[Error] Downloading stash for Abyss

### ISSUE THREAD

**Issue by AndrewKabal** [Stickymaddness/Procurement#769]
[08-12-2017 20:49] System.ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: source
   em System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   em POEApi.Model.Gear..ctor(Item item)
   em POEApi.Model.ItemFactory.Get(Item item)
[08-12-2017 20:49] ItemFactory unable to instantiate type : Bismuth Flask
[08-12-2017 20:49] Error downloading stash for Abyss, exception details: System.ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: source
   em System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   em POEApi.Model.Gear..ctor(Item item)
   em POEApi.Model.ItemFactory.Get(Item item)
   em System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em POEApi.Model.Stash..ctor(Stash proxy)
   em POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   em POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   em POEApi.Model.POEModel.GetStash(String league, String accountName)
[08-12-2017 20:49] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetStash(String league, String accountName)
   em Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   em Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
