### ISSUE TITLE
Procurement loading problem [Abyss] Please help!

### ISSUE THREAD

**Issue by SuperiumIdefinite** [Stickymaddness/Procurement#770]
[09-12-2017 1:18] System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: source
   в System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   в POEApi.Model.Gear..ctor(Item item)
   в POEApi.Model.ItemFactory.Get(Item item)
[09-12-2017 1:18] ItemFactory unable to instantiate type : The Scavenger
[09-12-2017 1:18] Error downloading stash for Standard, exception details: System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: source
   в System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   в POEApi.Model.Gear..ctor(Item item)
   в POEApi.Model.ItemFactory.Get(Item item)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в POEApi.Model.Stash..ctor(Stash proxy)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
[09-12-2017 1:18] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   в System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
