### ISSUE TITLE
 [Error] Downloading stash for SSF Hardcore, details logged to DebugInfo.log, appreciate the help!

### ISSUE THREAD

**Issue by mokbren** [Stickymaddness/Procurement#772]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1544380/DebugInfo.log)

Debug info attached, appreciate the help

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
