### ISSUE TITLE
[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

### ISSUE THREAD

**Issue by R3incower** [Stickymaddness/Procurement#779]
[10-12-2017 10:47] System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: source
   w System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[10-12-2017 10:47] ItemFactory unable to instantiate type : Topaz Ring
[10-12-2017 10:47] Error downloading stash for Standard, exception details: System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: source
   w System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[10-12-2017 10:47] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
