### ISSUE TITLE
[Error] Downloading stash for Abyss

### ISSUE THREAD

**Issue by RafBin** [Stickymaddness/Procurement#780]
Can somebody help me ? 
Procurement 1.17.0 Initialized.
                                                          
Authenticating rafbin4@gmail.com                                                          [OK]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Abyss Stash Tab 1...                                                              [OK]

[Error] Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
