### ISSUE TITLE
Error Procurement  Abyss

### ISSUE THREAD

**Issue by blacksun94** [Stickymaddness/Procurement#782]
[10-12-2017 20:14] System.ArgumentNullException: Il valore non può essere null.
Nome parametro: source
   in System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   in POEApi.Model.Gear..ctor(Item item)
   in POEApi.Model.ItemFactory.Get(Item item)
[10-12-2017 20:14] ItemFactory unable to instantiate type : The Calling
[10-12-2017 20:14] Error downloading stash for Standard, exception details: System.ArgumentNullException: Il valore non può essere null.
Nome parametro: source
   in System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   in POEApi.Model.Gear..ctor(Item item)
   in POEApi.Model.ItemFactory.Get(Item item)
   in System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   in POEApi.Model.Stash..ctor(Stash proxy)
   in POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   in POEApi.Model.POEModel.GetStash(String league, String accountName)
[10-12-2017 20:14] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   in POEApi.Model.POEModel.GetStash(String league, String accountName)
   in Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   in Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   in System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   in System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   in Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   in System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
