### ISSUE TITLE
can"t log in becouse of this error

### ISSUE THREAD

**Issue by justsomeuselessguy** [Stickymaddness/Procurement#783]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1546194/DebugInfo.log)

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
