### ISSUE TITLE
 [Error] Downloading stash for Standard, details logged to DebugInfo.log

### ISSUE THREAD

**Issue by 40423212** [Stickymaddness/Procurement#784]
[11-12-2017 9:39] System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 POEApi.Model.Gear..ctor(Item item)
   於 POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 9:39] ItemFactory unable to instantiate type : Citrine Amulet
[11-12-2017 9:39] Error downloading stash for Standard, exception details: System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 POEApi.Model.Gear..ctor(Item item)
   於 POEApi.Model.ItemFactory.Get(Item item)
   於 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 POEApi.Model.Stash..ctor(Stash proxy)
   於 POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   於 POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 9:39] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   於 POEApi.Model.POEModel.GetStash(String league, String accountName)
   於 Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   於 Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   於 System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.18.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.18.0)

Please install a clean copy of 1.18.0 and create a new issue if you have further problems.
