### ISSUE TITLE
Error after 1.18

### ISSUE THREAD

**Issue by theo1000** [Stickymaddness/Procurement#789]
Error reading character data for Fakundita, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Stickymaddness** [comment]
Have you used Procurement before?

Make sure you've got a "clean" installation of Procurement ie: extract the 1.18.0 zip into a new empty folder.

**Comment by theo1000** [comment]
did it nothing changes :/

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
