### ISSUE TITLE
Still dont work error 1.18.0 

### ISSUE THREAD

**Issue by Gutsuu** [Stickymaddness/Procurement#791]
[11-12-2017 15:09] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:09] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:09] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:09] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:09] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:09] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:09] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:09] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:13] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:13] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:13] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:13] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:13] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:13] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:13] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:13] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:14] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:14] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:14] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:14] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:25] System.IO.DirectoryNotFoundException: Nie można odnaleźć części ścieżki „C:\Users\Mateusz\Desktop\Procurement\matiwizi25@gmail.com\characterdata.bin”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   w POEApi.Transport.CachedTransport.GetCharacters()
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:25] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:25] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:25] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:25] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:27] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:27] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:27] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:27] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:29] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:29] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:29] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:29] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()
[11-12-2017 15:29] System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
[11-12-2017 15:29] ItemFactory unable to instantiate type : Stygian Vise
[11-12-2017 15:29] Error downloading stash for Abyss, exception details: System.InvalidCastException: Nie można rzutować obiektu typu 'POEApi.Model.Gear' na typ 'POEApi.Model.Gem'.
   w POEApi.Model.Gear.<>c.<getSocketedItems>b__34_0(Item proxy)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Gear..ctor(Item item)
   w POEApi.Model.ItemFactory.Get(Item item)
   w System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w POEApi.Model.Stash..ctor(Stash proxy)
   w POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
[11-12-2017 15:29] System.Exception: Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   w POEApi.Model.POEModel.GetStash(String league, String accountName)
   w Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   w Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()

**Comment by Gutsuu** [comment]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Abyss Stash Tab 1...                                                              [OK]
Loading Abyss Stash Tab 2...                                                              [OK]
Loading Abyss Stash Tab 3...                                                              [OK]
Loading Abyss Stash Tab 4...                                                              [OK]
Loading Rudy_egzorcysta's inventory...                                                    

[Error] Error reading character data for Rudy_egzorcysta, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.

**Comment by Gutsuu** [comment]
Tnx its working :)

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
