### ISSUE TITLE
Error reading character - New version 1.1.8

### ISSUE THREAD

**Issue by twiices** [Stickymaddness/Procurement#792]
Error] Error reading character data for Tuais, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by Erthafein** [comment]
same thing for me. 

[Error] Error reading character data for Alyithra, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.


Have retry multiple times over the past few hours

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
