### ISSUE TITLE
Still doesnt work on 1.18.0

### ISSUE THREAD

**Issue by RafBin** [Stickymaddness/Procurement#793]
can u help me ?

Authenticating rafbin4@gmail.com                                                          [OK]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Abyss Stash Tab 1...                                                              [OK]

[Error] Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by waddlin-penguin** [comment]
Take out any abyss jewels that you have in stygian vise belts. That's the reason for the crash, and taking it out will (temporarily) avoid this issue.

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
