### ISSUE TITLE
error after "loading abyss stash tab 2"

### ISSUE THREAD

**Issue by nabbelator** [Stickymaddness/Procurement#796]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1560766/DebugInfo.log)

hello
i have an error at the abyss stash loading. after "loading abyss stash tab 2" comes the error always.
the standard stash tab loadings before and comes no error

edit
sorry was my fail, i had a "abyss belt" with a jewel inside in this stash tab, i have remove the jewel from the belt and now works again :D

**Comment by Stickymaddness** [comment]
Support for abyss belts (with socketed jewels) is now supported in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)
