### ISSUE TITLE
Error after Abyss Stash Tab 1

### ISSUE THREAD

**Issue by xGroda** [Stickymaddness/Procurement#798]
Loading Abyss Stash Tab 1...                                                              [OK]

[Error] Downloading stash for Abyss, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

**Comment by xGroda** [comment]
Abyss items causing the error...

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0)

Please install a clean copy of 1.19.0 and create a new issue if you have further problems.
