### ISSUE TITLE
Use of API

### ISSUE THREAD

**Issue by Zarwalski** [Stickymaddness/Procurement#799]
Hi there,

I am making my own tool that looks at stash tabs, though does very different functionality to what your tool does (mine only deals with Jewels specifically and filtering and sorting)

Your API around this looks really easy to navigate and would be similar to what I would write myself.

Could I get your permission to use your API.Models API.Transport and API.Infrastructure projects in mine. I will give any citation you require me to use.

Many thanks,

**Comment by Stickymaddness** [comment]
Hi,

Sure, you're more than welcome to reuse the Procurement libraries in your project.

Procurement is under the Artistic License 2.0, so it's not required but a mention/citation would be appreciated!

Send me a link to your project when you're ready, I would be interested to see it.

**Comment by Zarwalski** [comment]
Thank you very much. I shall use the same licence for mine too and make sure i cite you to give you credit where credit is due :)

I'm still a while off from completion, but that's what Christmas holiday is for right? :D

**Comment by Stickymaddness** [comment]
No problem, have fun!
