### ISSUE TITLE
DLL ISSUE

### ISSUE THREAD

**Issue by DJDIAS2018** [Stickymaddness/Procurement#800]
give me a message crash error when i try start program ''api-ms-win-core-synch\1-2-0.dll error''

**Comment by DJDIAS2018** [comment]
problem solved but now i cant copy and paste

**Comment by Stickymaddness** [comment]
Please update to [Procurement 1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0), and create a new ticket if this is still an issue.
