### ISSUE TITLE
error reading character data/downloading stash

### ISSUE THREAD

**Issue by SavageAsFudge** [Stickymaddness/Procurement#806]
Since the start of Abyss league procurement won't open.

Also, poe.trade lists my items in standard even though I went through every stash tab and made sure none are on public setting and there are no prices set on items. I assume something went wrong when the game converted my stash from Harbinger to Standard, since the items listed are in Remove only Tabs.

I believe theres a setting in procuremet that lets me deactivate my standard shop.

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1580993/DebugInfo.log)

Thanks a bunch
Merry Christmas!

**Comment by Stickymaddness** [comment]
Update to Procurement [1.20.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.20.0)
