### ISSUE TITLE
divination card stash incorrect abyss

### ISSUE THREAD

**Issue by silic0ns0ul** [Stickymaddness/Procurement#807]
updated to most recent v1.20.0

does not appear to download the "divination stash tab" correctly in Abyss. many cards/stacks missing.

in game, tried changing selection to ALL, OWNED, FULL STACK. no change.

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/1593963/DebugInfo.log)

**Comment by aydjay** [comment]
#757 will need to be merged in for correct divination stash support. Until that happens there will be incorrect behaviour,
