### ISSUE TITLE
Everything is downloaded n+1 times after failing to login n times

### ISSUE THREAD

**Issue by SoonDead** [Stickymaddness/Procurement#82]
I have failed to log in 3 times and succeeded the 4th time.

Everything is downloaded 4 times, as this screenshot shows:

![procurementbug2](https://cloud.githubusercontent.com/assets/988167/6276158/04834e7e-b885-11e4-87fa-4c06f47e426d.png)

It not only loads much slower, but reaches GGG-s request limit and waits for even more time.

**Comment by SoonDead** [comment]
This might be a display issue only where the code does not properly unsubscribes from the events if the authentication throws an exception.

**Comment by Stickymaddness** [comment]
This is a bug that seems to have resurfaced, previously the issue was due to the events not being deregistered after a failed login, I'll look into why it has reappeared.

**Comment by Stickymaddness** [comment]
I've done some testing and can't replicate this in the latest version, please test and let me know if it's still an issue.
