### ISSUE TITLE
Recipe-specific dynamic loot-filter customizations

### ISSUE THREAD

**Issue by thailyn** [Stickymaddness/Procurement#821]
I use the [NeverSink](https://github.com/NeverSinkDev/NeverSink-Filter) loot filter (like probably most everyone who plays PoE), and in my local Procurement repo I've implemented updating the loot filter with some custom rules every time I recreate the recipes.  This mostly includes adding a rule to highlight normal items to finish partially-complete SameBaseType recipes, but I've also hard-coded in a list of base types to highlight for chancing specific uniques.

Right now it's pretty messy and has a bunch of stuff hard-coded, but I could work on cleaning it up and creating a PR if this is something that would be useful.  There would be a lot of customizations/options I would need to figure out how to do it in UI.  I also don't know if it would be useful to have support for modifying only one type of loot filter (it depends on searching for known strings in the NeverSink filter).

**Comment by Stickymaddness** [comment]
Is this still something you'd like to add?

**Comment by thailyn** [comment]
It's something I still use as a local modification to Procurement.  If it is indeed something you would be interested in merging, I can work on cleaning it up and all (would make my life a whole lot easier).
