### ISSUE TITLE
Req: add "increased Elemental Damage" filter(s)

### ISSUE THREAD

**Issue by mbourgon** [Stickymaddness/Procurement#824]
Howdy!  Awesome app, wish I'd known about it earlier. 

One request: could you add a filter for "increased Elemental Damage with attack skills" or just "increased Elemental Damage"?  Probably the latter, since that's what Jewels, Sceptres, and Shield seems to use.  

Thanks!

**Comment by thailyn** [comment]
Hi, @mbourgon .  The 1.21.0 release includes filters for "increased Elemental Damage" and "increased Elemental Damage with Attack Skills".  Note that the two filters do not overlap; the "increased Elemental Damage" does not include increases for attack skills.

Also, as with similar stat filters, this does not look at Abyss Gems.  This is a known issue and I hope to fix it soon.
