### ISSUE TITLE
I can't log in because of - [Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by RMX99** [Stickymaddness/Procurement#828]
Hi! When I want to log in it shows me something like this: 

Authenticating < email address >                                                        [OK]
Fetching account name...                                                                  [OK]
Loading characters...                                                                     [OK]
Loading Standard Stash Tab 1...                                                           [OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log

How to overcome it? What's goin' on? It's my first time when I want to log in

**Comment by thailyn** [comment]
Can you attach your DebugInfo.log file or paste its contents?  That should have more info on what is going wrong.

Do you have any rare or high-level items (fishing rods, etc.) in your stash?  There are some items that aren't supported yet, but we haven't been able to get examples of them ourselves or enough info from users to fix the issues.
