### ISSUE TITLE
League Selection

### ISSUE THREAD

**Issue by Jourmungar** [Stickymaddness/Procurement#832]
I am using this software for about a week without any issues, but now I set some rings for sale, but it started crashing afterwards, with the error message shown below. Now every time I try to open the program, it works, but it crashes constantly when selecting the league (BRE001)
![190](https://user-images.githubusercontent.com/39461458/40279907-11b0c3b4-5c43-11e8-9f2d-1e5b649401cb.PNG)

**Comment by thailyn** [comment]
Hi, can you attach your `DebugInfo.log` file?  That will contain more information about the error.

Also, when you say "rings" do you mean the breach rings in that screenshot?  Which league is BRE001?  Is it one of the bestiary race leagues?  Thanks!

**Comment by Jourmungar** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2020552/DebugInfo.log)
no, just some random rare/unique rings, and it is a normal league in the flashback event

**Comment by Jourmungar** [comment]
so if I get rid of my necromancy net completely, will the bug be resolved?

**Comment by thailyn** [comment]
If my theory is correct, then it should.  Alternatively, you could put those nets in the inventory of a character, and in Procurement's settings choose to only download selected characters, and exclude the character with the nets.

**Comment by Jourmungar** [comment]
yes thanks, everything is working now, I gave it to my friend so problem solved

**Comment by Stickymaddness** [comment]
Procurement 1.22.0 has been released which includes support for nets
