### ISSUE TITLE
Some tabs disappear after filtering

### ISSUE THREAD

**Issue by thailyn** [Stickymaddness/Procurement#852]
I noticed that some tabs disappear permanently after using a filter.  When the filter is removed, these tabs do not reappear, as they should.

Initial state: currency and essence tabs sit before divination card tab:
![image](https://user-images.githubusercontent.com/292581/40592175-113b2fd0-61ea-11e8-86dc-294bb8f64df4.png)

Enter a search term in the search box (side note: items in currency tabs are not found in searches):
![image](https://user-images.githubusercontent.com/292581/40592195-56d590ee-61ea-11e8-833f-254888bd9b9d.png)

Remove the search query.  The currency and essence tabs are missing.
![image](https://user-images.githubusercontent.com/292581/40592211-97ff13ce-61ea-11e8-9e35-29de910508e3.png)

The missing tabs do show up in the pulldown menu that lists tabs.  However, when selecting one of the missing tabs, nothing is shown, like what happens when selecting a tab that has no items matching the search conditions.
![image](https://user-images.githubusercontent.com/292581/40592238-d84f3c4c-61ea-11e8-980e-5bc955fc0284.png)

The missing tabs are restored after refreshing all tabs or switching to another league and back to the original one.

**Comment by aydjay** [comment]
This is resolved with #915
