### ISSUE TITLE
Fragments Stash tab is not supported.

### ISSUE THREAD

**Issue by thailyn** [Stickymaddness/Procurement#857]
The Fragments stash tab (with type `FragmentStash` in the JSON) does not show up properly in Procurement.  Only any "Sacrifice at Dusk/Dawn/etc." are displayed, and other items can not be searched for in the UI.

How a fragment stash tab currently looks:
![image](https://user-images.githubusercontent.com/292581/40622173-320b8032-626e-11e8-8507-3fc3c3d80eff.png)

How it probably should look (taken from the official website):
![image](https://user-images.githubusercontent.com/292581/40622226-862e881c-626e-11e8-99cb-61b0ffe7c8eb.png)

**Comment by aydjay** [comment]
If you could attach a fragment stash tab json I will slap one together. I don't own one myself.

**Comment by thailyn** [comment]
I've included the BIN file for a fragments stash tab.  It basically has the same contents as the above screenshot.  I removed all the unrelated tabs so the file isn't gigantic (it's tab 12).  Also apparently GitHub doesn't support attaching `.bin` files.  Not that the actual extension means anything....

I haven't gotten any of the other types of items, but I'm pretty sure (by comparing the icons and extrapolating) the other three sets of four items are the other [map fragments](https://pathofexile.gamepedia.com/Fragments): Advanced Vaal fragments in the top right, Prophecy fragments in the bottom left, and Atlas fragments in the bottom right.  And I expect the row of items above the splinters are the corresponding [Breachstones](https://pathofexile.gamepedia.com/Breachstone).

[fragments.bin.txt](https://github.com/Stickymaddness/Procurement/files/2060690/fragments.bin.txt)

**Comment by aydjay** [comment]
If you could login to the POE website and pinch the image they give for the fragment stash.

Press F12 and dive through the assets that get loaded and grab the provided image. This is where the currency one sits for reference.
![image](https://user-images.githubusercontent.com/9460838/40836891-586ba8e0-6590-11e8-8a0a-b7ebd8fa419a.png)

**Comment by thailyn** [comment]
Ah, right, that would be helpful, wouldn't it?

![stashpanelfragment](https://user-images.githubusercontent.com/292581/40845110-ad6c35b0-6583-11e8-80db-16aebafc5c10.png)
