### ISSUE TITLE
[Error] Failed to load characters

### ISSUE THREAD

**Issue by 3RR0** [Stickymaddness/Procurement#86]
Sometimes I don't even reach the error of downloading stash and I get an error at Failed to load characters. I'm a steam user if that makes a difference.

**Comment by Bwas** [comment]
That's the message i got : 
Loading characters...                                                                     [OK]
Loading Mac_Five's inventory...                                                           

[Error] Error reading character data for Mac_Five, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

**Comment by ManuelHirsch** [comment]
As of today the POST request to "/.../get-items" seems to require the "accountName" field additionally.

**Comment by comamitc** [comment]
Fix provided here: https://github.com/medvedttn/Procurement/releases/tag/1.9.1

**Comment by Stickymaddness** [comment]
Procurement 1.9.1 has been released, which fixes this issue!

https://github.com/Stickymaddness/Procurement/releases/tag/1.9.1
