### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Gsalsa13** [Stickymaddness/Procurement#866]
Error downloading account name, exception details: System.ApplicationException: Unable to deserialize object
   em POEApi.Model.POEModel.GetProperObjectFromTransport[T](Stream networkData)
   em POEApi.Model.POEModel.GetAccountName()

**Comment by thailyn** [comment]
Hi, thanks for the report.  Please attach the DebugInfo.log file so we can better diagnose the issue.
