### ISSUE TITLE
Cant login because of SSF Standard stash

### ISSUE THREAD

**Issue by rayuga4** [Stickymaddness/Procurement#870]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2088089/DebugInfo.log)

**Comment by thailyn** [comment]
Hi, thanks for the report.  Procurement is getting a 404 error (not found) from the server.  This might be a temporary issue, so please try again in a short while.

Also, can you provide more information on the issue: is this the first time you're using Procurement?  Or did the problem just start happening?  Did you just start playing in a league, or the first time after the leagues changed?  Did you delete any characters or transfer from SSF to standard?  Thanks!

**Comment by rayuga4** [comment]
Hi there sry for late reply, well i played in abyss league where i started using procurement, also where i created the ssf characters that got moved to standard, and i didnt play from abyss league end till this league, so when i launched procurement it said there was an update i went and downloaded it, when i tried to login the error happened

**Comment by rayuga4** [comment]
maybe the error was caused because i never used tge ssf stash, the ssf characters were used for oni farming so never "seen" the stash

**Comment by thailyn** [comment]
Thanks for the additional information!  My thought right now is that, if Procurement still thinks you had characters in the Abyss league, it might be requesting them from the GGG API.  When you request a tab that doesn't exist (such as when the temporary league ends), the API returns a 404 error.  Unfortunately, Procurement doesn't log info about which URL is giving the 404 (I should fix that), so I can't tell for sure right now, based on the log file you gave.

Are you still getting the issue?  If so, can you try deleting or moving the directory Procurement uses to save the `.bin` files for your account?  If that doesn't fix it, and if you have Procurement downloading only selected characters and/or leagues, and that includes leagues that don't exist, remove references to them from the `Settings.xml` file (or change the values for `DownloadOnlyMyLeagues` and `DownloadOnlyMyCharacters` to `False` in that file).

**Comment by rayuga4** [comment]
welp i "fixed" it by migrating the ssf characters, so there is no ssf standard stash then it logged it normally
