### ISSUE TITLE
EnDurance Issue

### ISSUE THREAD

**Issue by EnDurance123** [Stickymaddness/Procurement#874]
[15-06-2018 19:26] Error downloading stash for Standard, exception details: System.Net.WebException: Удаленный сервер возвратил ошибку: (502) Недопустимый шлюз.
   в System.Net.HttpWebRequest.GetResponse()
   в POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   в POEApi.Transport.HttpTransport.GetStash(Int32 index, String league, String accountName)
   в POEApi.Transport.CachedTransport.GetStash(Int32 index, String league, String accountName, Boolean refresh)
   в POEApi.Model.POEModel.GetStash(Int32 index, String league, String accountName, Boolean forceRefresh)
   в POEApi.Model.POEModel.getAllTabs(String league, String accountName, Stash stash)
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
[15-06-2018 19:26] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   в POEApi.Model.POEModel.GetStash(String league, String accountName)
   в Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   в Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__30.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass29_0.<Login>b__0()
   в System.Threading.Tasks.Task.Execute()
[15-06-2018 19:30] System.Net.WebException: Удаленный сервер возвратил ошибку: (502) Недопустимый шлюз.
   в System.Net.HttpWebRequest.GetResponse()
   в POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   в POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   в Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass29_0.<Login>b__0()
   в System.Threading.Tasks.Task.Execute()

**Comment by thailyn** [comment]
A 502 error indicates there is an issue with GGG's site/API.  It also looks like the pathofexile.com site isn't working properly.  So this isn't an issue on Procurement's end.  You'll need to try again later.

**Comment by EnDurance123** [comment]
Thank you!
