### ISSUE TITLE
cant login into procurement

### ISSUE THREAD

**Issue by okan-bayrak** [Stickymaddness/Procurement#879]
I cant login into procurement i just downloaded it and im new to the game.
It always fails at Loading standard stash tab 1

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2216305/DebugInfo.log)

**Comment by thailyn** [comment]
The log file indicates Procurement is getting a 404 (not found) error when attempting to use GGG's API.  I've seen this reported a few times, but I'm not sure the root cause yet.  Are you still experiencing an issue?

**Comment by Xiaminou** [comment]
same

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2272125/DebugInfo.log)

**Comment by thailyn** [comment]
Thanks for the report, @Xiaminou.  Do you get the same error if you try to log in again?  The `DebugInfo.log` file suggests Procurement might be getting some corrupted/invalid data from GGG's API, which might be a temporary issue.  Have you been able to log in with Procurement previously?  Also make sure your account name is entered correctly.  Thanks!

**Comment by Xiaminou** [comment]
It's my first time using this program, I tried 3 times in 2 minutes interval and nothing.

**Comment by Stickymaddness** [comment]
Please retest with a newer release of Procurement, and create a new issue if you still experience any issues.
