### ISSUE TITLE
Shop is not updated

### ISSUE THREAD

**Issue by Ezekhael** [Stickymaddness/Procurement#882]
Login normal, stash updates, but can't update forum thread ( get msg succefully updated, but nothing happen)
E.D: Manual c/p work

**Comment by jgm-gh** [comment]
Same issue here.

**Comment by benjaminjthomas** [comment]
Yep me too

**Comment by thailyn** [comment]
Hey, thanks for reporting the issue.  Can you please attach your `DebugInfo.log` file to this issue, so I can see if there is more information on the error that is happening?  I personally don't use Procurement's shop-related features, but I can try to figure out what's going on.  Thanks!

**Comment by Rafellus** [comment]
In my case the DebugInfo have this:

> [10-10-2018 7:08] Error updating shop thread: System.Net.WebException: Se excedió el tiempo de espera de la operación
>    en System.Net.HttpWebRequest.GetResponse()
>    en POEApi.Transport.HttpTransport.downloadPageData(String url)
>    en POEApi.Transport.HttpTransport.getThreadHash(String url, String regex)
>    en POEApi.Transport.HttpTransport.UpdateThread(String threadID, String threadTitle, String threadText)

File: [DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2464441/DebugInfo.log)

So this could be fixed with the pull request "Use generic hash regex when updating shops. #886"?

**Comment by thailyn** [comment]
Hi, @Rafellus, thanks for including a DebugInfo.log file.  It looks like this is the same error I saw while debugging the issue, so, yeah, it should be fixed by that PR.  If not, that PR also adds more logging so I can better investigate similar issues going forward.
