### ISSUE TITLE
[Error] Downloading stash for Standard

### ISSUE THREAD

**Issue by UreKismet** [Stickymaddness/Procurement#883]
I have just updated procurement after a long spell away from poe. procurement locked loading stash tab 14 standart mode and instructed 1) I open issue at github.
B) include debug log  which I have

**Comment by thailyn** [comment]
Hi, @UreKismet.  If you're still encountering an issue, please attach the `DebugInfo.Log` file to this issue.  That file is located in the same directory as `Procurement.exe`.  Thanks!
