### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by tinki-winki** [Stickymaddness/Procurement#887]
Login failed after downloading

There was an unhandled error - Sorry! Please create a ticket on github 
[Procurement.zip](https://github.com/Stickymaddness/Procurement/files/2430399/Procurement.zip)

**Comment by tinki-winki** [comment]
tried again with specifying to load delve league only, same mistake

https://code.google.com/archive/p/procurement/wikis/HowToOnlyDownloadSelectedLeagues.wiki

**Comment by Stickymaddness** [comment]
This should be fixed in the newer releases of Procurement, please create a new issue if you still experience any issues.
