### ISSUE TITLE
Error when downloading tabs

### ISSUE THREAD

**Issue by MLanghof** [Stickymaddness/Procurement#89]
Was messing around with my standard stash after the league merge and had procurement loading up in the meantime (figured I'd go for those nice vendor recipes).

http://pastebin.com/wQ3unBnU

I suppose some tabs went out of existence while you were querying for them because I emptied them. Just from a very rough look on it.

**Comment by Stickymaddness** [comment]
Looks like Procurement is getting back null data from GGG, are you still experiencing this issue?

**Comment by MLanghof** [comment]
Um. As I said, this was potentially the result of emptying a stash between starting the download request and actually downloading said tab. I have a hard time generating remove-only tabs on demand (and don't feel like sacrificing race rewards for it).

I've actually not used Procurement in a while (playing beta, and acquisition was just more convenient in the previous leagues), sorry!
