### ISSUE TITLE
Error Log In Procurement 

### ISSUE THREAD

**Issue by mag2392** [Stickymaddness/Procurement#890]
Hi, i have a problem when i try to log in. The error is Downloading Dash for Standard. This is my DebugInfo.
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2447860/DebugInfo.log)

**Comment by thailyn** [comment]
Hi, @mag2392.  You're using a really [old version](https://github.com/Stickymaddness/Procurement/issues/831#issuecomment-389714881) of Procurement.  Please download the latest version (currently 1.23.0) and try again.

**Comment by mag2392** [comment]
Ok, it's done. Thank you so much!
