### ISSUE TITLE
Error loading items

### ISSUE THREAD

**Issue by Cardosu007** [Stickymaddness/Procurement#893]
Error getting items for league, are you sure your league settings are correct?

DebugInfo:

[16-11-2018 9:50] 
Error: attempted to get items for the non existant league ''
Current leagues are:

Exception details : 
System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
   em System.ThrowHelper.ThrowKeyNotFoundException()
   em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   em Procurement.ViewModel.StashViewModel.getAvailableItems()

[16-11-2018 9:50] Application Version: Procurement 1.23.0
[16-11-2018 9:50] 
CurrentCulture: pt-BR
CurrentUICulture: pt-BR
Operating System: Microsoft Windows NT 6.2.9200.0
Current League: 

[16-11-2018 9:50] System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em Procurement.ViewModel.InventoryViewModel..ctor(InventoryView inventoryView)
   em Procurement.View.InventoryView..ctor()
   em Procurement.ViewModel.ScreenController.<>c.<initScreens>b__33_0()
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aydjay** [comment]
https://github.com/Stickymaddness/Procurement/releases

Please try latest version
