### ISSUE TITLE
Procurement offline

### ISSUE THREAD

**Issue by Lancten** [Stickymaddness/Procurement#900]
Error the external server is offline, server is not available error code 503

**Comment by Gravijas** [comment]
Thank god Im not the only one. wasted 1 hour getting it wo work.

**Comment by aydjay** [comment]
Closed by #902

**Comment by Stickymaddness** [comment]
[Procurement 1.24.1](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.1) has been released, which fixes this issue _when using SessionID_
