### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by XnIcRaM** [Stickymaddness/Procurement#914]
I heve error when I try to login (I use session id) I have Procurement 1.21.1

[19-12-2018 20:50] System.Exception: Cloud flare clearance failed, please wait one minute and try again ---> System.AggregateException: Wystąpił przynajmniej jeden błąd. ---> CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 3 attempt(s).
   w CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w POEApi.Transport.HttpTransport.CloudFlareSessionIdLogin()
   w POEApi.Transport.HttpTransport.Authenticate(String email, SecureString password, Boolean useSessionID)
   w POEApi.Model.POEModel.Authenticate(String email, SecureString password, Boolean offline, Boolean useSessionID)
   w Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass29_0.<Login>b__0()
   w System.Threading.Tasks.Task.Execute()

**Comment by XnIcRaM** [comment]
Also what I should use as "Alias" when I "Use SessionID"?

**Comment by aydjay** [comment]
Your alias should be your account name. You are getting the cloud flare error so just wait 30 seconds and try again.

**Comment by crackingSounds** [comment]
Still cant login, tried it many times, even used alias one. Still cant login.

**Comment by aydjay** [comment]
@crackingSounds  Once you've logged into the path of exile website, in the top left hand corner will be a link next to:

"Logged in as:"

Click on that, that will direct you to:

https://www.pathofexile.com/account/view-profile/THIS_IS_YOUR_ALIAS

Grab the alias from the end of the URL

Then grab the cookie as described on the wiki:

https://github.com/Stickymaddness/Procurement/wiki/SessionID

If it is still not working these steps could you please let me know the answer to the following questions:

a) Have you ever been able to login using the alias method?
b) Is your account via steam?
c) Do you have an account that you signed up with directly with pathofexile.com?
d) Are you using one of the localised sites? (BR, RU, TH...)
e) What version are you using, cloudflare circumvention is only in: V1.21.1

Hope you get logged in soon.

**Comment by crackingSounds** [comment]
@aydjay Hello, Tried your this method too and did as you told me.
regarding the questions:
a) I never tired alias method as it used to get login through normal method during previous leagues.
b) No, its not.
c) Yes, I am using that account to play.
d) No, I dont think so.
e) I am using the latest one 1.24.1 and 1.24.2.
 
Its still showing cloud flare clarence failed

**Comment by crackingSounds** [comment]
If i use the email method then it shows Error(503) - server error.

**Comment by aydjay** [comment]
Ok thanks for the info. We will have to resolve the email login via cloud flare. Currently only login with alias will get you past cloudflare.

**Comment by Stickymaddness** [comment]
The next release will remove the ability to login via email, as SessionID is the only mechanism we are now able to support,
