### ISSUE TITLE
Crashing when loading a stash tab

### ISSUE THREAD

**Issue by tr4cefl0w** [Stickymaddness/Procurement#916]
It suddenly started. I deleted Procurement then downloaded it again, same issue. Version 1.24.1 both times.

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2699897/DebugInfo.log)

**Comment by aydjay** [comment]
Can you attach the bin files which are in your application directory - you might need to zip them up and put them on drop box. They will be in a folder that has your alias name on it.

**Comment by tr4cefl0w** [comment]
Here you go!
[issue-916.zip](https://github.com/Stickymaddness/Procurement/files/2701142/issue-916.zip)

**Comment by tr4cefl0w** [comment]
Glad my fishing rod can finally be used for something :joy:

**Comment by Stickymaddness** [comment]
I've released the fix as part of [Procurement 1.24.2](https://github.com/Stickymaddness/Procurement/releases/tag/1.24.2)!
