### ISSUE TITLE
Essence Combination recipe 

### ISSUE THREAD

**Issue by aydjay** [Stickymaddness/Procurement#931]
3 Essences of same name!

Might be an idea to exclude essences in the essence tab as it already provides this functionality.

Exclude Shrieking and "Special" essences

**Comment by thailyn** [comment]
We probably shouldn't force excluding essence tabs, as the user still needs to know he has essences that can be upgraded in order to use the tab to perform the upgrades.  Plus, he could also manually exclude essence stash tabs from recipes in the settings page.

**Comment by aydjay** [comment]
Yep - fair shout
