### ISSUE TITLE
Divination card not added

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#947]
Boon of the First Ones divination card doesn't show up in export code.

But more importantly, can Procurement add items (at least ones with a price tag) to an "Others" spoiler tag which otherwise were missed by other tags? That could solve many similar issues in future.

It would also help with adding normal/magic rarity gear that are still valuable as base and has a price set but not currently showing up in export code unless they are 5 or 6-linked.

**Comment by aydjay** [comment]
If you could zip up your stash data and add it to this ticket that would help immensely. It's in the folder you installed procurement too in a folder named after your account name/login name.

**Comment by aydjay** [comment]
Update your data.xml with the data from: #948 until the next release.

@Stickymaddness Probably sensible to issue a release after #948 is merged in.

**Comment by Stickymaddness** [comment]
I've released Procurement 1.25.0 which fixes this as @aydjay mentioned
