### ISSUE TITLE
Item quantity/rarity search not working

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#949]
When I choose either Item Quantity or Item Rarity on Advanced Search no items show up even though I have quite a few of them.

Edit: Increased Attack Speed and Increased Cast Speed return no results as well.

**Comment by nqrcqn** [comment]
At the very least,

Increased Cold Damage
Increased Fire Damage
Increased Lightning Damage

have the same issue, from the looks of it, they aren't being checked in correct case like "**i**ncreased Cold Damage"

**Comment by nqrcqn** [comment]
Off topic, if anyone is up for it, more phrases can be supported like:

15% increased Item Quantity per White Socket
Nearby Allies have 30% increased Item Rarity
to Cold/Fire/Lightning and Chaos Resistances

**Comment by aydjay** [comment]
![image](https://user-images.githubusercontent.com/9460838/52285269-f45ddc00-295d-11e9-877d-9c1cc0800c25.png)

Looks ok for me, this is using V1.24.2

If you could link the items that have the mods that you want filters included for and the appropriate bin files, that have those items that would help alot.

The bin files are in a folder with your account name next to where you have procurement installed.

**Comment by nqrcqn** [comment]
Looks like an issue with handling OS locale, lower case of I or upper case of i both differs from the english equivalent on my system.

**Comment by aydjay** [comment]
What locale is your system set too?

**Comment by nqrcqn** [comment]
Turkish
