### ISSUE TITLE
Exclude tabs by name or hide race reward tabs.

### ISSUE THREAD

**Issue by QuickBASIC** [Stickymaddness/Procurement#95]
Race reward tabs can't be renamed and always end up as the first tab shown in Procurement. 

If they can't be determined programmatically to be race reward tabs, I wouldn't mind adding them manually to my Settings.xml. (Similar to MyTabs section.)

At the moment one could list the tabs that you want specifically, but I'd like to have an option for download EVERYTHING except this tab instead.

**Comment by Stickymaddness** [comment]
I'll try get this improvement in for the next release, do you have a set of .bin files from your Procurement folder that you can send me which include race rewards? I haven't taken part in a race in quite a while, so don't have any race tabs myself to test with.
