### ISSUE TITLE
Map stash tab not displayed

### ISSUE THREAD

**Issue by Ydoum** [Stickymaddness/Procurement#952]
I've tried clearing app data and 'reinstalling', but map stash tab still won't load. It shows empty grid. I'm using session ID for logging in, as the standard option never works since 2017.

Any suggestions?

**Comment by thailyn** [comment]
Procurement doesn't support map stash tabs, as they are not currently supported by GGG's API, unlike all the other stash types.  It's a [known issue](http://www.pathofexile.com/forum/view-thread/1733474) by GGG.

**Comment by Ydoum** [comment]
Thank you for the insanely quick response.
