### ISSUE TITLE
No item bg colors in 1.25.0

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#957]
Compared to 1.24.2 items no longer have a blue or red background, so stashes look a little darker. Was this an intentional change?

**Comment by Stickymaddness** [comment]
Not intentional no, this is a bug!

**Comment by Stickymaddness** [comment]
This has been fixed in [Procurement 1.25.1](https://github.com/Stickymaddness/Procurement/releases/tag/1.25.1), thanks for reporting!
