### ISSUE TITLE
Many gems not being recognized

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#959]
I don't know why or for how long this has been the case but some gems are not being recognized as of 1.25.1

Fortunately I was able to add them to forum export using {UnknownItems}

Screenshot added. Some gems are recognized, many aren't and they have a transparent white background instead of dark green.

![gems](https://user-images.githubusercontent.com/47343000/52771216-6ca35c00-3046-11e9-8a39-753c46f02e88.png)

**Comment by nqrcqn** [comment]
This issue seems to happen only on level 20 and 21 gems, level 19 and lower are recognized correctly

**Comment by aydjay** [comment]
Also looks like they aren't showing the experience progress bar.

**Comment by nqrcqn** [comment]
Yes , since those aren't supposed to, my guess is same issue with gems that reach max lvl at lvl 1 or 3 etc

**Comment by aydjay** [comment]
Can you check with this version from my PR.

https://ci.appveyor.com/project/Stickymaddness/procurement/builds/22363798/artifacts

That should resolve it.

**Comment by nqrcqn** [comment]
Appears to be fixed
