### ISSUE TITLE
can't logon

### ISSUE THREAD

**Issue by FlamingQaz** [Stickymaddness/Procurement#963]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2876617/DebugInfo.log)
 yes i am using the latest version

**Comment by Stickymaddness** [comment]
Looks like server side issues on GGG's end, try login to Procurement again, if that still doesn't work I'd relog on the website to force a new sessionId and try again.

**Comment by FlamingQaz** [comment]
Thanks it's fixed now :D
