### ISSUE TITLE
Synthesis Support

### ISSUE THREAD

**Issue by aydjay** [Stickymaddness/Procurement#965]
Checklist for work that needs to be done for full Synthesis support.

Taken from:

https://youtu.be/ThYCp7bjDa0?t=172

- [x] New item type, Fractured
- [ ] Will need a new item hover header same as shaper and elder items - Looks like there is one for a fractured item and one for a synthesised item. Need to confirm this though.
- [ ] New type of mod, Broken this needs to be accommodated in the pob export code.
- [ ] New item bases with new implicits - in theory this should already be supported but we would need test data to prove this.
- [x] Synthesis banner update for the MainWindow

Please post in this thread if more information comes to light, json test data to support these items and api paperwork from GGG would be great. If you come across it please post it up!

**Comment by Stickymaddness** [comment]
The 3.6 changes are going to necessitate quite a few changes in Procurement, especially from an item display perspective. Two noteworthy ones:

- [ ] Fractured items have locked affixes, which are displayed differently to other affixes. 
- [ ] Lab enchants that are now a separate modifiers and will no longer overwrite implicits.

There are also some new interesting affixes that have been teased, that might be good candidates for adding to the search filters, for example  `% spell damage leeched as ES`

**Comment by thailyn** [comment]
The full details for the API changes for Synthesis are now available [here](https://www.pathofexile.com/forum/view-thread/2333275).

In summary, items can have a `synthesised` boolean property, and will have "Synthesised" add to the beginning of the type line (but after "Superior").  Items can also have a `fractured` boolean property, and a new `fracturedMods` property, which behaves similarly to `explicitMods` but sorts before them.

Side note: why the heck is it not "synthesized"?!

**Comment by thailyn** [comment]
New divination cards from the [post about the patch notes](https://www.pathofexile.com/forum/view-thread/2333649) (it also contains a list of the maps and their new tiers):

```
The Seeker
The Messenger
The Mad King
Boon of Justice
The Journey
Arrogance of the Vaal
The Landing
Seven Years Bad Luck
The Golden Era
Monochrome
Dark Temptation
Alone in the Darkness
Sambodhi's Vow
The Lord of Celebration
```

**Comment by thailyn** [comment]
Also, `Added Chaos Damage Support` and `Detonate Mines` will no longer be drop-only gems in 3.6, as per the [patch notes](https://www.pathofexile.com/forum/view-thread/2333648#worldchanges).

**Comment by aydjay** [comment]
> Side note: why the heck is it not "synthesized"?!

Because American English is incorrect! 

https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences

**Comment by aydjay** [comment]
Ok the new login screen looks dope AD

**Comment by Stickymaddness** [comment]
Thanks, little something I had up my sleeve 😁
