### ISSUE TITLE
Currency image incorrect rendering

### ISSUE THREAD

**Issue by aydjay** [Stickymaddness/Procurement#966]
With the latest build (As of today)

![image](https://user-images.githubusercontent.com/9460838/53091285-74ad4100-3509-11e9-90f3-b143fc3fecf7.png)

- [x] All the currency images don't line up
- [x] The inbuilt stack that used to be on the image (IIRC) is gone

Old image looked like this:
https://web.poecdn.com//image//Art//2DItems//Currency//CurrencyAddModToMagic.png?scale=1&scaleIndex=3&stackSize=37&w=1&h=1&v=97e63b85807f2419f4208482fd0b4859

Notice the stack and scale in the URL, new response from GGG is as follows.

https://web.poecdn.com//image//Art//2DItems//Currency//CurrencyAddModToMagic.png?scale=1&w=1&h=1&v=97e63b85807f2419f4208482fd0b4859

We could add the stack and scale into the URL by hand or we could remake the display. Not sure what is the best option.

**Comment by Stickymaddness** [comment]
Nice catch, that's pretty annoying 😞

**Comment by aydjay** [comment]
[initial currency fix.zip](https://github.com/Stickymaddness/Procurement/files/2889697/initial.currency.fix.zip)

Attached is a zipped up patch file. This will add the scale and stack to the icon URL.

I would pull request it but unfortunately, it's not a complete fix!

![image](https://user-images.githubusercontent.com/9460838/53176943-06d74700-35e7-11e9-807b-e3a2bbbc579c.png)

**Comment by thailyn** [comment]
Don't know if it's the same cause or not, but the images for items in quad stash tabs aren't being properly scaled anymore.

![broken layout](https://user-images.githubusercontent.com/292581/53304914-dbec2d80-3848-11e9-9591-11b23465b03e.png)

**Comment by aydjay** [comment]
Wouldn't surprise me at all, try and compare it with an "Old" bin file for a quad stash tab, that's how I diagnosed the currency issue. 

I tried to look on the GGG forums to see if it's a known issue but I couldn't see anything.

**Comment by Stickymaddness** [comment]
Just tested against a cached quad tab that I have, same issue appears to have borked quad tabs as well.

This is pretty frustrating, I'll try find some time to look into this as well.

**Comment by Stickymaddness** [comment]
From what I can see, the scale parameter on the API no longer makes a difference. On the website GGG are now using css to scale the images to fit in their appropriate slots, as follows:

For currency tab:

```css
transform: scale(0.8077);
```

For quad tab:

```css
transform: scale(0.5);
```

For fragment tab:

```css
transform: scale(0.641);
```

From this it is clear that we can no longer rely on the images provided by the cdn to be in the appropriate dimensions, nor should we, as we should be protecting the sizing and scaling of the images as needed by Procurement.

From my initial digging the easiest place to do this seems to be ItemDisplayModel as this is where the image is instantiated based on the item url, 

```csharp

        private double? _width;
        private double? _height;

        public ItemDisplayViewModel(Item item, double? width = null, double? height = null)
        {
            this.Item = item;
            _width = width;
            _height = height;
        }

```

```csharp

        public Image getImage()
        {
            if (Item != null)
            {
                try
                {

                    var img = new Image
                    {
                        Source = ApplicationState.BitmapCache[Item.IconURL],
                        Stretch = Stretch.Fill
                    };

                    if (_height.HasValue && _width.HasValue)
                    {
                        img.Height = _height.Value;
                        img.Width = _width.Value;
                    }

...

```

This can then be wired up to the getitem calls in the respective tab, for example in CurrencyStashViewModel,

```csharp
private const double CurrencyTabScale = 38.3388;

public ItemDisplayViewModel Exalted => GetCurrencyItem(OrbType.Exalted, CurrencyTabScale, CurrencyTabScale);
``` 

The magic 38.3388 is the resulting size of each currency item after scaling has been applied on the website.

With this change the currency tab now renders perfectly, and will allow us to remain pixel perfect in the future with minimal changes if GGG make further changes. It also wouldn't surprise me if further down the line regular item images change scale as well.

I have not looked into much of the xaml, as it was never my strong suit and it has been quite a while, but if we could achieve the same result by forcing the size on the style used by each slot, on each tab type, in xaml this would be far preferable to introducing sizing logic in the code.

**Comment by aydjay** [comment]
This is a great find! I'll dig into the XAML to see if there is something we can do from that perspective. Injecting it in from the viewModel's isn't ideal as it is very much a "View" concern.

**Comment by Stickymaddness** [comment]
Just tested the fix, we still have a few kinks to iron out unfortunately:

- [ ] Item slot in currency tab is misaligned 
- [ ] Divine Vessels are squashed in fragment tab, this probably has to do with the fact that they're 2 high as opposed to the rest of the slots in the tab that are 1 high
- [ ] Items in quad tabs are not properly aligned, especially noticeable on items in the bottom right corner

**Comment by aydjay** [comment]
Fragment tab I can't comment about as I don't have one, any changes I make there I make blind i'm afraid, it's a miracle it works at all tbh xD

The quad tab is a walking hack so i'm not surprised at all that it's not sitting perfectly. The layout generation is a very interesting WPF problem to resolve. This goes for quad and "Normal tab".

Item slot in currency and essence tab is "Borked" and have been since their inception i'm afraid. Definitely needs some more looking into.

I don't necessarily think that these are issue that are brought about with the changes that GGG have put in with regards to scaling but are they are known about (by myself atleast) and go back a while.

**Comment by Stickymaddness** [comment]
Pushed two PRs:

- Currency tab fixed (check PR comment)
- Fragment tab fixed
- Essense tab seems fine
- Quad tab will need some TLC

**Comment by Stickymaddness** [comment]
Closing this as the majority of the issues have been addressed, main outstanding item will be the ItemDisplay refactor and quad tab rework
