### ISSUE TITLE
Issues with Procurment

### ISSUE THREAD

**Issue by Fraggers92** [Stickymaddness/Procurement#967]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2898852/DebugInfo.log)

Here is the Debug Info file that Procurement told me to link. I'm not really sure what the issue is, but it persists throughout all copies of Procurement for me as I did get a fresh copy of Procurement and I got the same error. Thanks!

**Comment by thailyn** [comment]
There are 503 and 401 errors in the debug log when trying to log in or get the account name.  The former suggests an issue on GGG's part, while the latter an issue with logging in.  Make sure you're using the latest version of Procurement and are using Session ID to log in.  If it is a temporary issue on GGG's part, then there's nothing we can do.

**Comment by Fraggers92** [comment]
Yep I am using the latest version and using SessionID. I guess I’ll try it later today and get back to you. Thanks!

**Comment by Fraggers92** [comment]
After trying again with a fresh copy of Procurement the issue still exists. Is there anything that we can do or do we just have to wait? Thanks!

**Comment by thailyn** [comment]
Unfortunately, I don't know of a sure-fire way to solve the issue.  Logging in has been unreliable since GGG added CloudFlare protection, and I haven't figured out how to make the process smoother in Procurement.  You might indeed just need to wait.  I would also suggest logging out and back in in the browser you're using to get the Session ID value, which should get you a fresh Session ID cookie you can use.

**Comment by Fraggers92** [comment]
I an quite possibly the dumbest person to have existed. EVER. I'm
really not sure how, but I was logged out of the website and I never
checked that because it always kept me logged in. I am so sorry to
have wasted your time!!!

	-----------------------------------------From: "Charles Macanka" 
To: "Stickymaddness/Procurement"
Cc: "Fraggers92", "Author"
Sent: Monday February 25 2019 4:17:43PM
Subject: Re: [Stickymaddness/Procurement] Issues with Procurment
(#967)

**Comment by thailyn** [comment]
Don't beat yourself up.  You'll get logged out of the website automatically after a certain period of time.  It's after a while, but it will happen unannounced, and then the Session ID will stop working.  Glad you could get it working!

**Comment by aydjay** [comment]
Might be an idea to put the suggestion to log in to the main POE website once in a blue moon somewhere in the login UI.

**Comment by Stickymaddness** [comment]
Don't worry about it, after 6+ years of Procurement I can tell you this is far from the "dumbest" issue I've seen.
