### ISSUE TITLE
Cloud flare clearance failed, please wait one minute and try again

### ISSUE THREAD

**Issue by LucasIME** [Stickymaddness/Procurement#977]
Hi, 

I've been getting the following error when trying to log in with procurement:

> Cloud flare clearance failed, please wait one minute and try again

**Comment by thailyn** [comment]
CloudFlare is that extra layer of authentication GGG recently added, to try to prevent DDoS attacks.  You might have noticed the brief screen that loads when you go to the login page on the pathofexile.com website.  I've noticed it can get temperamental sometimes with Procurement.

Make sure the Session ID value you're using is still valid (you're still logged in on the web site).  Also, it might help to wait longer than a minute (maybe ten, unfortunately), or log out and back in on the website to get a new Session ID value.

**Comment by LucasIME** [comment]
Yeah, had to logout and log in again. Was trying to write a script to find duplicate itens on my stash tabs, but never managed to get a response back. Maybe I got my sessionID blacklisted by them or something like that :(

**Comment by thailyn** [comment]
Duplicate items in what way?  Maybe it's something Procurement can do now, or we can add it.  I've been thinking about ways and reasons to sort/search stash items.

**Comment by LucasIME** [comment]
Basically I want to get rid of some of the 150 tabs I have on standards, lol

What I wanted to do is find all the duplicate uniques I have (hoader and collector here), so I can remove most of them and keep a single copy only.

**Comment by thailyn** [comment]
Ah, yeah, I don't think Procurement can help with that task (right now).  But all I've got to say is, maybe hold off until the new tab is announced this week/next week; it's supposed to be [suited for collectors](https://www.reddit.com/r/pathofexile/comments/awg4bj/new_collector_tab_hype/). :smiley:

**Comment by LucasIME** [comment]
Wasn't aware of that announcement! Thanks for sharing!

Btw, managed to get my script running :) 
Used `cloudscraper` to bypass the Cloudflare check.
