### ISSUE TITLE
Portal gem not listed under Gems tab

### ISSUE THREAD

**Issue by Michaelangel007** [Stickymaddness/Procurement#991]
The `Portal` gem is not listed under the Gems tab.

![bug_portal_gem_not_listed_under_gems](https://user-images.githubusercontent.com/7876796/54225333-b1d97300-44b8-11e9-92d2-6ab6a7ec660f.png)

**Comment by aydjay** [comment]
That's odd. Might be to do with the fact that you have it socketed in the Tabula.

![image](https://user-images.githubusercontent.com/9460838/54264971-333e0d80-456c-11e9-808b-543fa1860fa1.png)

Could you attach your stash, please?

There will be a folder next to the procurement executable that will have your alias on it and it will be full of bin files.

Could you zip it up and attach it too this issue and I'll see what I can do.

**Comment by Michaelangel007** [comment]
Hmm, I noticed that my currency was showing the wrong amounts so I deleted the `<user>` folder  to force a re-sync of the stash tabs and now I'm getting this crash. :-/

[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2967630/DebugInfo.log)

**Comment by Michaelangel007** [comment]
Here are the old, stale .bin files zipped up. **Note:** .zip file is ~8 MB !

[previous_bin.zip](https://github.com/Stickymaddness/Procurement/files/2967700/previous_bin.zip)

**Comment by Michaelangel007** [comment]
:+1: For fixing this!

Had a minor error of login not working but that was solved via:

* rename account folder (to force a redownoad)
* Use the latest `POESESSID` cookie
