### ISSUE TITLE
Scorched Fossil not added to forum export

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#992]
I haven't had a chance to try with other fossils, but the 3 scorched fossils I have in my stash don't get added to forum export, I think it worked fine during Betrayal or a previous Procurement version. They used to show up under Currencies

**Comment by nqrcqn** [comment]
Just tested 1.25.2 and fossils work fine there, some change in 1.26.0 broke it.

**Comment by aydjay** [comment]
Will be this:

https://github.com/Stickymaddness/Procurement/pull/968/commits/150d4e23b4fd83047878840859aaae9601ad75b9

That broken it.

It will need a fossil runner adding.

**Comment by nqrcqn** [comment]
Didn't want to open another issue, sextants also seem to broken between 1.25.2 and 1.26.0. They are not being added to forum export anymore
