### ISSUE TITLE
Procurement Doesn't Pull Tabs In Trade Screen

### ISSUE THREAD

**Issue by shutEyEJerry** [Stickymaddness/Procurement#997]
So I recently updated to 1.2.6 (last I played was during Delve League) so I'm not sure what version I was on previously.
This might be user error, but when I select the tabs I want to port into the trade screen, they don't show up. I've only just started a new character, so I'm only trying to start a shop on one tab. I've attached screenshots of my trade screen, the tab I'm trying to trade, my template (at least the part that shows the tab in question) and my shop as it's currently set up.
https://gyazo.com/a7b9d87a2b4b28a95e2000ecab80d26e trade screen
https://gyazo.com/5b0b20e09dc4b1d06c89ad1ec6dc71f7 tab I'm selling
https://gyazo.com/eaa37d44f552717b5fd637b824fdf88b template
https://gyazo.com/5416dea3c05f8dfa76ffdba4d2ddadb9 shop

I've been able to successfully set this up before, so maybe I messed up. But I think something else is up. Any assistance would be appreciated.

**Comment by shutEyEJerry** [comment]
Update: I've gotten Procurement to work. For some reason, it was the template that was breaking it. I'm now using the vanilla template, but I don't want to use that.
I typically use the template ZiggyD uses in his procurement video. It's easy to dump items into 1c, 2c, 3c tabs, etc, so maybe there's something wrong with the template now that Procurement has been updated?

If there are any fast solutions for swapping out templates, that would be great.

**Comment by aydjay** [comment]
If you could post up the template that ZiggyD was showing I might be able to "Fix" it. Afaik ZiggyD hasn't used procurement in some years so it might be very out of date.
