### ISSUE TITLE
Item level

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#999]
Some items that don't show any item level in-game like sacrifice fragments or breachstones appear with an item level of 0 in Procurement. Those can be hidden. And perhaps the item level of maps can be shown in Procurement, whether or not that is useful.

**Comment by aydjay** [comment]
Could you attach some screenshots, please?

**Comment by nqrcqn** [comment]
I forgot to mention divination cards, they all show an item level of 0 in Procurement, that can be hidden as well. These items (except maps) don't show any item level on trade or in-game when alt is pressed.
![ilvl](https://user-images.githubusercontent.com/47343000/54516564-54d63500-4970-11e9-978d-0051d87fcf99.png)
